### ISSUE TITLE
UI script editor - wrong label on brightness when it sets brightness_pct

### ISSUE THREAD

**Issue by Octofinger** [home-assistant/frontend#10035]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm editing a script that will turn on a light (Philips Hue) and set it's brightness. The UI shows the label _Brightness_ when it actually sets the parameter _brightness_pct_

![image](https://user-images.githubusercontent.com/34031086/133301659-820b7f54-07ae-42d6-aa14-56213cee22ce.png)

### Describe the behavior you expected

The field for brightness should _either_
Be labelled _Brightness (pct)_
or
Actually set the parameter _brightness_

### Steps to reproduce the issue

1. Create or edit a script
2. Choose an action for a light entity that has brightness capability
3. Set brightness to anything but zero
4. Verify the resulting YAML
...

### What version of Home Assistant Core has the issue?

core-2021.9.6

### What was the last working version of Home Assistant Core?

core-2021.9.6

### In which browser are you experiencing the issue with?

Google Chrome Version 93.0.4577.63 and Opera Version:78.0.4093.184

### Which operating system are you using to run this browser?

Windows 7

### State of relevant entities

```txt
supported_color_modes:
  - brightness
color_mode: brightness
brightness: 191
off_brightness: null
friendly_name: Philips Hue 1 (Vägglampa nere)
supported_features: 41
```

**Comment by spacegaier** [comment]
I am not sure if that is something we need to change. Brightness values are always 0-100 % in the UI, independent of what the backend does. In the light more-info we use the same translation key (you could argue it is a bit more clear there since we have a 0-100 % percent slider).

If you use a service call in the automation editor, we show this:
![image](https://user-images.githubusercontent.com/114137/133597797-548a68d2-d547-4e1f-a182-27bef8e0feba.png)

So the current wording I think is consistent.

**Comment by Octofinger** [comment]
Hmm, you have a very valid point.

The _inconsistency_ arise when the UI is considered an interface to YAML and the terminology doesn't match.

But I get the point and I leave you to decide whether to see if UI can be clearer or just close this bug.
