### ISSUE TITLE
Why are browser versions that were only released last year, unable to display graphs in the local timezone?

### ISSUE THREAD

**Issue by del13r** [home-assistant/frontend#10273]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

all times are **incorrectly** shown in UTC when viewed in any web browser version that was last updated in February 2020, (see how 01:00 is in bold, that time is actually 12:00PM in my local timezone)

![image](https://user-images.githubusercontent.com/86141523/137419850-f10335a1-358b-47c1-8259-f66858d4ddeb.png)

while all times are **correctly** shown in local timezone when viewed with iOS home assistant app.

![image](https://user-images.githubusercontent.com/86141523/137419793-13186b97-6369-4a05-8b4c-59570678d296.png)

### Describe the behavior you expected

I expected the graphs to be shown in my local timezone as they have always been until today.

### Steps to reproduce the issue

1. opened several browsers on several machines and got the same result
2. opened the iOS app and got a different result

### What version of Home Assistant Core has the issue?

core-2021.10.4

### In which browser are you experiencing the issue with?

Version 80.0.3987.122 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

macOS 10.13.6 (17G14042)

**Comment by del13r** [comment]
I am on a Mac (Early 2011 MacBook Pro) which cannot upgrade any higher than macOS 10.13.6

The highest safari version that is allowed on macOS 10.13.6 is
Safari Version 13.1.2 (13609.3.5.1.5)
which was Released 15 July 2020

When I access home assistant using version 13.1.2 of safari, all the times are still shown incorrectly in UTC.
The only way to view home assistant properly on this old mac is to use chrome or firefox instead.

**Comment by terual** [comment]
I had the same issue on my Ubuntu system. Upgrading Firefox to 93.0 solved the issue.

Also I had the same issue on my iPad using the Homeassistant app. Upgrading iPadOS to 15 solved the issue.

**Comment by sbasmanov** [comment]
Hit this issue today as well. El Capitan, old iPad - nothing works. Not Safari, not FF. Only Chrome worked somehow.
May we have an option in config to override frontend time detection? Like I want to always see graphs in local time no matter where I am. That will solve all issues with old devices.

**Comment by del13r** [comment]
Bery good point.
I suppose the best way to phrase this issue is,
'Why are browser versions that were only released last year, unable to display graphs in the local timezone?'

**Comment by sbasmanov** [comment]
I think the problem is deeper and not only with last year browsers. Safari on El Capitan shows UTC, Firefox 78 (latest available for this OS) also shows UTC. Only old Chrome that asks me for update for few years, works as expected :)
I am currently in different TZ from my HA and when I open any sensor graph I see my current local time, not the time of HA (I'm on High Sierra, FF 93). So, imagine I'm on opposite side of the globe and I'm checking temperature sensor graph. Guess what I will see? Cold days and hot nights :) So, I have to do some math to understand, when that data was collected. Oh, wait, this is what we have computers for... I guess :)
So, getting TZ from browser and adjusting frontend may be was good idea for things like weather. But this is totally wrong for historical data. I think best way is to add TZ picker at account details (right after numbers/time format) so every user can select preferred TZ (or auto).
