### ISSUE TITLE
UI, TV and Security System.

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#10512]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

.

### Describe the behavior you expected

.

### Steps to reproduce the issue

.

### What version of Home Assistant Core has the issue?

2021.11.0

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![image](https://user-images.githubusercontent.com/42905545/140191092-08cc756f-745b-4094-ba63-70f1b004a43a.png)
 
I dont see controls button for android tv and samsung, and im open panel for security system i dont see arm night.
same problem on the mobile app HA.

**Comment by spacegaier** [comment]
The missing buttons most likely are due to you using a custom card that has not yet been updated to work withe the latest HA frontend.

Please post the entity state info of your alarm entity. The fronted decides which buttons to show based on the info the backend provides about the alarm integration's capabilities. So most likely the frontend behaves correctly and the integration is just not supporting or reporting it.
