### ISSUE TITLE
Cover More Info: Tilt stop displayed by fault

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#10883]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the more info dialog of all my covers (device class shutter) the tilt stop button and tilt position is displayed. I'm almost sure that < 2021.12 this was not the case. 

![image](https://user-images.githubusercontent.com/25910703/145722022-25321772-d181-4838-a2ad-3ffb773e6e3a.png)

I have the same issue with KNX covers and cover groups. 

### Describe the behavior you expected

Tilt stop button and tilt position header should not be displayed as the cover does not have tilts configured.

### Steps to reproduce the issue

1. Create cover without tilts
2. Create cover entity on dashboard
3. Click on cover entity

### What version of Home Assistant Core has the issue?

core-2021.12.0

### What was the last working version of Home Assistant Core?

core-2021.11

### In which browser are you experiencing the issue with?

Version 96.0.4664.93

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
- name: OG Bad Rollladen Nord
  move_long_address:
  stop_address: 
  position_address: 
  position_state_address: 
  travelling_time_down: 
  travelling_time_up:
  device_class: shutter
```

**Comment by spacegaier** [comment]
Can you please post the state from the HA dev tools of that entity, specifically I am looking for the `supported_features` value.

**Comment by KNXBroker** [comment]
Sure, these are the attributes

```
current_position: 0
device_class: shutter
friendly_name: OG Bad Rollladen Nord
supported_features: 79
assumed_state: true
```

**Comment by spacegaier** [comment]
The frontend behaves correctly here. Your cover reports "79" as its feature set, which means 64 + 8 + 4 + 2 + 1.

![image](https://user-images.githubusercontent.com/114137/150005286-4ef68792-13ac-43f8-8a2e-dfff7e0c709b.png)

Therefore the frontend has to render the stop tilt button (might not have been the case with versions < 2021.12 because I cleaned up the cover logic for that release via https://github.com/home-assistant/frontend/pull/10671). 

=> Please check with the integration that owns the cover why this `supported_feature` gets set.

**Comment by KNXBroker** [comment]
Thank you @spacegaier , I will report it in the core for KNX integration
