### ISSUE TITLE
Area card shows wrong temperature

### ISSUE THREAD

**Issue by royalheadwear** [home-assistant/frontend#10960]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Area Card does not show the correct temperature. The temperature should come from a Fritz!Dect 301. The termostate is configured to belong to the Area. The Thermostat Card shows the correct 21 °C from the AVM-Device but in the Area card a different temperature (no other sensor has this temperature value).
![grafik](https://user-images.githubusercontent.com/19154381/146606139-d6576741-adec-4c8e-96b4-2ca2dd0833fd.png)

![grafik](https://user-images.githubusercontent.com/19154381/146606083-10dd8ee0-6ff4-4383-85a6-a8bf4ecf004d.png)

### Describe the behavior you expected

The Area Card should show the temperature of the termostate that is inside of this area.

### Steps to reproduce the issue

1. Create a Area
2. Add a Fritz!Dect 301 termostate to it
3. Add a Area Card to any dashboard

### What version of Home Assistant Core has the issue?

core-2021.12.3

### In which browser are you experiencing the issue with?

Mozilla Firefox 95.0.1

### Which operating system are you using to run this browser?

Windows 10 Version 21H1

### Additional information

The same temperature is also shown in the Android App. That's why I think it has nothing to do with the used Browser or OS.

**Comment by a351must2** [comment]
Hopefully some more helpful information since I've seen the Area cards show the correct temp as well as incorrect temps:  

A friend of mine has 4 area cards with temps coming from zigbee devices using the Zigbee Home Automation integration that all show correctly.  

I have 9 Area cards with temps and none are ever correct.  Most of my temps are provided by DHT11 and AHT10 devices connected using the Tasmota integration and one temp comes from my thermostat using the Honeywell integration.  At any given time, the temp shown on the Area cards will be 5 to 10 degrees F off what the sensor is actually reporting.

**Comment by zsarnett** [comment]
If you have more than one temperature sensor of climate device in the area. It will show the average.

**Comment by royalheadwear** [comment]
I actually just have one sensor for each area. Is there a possibility to check where the other information seems to come from?

**Comment by a351must2** [comment]
> If you have more than one temperature sensor or climate device in the area. It will show the average.

In my case, all 9 areas with temps only have one temp sensor each...I've looked for trends like averaging values from the same device and other devices in the same area and nothing has matched up.  If it's an average, it is not obvious what other value is being used to make the average.  i.e. my Laundry room has one Tasmota AHT10 device and a Lutron light switch.  While Tasmota is reporting 60.3 degrees, the Area Card for the room shows 50.8 degrees.

**Comment by a351must2** [comment]
Ok ... I guess I didn't look hard enough at values that could be averaged.

The Area card is displaying the average of the Room Temp and the Dewpoint ... still seams buggy.  
I would bet in the case of the thermostat that it is averaging the Temp settings since the person that reported this bug shows 3 temp settings on his device.
