### ISSUE TITLE
Scene edition actually trigger scene

### ISSUE THREAD

**Issue by almooj** [home-assistant/frontend#11430]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

 on my home assistant instance, http://myhome-assistant.instance/config/scene/dashboard

when clicking on the edit icon (pencil) of one of my created scene, it trigger it as well as opening the edit interface

### Describe the behavior you expected

usually it should not trigger my scene but only opening the edition interface

### Steps to reproduce the issue

1.go in the config menu from the home assistant instance (lower left gear icon on the home page) 

2.click automations and scenes menu

3.switch to the scene "tab" to display your actually defines scenes

4.click on the pencil icon of the defined scene you want to edit

5. it trigger the scene and display the edition interface
...

### What version of Home Assistant Core has the issue?

core-2021.12.10

### What was the last working version of Home Assistant Core?

core-2021.12.10

### In which browser are you experiencing the issue with?

Mozilla Firefox 96.0.2 (64 bits)

### Which operating system are you using to run this browser?

windows 10

**Comment by spacegaier** [comment]
That is not a bug. The scene has to be triggered since otherwise when you edit it, it would basically overwrite it.

Imagine a scene with a single light that is set to turn on at 50% brightness when the scene is activated. If you now go to edit the scene, but the light is currently off and we would not activate the scene during editing, once you save the scene it would now have the light set to brightness 0% since it was off during the scene editing. So it would silently alter the scenes completely and that would then be a bug.

**Comment by almooj** [comment]
that make sense , thx for the explanation

**Comment by almooj** [comment]
this is clearly not a bug
