### ISSUE TITLE
2022.2.0b introduced cubic spline connections in history graphs

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#11492]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The 2022 February beta has introduced connecting data points with cubic splines. This has created very poor representation of the actual data, e.g.

![CHkQXNo](https://user-images.githubusercontent.com/10679300/151779503-156c78d5-d94c-44a2-8683-7dbe6915586a.png)

This seems to be the PR responsible: https://github.com/home-assistant/frontend/pull/11082

### Describe the behavior you expected

An accurate representation of data received without this artefact inducing interpolation.

Please consider reverting PR https://github.com/home-assistant/frontend/pull/11082

### Steps to reproduce the issue

1. Open a history graph for a sensor with a step change.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.2.0b3

### What was the last working version of Home Assistant Core?

core-2021.12.10

### In which browser are you experiencing the issue with?

Chrome, Firefox, Safari

### Which operating system are you using to run this browser?

Windows 10

**Comment by thomasloven** [comment]
I don't think #11082 is the culprit. It does not introduce the cubic interpolation, but changes how the space between two data points is filled.

What we had before 11082 is the red line in this figure, and what we have now is the green.
Without the cubic splines the green is more representative IMO, since I guess noone's interested in switching to a point graph...

![image](https://user-images.githubusercontent.com/1299821/151784839-3ddb6f77-4281-4e47-bd88-2f4fa7e175b8.png)

**Comment by tomlut** [comment]
We don't have the green now. We have the red. Look how the step change in my image above (between 01:30 and 0830) has been converted to sloped line instead of remaining at 0W.

**Comment by tomlut** [comment]
![151779503-156c78d5-d94c-44a2-8683-7dbe6915586a](https://user-images.githubusercontent.com/10679300/151787900-e0f5f591-8681-4fcf-af65-b447e5cd494c.png)

**Comment by thomasloven** [comment]
You are right, of course.

**Comment by emontnemery** [comment]
We should not revert #11082 as it fixes a bug.
What we could consider doing is perhaps to disable interpolation.

**Comment by trichromic-ab** [comment]
Hello,
I'm not a contributor and I'm only just getting to know Home Assistant so I may be in the wrong place here.
However I have noticed that since applying the 20220203.0 frontend update, my history graph lines are breaking up and I wondered if this is related to the change in interpolation.
This sensor and all my other temperature and humidity sensors exhibit this from about 01:55 on 04/02/2022 when I applied the update. Before that the lines are continuous as you can see in the screenshot example.

I didn't do any Core updates at the same time. I was still on 2022.2.0 until today and updating that to v2022.2.3 hasn't made any difference.

![image](https://user-images.githubusercontent.com/80370469/152837888-3ad23624-1965-47b5-9d07-9de6e5934b06.png)

**Comment by trichromic-ab** [comment]
Following my previous posting, I upgraded from Core v2022.2.0 to v2022.2.3 
My history charts from that point in time seem to be showing unbroken lines again.

![image](https://user-images.githubusercontent.com/80370469/152869509-59298880-0b22-48c2-bac1-25af791e30e8.png)
