### ISSUE TITLE
Error in the unit of measurement of atmospheric pressure

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#11552]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The entity weather.house presents in more info the atmospheric pressure measured in Pa. Shouldn't it be expressed in hPa?

### Describe the behavior you expected

hPa instead of Pa

### Steps to reproduce the issue

1. click on the weather.house card
2. look at the unit of measurement of atmospheric pressure on the more info tab that appears
3.
...

### What version of Home Assistant Core has the issue?

core-2022.2.0

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![Weather](https://user-images.githubusercontent.com/74879713/152598943-8b09d9e3-53b3-47ff-b048-a143afa5475e.png)

**Comment by WRoss7** [comment]
This is a persistent minor bug.

**Comment by emontnemery** [comment]
Which integration provides the pressure sensor?
Can you share a screenshot from the "states" developer tool for the pressure sensor?

**Comment by WRoss7** [comment]
@emontnemery isn't this integration?

![Immagine](https://user-images.githubusercontent.com/74879713/167949423-5e03fd7f-a4df-4004-82f1-f7d8edbec845.png)

Anyway:

![Immagine2](https://user-images.githubusercontent.com/74879713/167950002-e917836b-7dc6-4429-99da-049ec269640d.png)

**Comment by Tommatheussen** [comment]
This seems to be an issue with any weather platform (I use OpenWeatherMap for example). According to the developer docs, pressure should be return in `hPa` (https://developers.home-assistant.io/docs/core/entity/weather), which is the case for OpenWeatherMap (and I guess met.no as well), as can be seen in the code: https://github.com/home-assistant/core/blob/dev/homeassistant/components/openweathermap/weather.py#L85

The separate sensor that gets created by the OWM platform actually does show as hPa in the frontend, it just looks like the weather card doesn't show the correct unit.

**Comment by WRoss7** [comment]
@Tommatheussen 
Hi Tom sorry for the big delay in replying and thanks for the great detective work.
Unfortunately I don't know GitHub except to report bugs, besides I don't have any experience with Python and the other languages ​​used for HA.

**Comment by lnxsrt** [comment]
I'm also seeing this issue (displaying "psi" instead of "inHg") with the AccuWeather integration as well as a Template Weather provider (where I provide these values from sensors). I do remember both providers being correct when I initially set these up last year. So that ties in with the regression @Tommatheussen found.

**Comment by WRoss7** [comment]
@lnxsrt, with the work of Erik Montnemery (https://github.com/home-assistant/frontend/pull/12947) joined 2 days ago the bug should have been squashed.
We will see the result in the next release on July 6th 🤞

**Comment by lnxsrt** [comment]
Bug still exists for me on 2022.7.1.

**Comment by emontnemery** [comment]
The underlying fundamental problem was fixed in #12947, which is included in Home Assistant Core 2022.7.0 - weather integrations now specify what unit they use for atmospheric pressure.

@lnxsrt If you upgrade to that version, atmospheric pressure is no longer psi, it's inHg if you use imperial units and hPa if you use metric.
Please make sure your browser cache is cleared, or the UI may be outdated. You can try from within an "Incognito mode" browser window or similar.

If it still doesn't work, please open a new issue and ping me from it.

**Comment by emontnemery** [comment]
@lnxsrt thanks for the detailed explanation, that helped 👍

**Comment by lnxsrt** [comment]
This issue is fixed for me in 2022.7.5! Thanks!
