### ISSUE TITLE
Energy Dashboard Units Are Incorrect When Converted

### ISSUE THREAD

**Issue by kspearrin** [home-assistant/frontend#11775]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the energy dashboard converts a sensor to match the localization unit settings for HomeAssistant, the unit is not accurately shown on the energy graphs. It seems like HomeAssistant is doing the unit conversion, but maintains the original unit label on the UI. In my case, a gas meter MQTT sensor is collected in cubic meters, the dashboard converts it to cubic feet based on my localization settings, but the labels still show cubic meters.

More details reported here: https://community.home-assistant.io/t/gas-consumption-on-energy-dashboard-much-higher-than-expected/357029/4?u=kspearrin

### Describe the behavior you expected

The units should report as cubic feet, or no conversion should happen.

### Steps to reproduce the issue

1. Configure HomeAssistant for Imperial units. 
2. Configure a sensor to collect gas consumption in cubic meters. Example:
```
- platform: mqtt
  name: Gas Meter
  state_topic: "rtlamr/xxxxxxxxxx/state"
  device_class: gas
  state_class: total_increasing
  unit_of_measurement: "m³"
```

3. Add the gas sensor to the energy dashboard. See my sensor here that increased by 18 cubic meters over the hour:
![image](https://user-images.githubusercontent.com/1190944/155176179-47b6c173-221d-44a0-8c2a-9216637edd3f.png)

4. Observe the the graphs display values converted to cubic feet, but the labels still show cubic meters.

![image](https://user-images.githubusercontent.com/1190944/155176237-d890c8f8-0768-4123-8d4b-f17a4cb11646.png)

### What version of Home Assistant Core has the issue?

core-2022.2.9

### In which browser are you experiencing the issue with?

Chrome/98.0.4758.105

### Which operating system are you using to run this browser?

Windows 10

**Comment by ehendrix23** [comment]
I can confirm. My daily total right now is showing 16.5732 cubic meters but energy page is showing 566.8 cubic meters. If I convert to cubic feet then it pretty matches. 
Thus the numbers displayed are in cubic feet (baed on Imperial units) but the label still shows cub meters instead of cubic feet.

**Comment by kspearrin** [comment]
Still an issue.

**Comment by kspearrin** [comment]
Still an issue.

**Comment by nor500** [comment]
I am facing similar issue. I live in Europe sp the metric system in set in Home assistant. Gas usage shows around 10 times more then the actual true values. I dont make any conversions because the meter reading values are in m3 and also the summarized usage values are also in m3.

My settings for utility meter:

utility_meter:
    gas_usage_monthly:
       source: sensor.gas_meter
        cycle: monthly

**Comment by kspearrin** [comment]
This issue appears to be resolved now.
