### ISSUE TITLE
My user is an administrator and is not able to set advanced mode ( option is greyed out.)

### ISSUE THREAD

**Issue by jr3us** [home-assistant/frontend#12075]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when trying to add the ssh and web terminal addon, I found that being an administrator was not enough permissions and had to turn on advanced mode to let me add it.

My user jrh did have administrator permissions, but the option to turn on the advanced mode was greyed out for my user, preventing me from adding the addon.

I have been upgrading this home assistant instance since around version .55 or so. 

### Describe the behavior you expected

The selection for the advanced settings for the user should be available since the user is an administrator.

### Steps to reproduce the issue

1.
2.
3.
...

I dont know as I did create a new user with administrator permissions, and the new user did have the ability to select advanced.

### What version of Home Assistant Core has the issue?

2022.3.5

### What was the last working version of Home Assistant Core?

I don't know.

### In which browser are you experiencing the issue with?

Firefox current and Safari current

### Which operating system are you using to run this browser?

macos as well as linux

**Comment by spacegaier** [comment]
I had a very quick glance at the code, and the option can only be disabled, if some user data is missing in the frontend, probably because it could not get read from the backend.

Could you try it again and have the browser tools open. In the "Network" tab you will see the communication between frontend and backend. Towards the top of the entries that will appear, there should be one called "websocket" which will contain all the API calls between frontend and backend, specifically one named `frontend/get_user_data`. 

=> Can you spot that one?
=> Is there any error noted for it?

**Comment by jr3us** [comment]
I see 2 items for get_user_data as follows:

{"type":"frontend/get_user_data","key":"core","id":15}
{"type":"frontend/get_user_data","key":"language","id":16}

There were no other messages in the Response section in Firefox.

Regards

**Comment by jr3us** [comment]
I see 2 items for get_user_data as follows:

{"type":"frontend/get_user_data","key":"core","id":15}
{"type":"frontend/get_user_data","key":"language","id":16}

There were no other messages in the Response section in Firefox.

Regards
