### ISSUE TITLE
Timer Helper does not show correct time in the GUI

### ISSUE THREAD

**Issue by wjarka** [home-assistant/frontend#12587]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a timer with the duration set to 10 minutes and 15 seconds. The moment I start the timer - the history for it shows it started a minute ago and the time remaining (displayed in Entities Card in Lovelace) shows 9:02 minutes left.

The timer finishes at the right time and all the integrations / automations work correctly, but I can't reliably display the countdown.

### Describe the behavior you expected

I'd like to display the correct countdown of a timer in Entities card. 

### Steps to reproduce the issue

1. Create a new Timer helper through the GUI. Set duration to 10 minutes 15 seconds
2. Add a new card to Lovelace dashboard to present the timer. (Add Card -> By Entity -> Search for the newly created timer)
3. Start the timer
4. At least in my case - it shows 9:02 instead of 10:15
...

### What version of Home Assistant Core has the issue?

core-2022.5.0

### In which browser are you experiencing the issue with?

Brave 1.38.111 / Edge 101.0.1210.32

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
This is the timer entity
duration: '0:10:15'
editable: true
friendly_name: Time left in the game
finishes_at: '2022-05-04T20:24:54+00:00'
remaining: '0:10:15'
```

### Problem-relevant frontend configuration

```yaml
All created through GUI
```

### Javascript errors shown in your browser console/inspector

```txt
No errors.
```

**Comment by wjarka** [comment]
In my case, it was Windows Time Sync issue. The PC's clock got desync'd with the server time and that's where the issue originated from. 

May be a good idea not to use browser time to calculate it? 

I will leave this issue open just for you to consider this comment, but feel free to close it.

**Comment by RoepLuke** [comment]
I tried using the attribute "remaining" in an Entity-Attribute Card. The Attribute 'remaining' of a timer helper always stays at the initial time. Per my definition this should at least periodically decrease as the time is active, otherwise it would be a duplicate of the 'duration' attribute.
![image](https://user-images.githubusercontent.com/29387023/168172267-d9b41017-0bb1-4b46-a0d4-8b116b553d90.png)
![image](https://user-images.githubusercontent.com/29387023/168172380-909a85f3-f8e9-4a73-9a13-72161fba1525.png)
![image](https://user-images.githubusercontent.com/29387023/168173105-15a1be2a-c72f-4ab2-838b-5ad550789715.png)
`type: entity`
`entity: timer.gaeste_anwesend_timeout`
`name: Timer`
`unit: HH:MM:SS`
`state_color: true`
`attribute: remaining`

The Variant suggested by @wjarka in this issue works on my HA-Instance (2022.5.3 Container) but that's not what I want designwise: 
![image](https://user-images.githubusercontent.com/29387023/168172679-a6f17577-6a22-49f8-8c95-b6fdfb430449.png)
