### ISSUE TITLE
entity_picture with new logbook in 2022.06

### ISSUE THREAD

**Issue by chertvl** [home-assistant/frontend#12851]
### The problem

Not all domains show they entity_picture in new logbook (2022.06 update).
As I can see, binary_sensors is ok, but light, switch, media_player, input_boolean, input_boolean, sensor (maybe etc) - is shows icon instead of customized entity picture.
![image](https://user-images.githubusercontent.com/38353584/171459065-36aa2a82-a338-450c-85f4-c7bfbe1624f8.png)

### What version of Home Assistant Core has the issue?

2022.06

### What was the last working version of Home Assistant Core?

2022.05

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

logbook

**Comment by bdraco** [comment]
To archive that we likely need to not set overrideIcon here https://github.com/home-assistant/frontend/blob/dev/src/panels/logbook/ha-logbook-renderer.ts#L184 if there is a historic state and there is an `entity_picture` or `entity_picture_local`  in the attributes.

I'm not sure if we should do that though since thats always going to be the current entity_picture and not the historical one since we only store the historical icon and not the historical entity_picture.  I guess thats fine for domains that don't have a dynamic picture but the entity could have a dynamic picture for an on/off state if it wanted to so the icon may be more correct.

Its easy enough to change, but needs another opinion on what the best option is here.

**Comment by bdraco** [comment]
It looks like this will only happen when there is both a picture and an icon set.  This one is hard to know how to proceed.  While the frontend usually prefers the picture over the icon, with the available data the icon is guaranteed to be historically accurate but the picture is not.

**Comment by chertvl** [comment]
> It looks like this will only happen when there is both a picture and an icon set.

Yes, you are right, only when both are set.

**Comment by chertvl** [comment]
I deleted all my icon: in customize entities of configuration. Now I have default light.*, switch.* icons at interface of HomeAssistant WearOS companion (thats not good), but I see entity picture in logbook for this objects (but not all).

I still cant do same for input_select, input_boolean objects,  switches with device_class: plug for example, because Home Assistant Core creates they own icon: attribute, wich I cant remove. 

Now I dont have any way to display entity_picture for this entities in logbook. 
Any improvements please?

**Comment by bdraco** [comment]
I'm leaning twords leaving this as-is as I think the new behavior is more correct since we don't have the historical picture and loading additional images is going to make issues like https://github.com/home-assistant/frontend/issues/7805 worse.

I'll ask for a second opinion in case another member disagrees and things we should change it back.

**Comment by ildar170975** [comment]
> we don't have the historical picture

In my setup for template sensors all `entity_picture` attributes are **static** (does not depend on any conditions).
So I do not know how it worked earlier - whether Logbook displayed a historical picture or it was always the current one.

I guess that since there is a possibility to define the `entity_picture` dynamically for template sensors, it is expected that these attributes (as well as any other user-defined attributes ) are stored in DB.
Yes, this will cause an additional DB usage. But that will be a cost of user's requirement "I need a dynamic entity_picture".

I am not a DB expert. But I think there are methods to minimize a DB usage like "do not keep 10000 copies of the same image, keep only changed versions".

**Comment by bdraco** [comment]
It has always been the current one. We have never displayed the historical one since there hasn't ever been a way to get it from the backend and most of the time its not stored.

**Comment by bdraco** [comment]
The options here are

1. Leave it as-is and display the historical icon since we have that
 - This is always historically correct 
2. Change it back to display the current image (we do not have the historical image)
  - This is sometimes historically correct if it happened to be the same
3. Implement storing the historical image url in the database and provide an api to do so
 - This will sometimes show a broken image since the url may no longer point to a valid image. For cameras this will always be broken

**Comment by bdraco** [comment]
Another option would be to only use the current picture for live rows and use the historical icon (as it is currently implemented) for historical rows.

However as soon as you reload the page its going to switch back to the icon so that might be confusing.

**Comment by ildar170975** [comment]
I got your point.
I would prefer the current implementation then:
- `icon` is defined - show historical icon
- no `icon` is defined, `entity_picture` is defined - show the current picture.

Currently my ONLY template sensor with a **static** `entity_picture` has no defined `icon` (this is a person-related sensor).
So the logbook shows ALL rows with that `entity_picture` (person's picture).
For me it is 100% ok.
Personally me not asking to display different images - since I do not have them))).

**Comment by chertvl** [comment]
> 3\. Change it back to display the current image (we do not have the historical image)
> 
> * This is sometimes historically correct if it happened to be the same


> I don't like 2 since its not inline with how the rest of logbook works.

This variant exactly what are we used to before 2022.06.x. I vote for this.
- If entity_picture is defined for entity at this moment - show entity_picture for all historical stats (for new and earlier) in all logbooks (card, device-page, /logbook, etc). Dont show icon even if this attribute is defined. Show blank field if image url is wrong.
- If only icon is defined, show historical correct icon from db.
- If no one is specified in attributes, show default entity icon (device class, domain).

In this case we dont need to:
- Cache images and they urls
- Display state-variable images

People whos uses entity_picture for they entities already know:
- Entity picture is always the same
- Image is state indepentend, solid

Only one way to make state-dependent entity_picture its Template Sensor with many templated image urls. But again we dont need cache it or record in db, just show current one for all records. Its ok.

Maybe we can make some boolean for yaml setting of logbook to prefer priority for entity_picture? Wich wll be disabled default

**Comment by ildar170975** [comment]
bump

**Comment by chertvl** [comment]
> @chertvl why did you close the issue?

Sorry, no second opinion for three months, no one cares. I have already come to terms with the new rules.
