### ISSUE TITLE
Add Utility Meter: Supported Tariffs need to contain a value

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#12938]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Adding a Utility Meter as a helper requires the user to enter a supported tariff. The help text below the input field on the other hand states, that it should be left black if only a single tariff is needed:

![Screenshot_20220612_192421-1](https://user-images.githubusercontent.com/614929/173245488-83ec5f0d-cb8a-43d3-bb5d-923ba8a6aa93.png)

### Describe the behavior you expected

The input field should be optional.

### Steps to reproduce the issue

1. Go to helper page
2. Click on add
3. Select Utility Meter
4. Fill in all required fields and leave Supported Tariffs empty
5. Be reminded that Supported Tariffs need to contain a value

### What version of Home Assistant Core has the issue?

2022.6.4

### In which browser are you experiencing the issue with?

Firefox 101.0.1 / Chromium Version 102.0.5005.61 (Official Build, ungoogled-chromium)

### Which operating system are you using to run this browser?

Arch Linux x86_64

**Comment by jdelker** [comment]
This issue is still present in Home Assistant 2022.9.3

**Comment by jdelker** [comment]
Correction:
With 2022.9.3 the UI form **does** accept an empty "Supported Tariffs" field. However, the field is still marked as required (*).
In my case, it was the field "Meter reset cycle", which was causing the error. It is not marked as required (no *), but must be filled with a selection (e.g. "No cycle").

**Comment by karwosts** [comment]
The tariffs field is marked as required because it is defined as required in the core integration:

https://github.com/home-assistant/core/blob/dev/homeassistant/components/utility_meter/config_flow.py#L93

I do see meter reset cycle currently visually marked as required:

![image](https://github.com/home-assistant/frontend/assets/32912880/4c52ba8e-f80c-4cc6-beeb-6fb450ac3d5f)


If you want that tariffs field to not be visually marked as required, you need an issue/PR in home-assistant/core repository to remove the required property on that field in the config flow, there's nothing can be done in the frontend. 

Otherwise I don't think there's anything more that can be done here and would suggest this to be closed.
