### ISSUE TITLE
Thermostat graph doesnt update correctly

### ISSUE THREAD

**Issue by Viss** [home-assistant/frontend#13214]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If left alone, the temperature graph looks like this:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1756255/179570908-73cd32ee-87f5-4d5c-9634-50a6bafc6a6b.png">

That solid blue area would indicate the AC has been running sold for close to 12 hours. That's not right

### Describe the behavior you expected

if I hit refresh, the graph updates and looks correct:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1756255/179571064-2ef5a33c-67e6-455d-9e88-e0b72f4f9dc4.png">

The data lives in the backend correctly, but for some reason the front end needs a force-refresh to display it correctly

### Steps to reproduce the issue

1. Create a thermostat entity card
2. set the refresh interval to 1
3. run your air conditioner
4. wait

### What version of Home Assistant Core has the issue?

core-2022.7.5

### In which browser are you experiencing the issue with?

chrome, firefox, and the android app - all the newest available as of July 18th, 2022

### Which operating system are you using to run this browser?

It's everywhere, osx, linux, android

### Additional information

It looks like the issue is just that the front end doesnt make a query to the backend to get the data when the refresh interval fires. Or if it does, that data isnt being rendered correctly

**Comment by Viss** [comment]
this issue is still not resolved, despite the frequency of the recent home assistant updates. you still have to force-refresh for the chart to update

**Comment by coutadeurf** [comment]
Hi,

Also had this issue : 
![image](https://user-images.githubusercontent.com/40169798/203736965-9dd3f805-1153-44de-8f62-7e3b379cdc2f.png)
but the history is correct:
![image](https://user-images.githubusercontent.com/40169798/203737101-a81599c3-b8ae-4835-a7b0-4dc876136181.png)
But after cleaning the cache and reconnecting to my instance, it worked correctly

**Comment by Viss** [comment]
which cache?

**Comment by coutadeurf** [comment]
Chrome's one. 
I dind't have the issue with the Android app

**Comment by Stefano0042** [comment]
Cache purging is not solving on both Edge and Safari iOS browsers. I did a try again after few weeks ago.

**Comment by Viss** [comment]
Same. browser caches do nothing to solve this problem, only a hard refresh of the tab home assistant is in

**Comment by Viss** [comment]
Just an update - despite all of the recent upates, this bug still persists. Users have to force-refresh to make this graph update, it doesnt update on its own.

**Comment by karwosts** [comment]
I know why this happens. 

The history graph chart is coded to auto refetch history data anytime any of the charted entites' state changes. 

The problem with a climate entity is that it's "state" is not what is interesting for graphing, it is rarely ever changed, since it is just the mode of the thermostat, like "heat" or "cool", or "off". All the interesting things happening with climate are attributes of the climate entity, but the history chart is not watching for attributes to change, only the state. So it doesn't refetch the history when it redraws, it thinks "nothing has changed".  Normally this works because it is only graphing states, but the climate entity is a special case. 

One workaround you could do here is manually add a temperature sensor to the history chart, in addition to the climate entity. This means everytime the temperature changes, it will redraw the full graph, including the climate entity and all of its attribute states. 

E.g. here are two identical history charts, the upper one with just the climate entity, and the bottom one including a climate entity and a temperature sensor. I refreshed the page around 1:41 and let it sit. The bottom chart redraws when the temperature changes, the top one never redraws. 

![image](https://user-images.githubusercontent.com/32912880/207454057-5b4d6538-c400-4557-b614-562968ba592b.png)

**Comment by lubosjerabek** [comment]
I am having the same issue. So annoying, that explains why I observe this more in the companion app rather than on desktop.

**Comment by Viss** [comment]
so i tested this - it looks like @karwosts analysis is right - to force this to be fixed, you basically have to edit the card and add an entity in addition to the thermostat, like its temperature on its own, and it'll update as you'd expect.

Problem then is there are two entries for the same value, and it eats vertical space in the dashboard needlessly. It would be pretty neat if there was a better way to do this.

**Comment by bdraco** [comment]
fixed in 2022.2.x via #15112
