### ISSUE TITLE
Unable to select targets for service: Z-Wave: Set a Z-Wave device configuration parameter

### ISSUE THREAD

**Issue by DPetersen257** [home-assistant/frontend#13365]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Targets" section when using service "Z-Wave: Set a Z-Wave device configuration parameter" is blank and cannot be updated. I've confirmed with a friend that they're having the same issue

Previously, this was where we could select a device to be the target of the service call.
![blank targets](https://user-images.githubusercontent.com/7536643/183762087-83a5aca8-b392-4c1f-8626-fe84a850645b.png)
I can see the ID's in place if I edit via YAML, it seems that just the GUI editor is broken at the moment

![yaml](https://user-images.githubusercontent.com/7536643/183762088-b8287cfe-3a54-4e06-813e-0740f20ac628.png)
.

### Describe the behavior you expected

Previously, in the GUI editor - targets section of the service call, we were able to choose devices.

### Steps to reproduce the issue

1. Developer Tools-> Services OR Create/edit a script
2. Services
3. Select "Z-Wave: Set a Z-Wave device configuration parameter"
4. Observe empty targets sectio
![blank targets](https://user-images.githubusercontent.com/7536643/183762416-45e9bb35-7594-4bf9-928e-02fdb81a7794.png)
n

### What version of Home Assistant Core has the issue?

2022.8.2

### What was the last working version of Home Assistant Core?

Unsure exact version, but somewhere between 2022.7.7 and 2022.8.2

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.79

### Which operating system are you using to run this browser?

Windows 10 Pro 21H1

**Comment by Petro31** [comment]
This is affecting all zwave js service calls.  Not just set params.

**Comment by DPetersen257** [comment]
https://github.com/home-assistant/frontend/issues/13332#issuecomment-1214306424

"fixed in https://github.com/home-assistant/frontend/pull/13380 which should be available in one of the next (path) releases which includes a new build of the frontend."

**Comment by almighty059** [comment]
@Petro31 @DPetersen257 I have a similar but slightly different issue and wanted to check to see if it's related before I open a New Issue. 

Instead of using "Call Service" and choosing "Z-Wave: Set a Z-Wave device configuration parameter" I went the other route and in my automation, I choose a "Device" and the "Action" of "Set value of config parameter".

I am attempting to change the parameter of a Zooz ZEN Z-Wave switch which controls the LED Indicator Color for one of its buttons. On the UI the choices for the parameter's values are given as text (white, red, green, and blue). If I select blue, red, or green everything works however if I select white then I get an invalid data error when I try to save the automation. 

If I have white selected on the UI and switch to YAML it shows no Value however if I choose a different color on the UI and switch to YAML the Value shows correctly. The value in YAML is represented as a numeric value (0, 1, 2, and 3) and if I choose the numeric value for white (which is 0) and enter that as the Value in YAML and switch back to the UI then white is selected and I can save the automation and it works fine. This happens the same way when doing it in a script.

See below in the GIF.


![ezgif-1-677dae9d5d](https://user-images.githubusercontent.com/63380298/185716388-f671beca-5aea-4dc8-b665-68dfbc050b9e.gif)

**Comment by DPetersen257** [comment]
@almighty059 I do not believe that's the same issue - The above issue is specifically around not being able to set a target for integrations
