### ISSUE TITLE
Hassio supervisor page for dedicated restart of supervisor/core/host is missing in new version

### ISSUE THREAD

**Issue by tilman** [home-assistant/frontend#13516]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Supervisor page for dedicated restart of supervisor/core/host is missing in new version

### Describe the behavior you expected

Get back the old page or at least the same functionality. Right now it is not possible to do an restart from just the supervisor or just HA core.

### Steps to reproduce the issue

1. upgrade
2. can't find old page

### What version of Home Assistant Core has the issue?

2022.8

**Comment by matthiasdebaat** [comment]
In [2022.5](https://www.home-assistant.io/blog/2022/05/04/release-20225/) we've streamlined the settings menu. Restart Core is in Settings > System > Restart (top right). Reboot and shutdown host in Settings > System > Host > Top right overflow menu. Restart Supervisor has been removed, since there shouldn't be a purpose to do this.
