### ISSUE TITLE
Moon phase is shown with internal value in sensor state history

### ISSUE THREAD

**Issue by mback2k** [home-assistant/frontend#13558]
### The problem

The moon sensor state in the UI does not use "friendly" or translated values, instead the internal value is shown, e.g.:
![image](https://user-images.githubusercontent.com/231943/187994905-c260fb83-4c69-4b59-9186-70bbefa718d3.png)
![image](https://user-images.githubusercontent.com/231943/187994973-137b98fa-4da1-4149-988d-f80f8961d7a0.png)

### What version of Home Assistant Core has the issue?

2022.8.7

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Moon

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/moon

**Comment by silamon** [comment]
The localization seems to be structured otherwise for these entities (including moon for example), it needs the device_class to show the correct translation: 
https://github.com/home-assistant/frontend/blob/d3015c362d3952cc0a94dfc146114678ddabe54c/src/common/entity/compute_state_display.ts#L184-L193
When you fetch a state display using the entity current state, the attributes like the `device_class` are included. When you fetch a state display using a entity history state, the common attributes are not longer included.

**Comment by piitaya** [comment]
Fixed in `2023.1`
![CleanShot 2023-01-11 at 11 15 37](https://user-images.githubusercontent.com/5878303/211779424-2d9c664c-e84c-4577-bd05-03226bad3531.png)
