### ISSUE TITLE
z-wave thermostat temperature control gone

### ISSUE THREAD

**Issue by Theflxkid** [home-assistant/frontend#13649]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since upgrading to 2022.9.0 now instead of my z-wave thermostat control not updating the UI after I set it, the controls to set the temperature are gone entirely. I can set the cool mode and fan mode, but the actual temp setting is nowhere to be found. I can still set it programmatically via node red just fine, but the Lovelace UI doesn't have the up/down temp control anymore. Argh!

### Describe the behavior you expected

There should be controls to actually set the temp of my z-wave thermostat (using z-wave js latest version as well).

### Steps to reproduce the issue

1. Go to z-wave js based thermostat
2. Tap/click on it to open controls
3. No controls there to set the temp (although the temp setting and current temp shows).
...

### What version of Home Assistant Core has the issue?

2022.9.0

### What was the last working version of Home Assistant Core?

2022.8.7

### In which browser are you experiencing the issue with?

the HA app and safari & chrome

### Which operating system are you using to run this browser?

MacOS 12.5.1

<img width="576" alt="image" src="https://user-images.githubusercontent.com/112534509/188963692-3951f8d8-ff0f-496c-a716-4a64133568f4.png">

_No response_

**Comment by grischard** [comment]
I am seeing this with zigbee thermostats too. An imperfect workaround is to use a `thermostat` card.

**Comment by Theflxkid** [comment]
> I am seeing this with zigbee thermostats too. An imperfect workaround is to use a `thermostat` card.

@grischard Thanx for this workaround! Better than nothing. TBH I hadn’t even noticed there was a thermostat card.

**Comment by ianmcorvidae** [comment]
Not a home-assistant contributor, just doing some code spelunking: I believe this may be happening due to https://github.com/home-assistant/frontend/pull/13638

That change makes it so only one of `CLIMATE_SUPPORT_TARGET_TEMPERATURE_RANGE` or `CLIMATE_SUPPORT_TARGET_TEMPERATURE` can be displayed, looks like, but (for zwave), in https://github.com/home-assistant/core/blob/5c234a3504fd0d399c63b045dbe86fbe2d26f292/homeassistant/components/zwave_js/climate.py#L195-L199 it appears that zwave sets both of those support values if heat-cool mode is available at all (even if it's not currently selected, looks like). So, when a z-wave thermostat is set to a mode that needs only one value, the picker is not displayed because `CLIMATE_SUPPORT_TARGET_TEMPERATURE_RANGE` is on, but the target_temp_high/low values will be null or undefined since it's not currently set to heat-cool mode.

I don't know if the correct fix here is to change the zwave (and zigbee, from what grischard is saying) integrations to not set those values when the mode is not currently set to heat-cool mode somehow (though it appears from the code I linked that these values aren't intended to be changed after the integration sets things up), or if the frontend change needs amendment/reversion.

It appears that there is a comment on that pull request pointing out a similar (possibly identical) issue with some other thermostats due to the same change, as well.

**Comment by ianmcorvidae** [comment]
Just for fun I checked, and it appears that if I set my thermostat to heat-cool mode, the temperature settings come back, because the conditionals in 13638 only turn off the single input when the range is available and don't turn off the range input when the single input is available. So I'm even more convinced this is a result of that change.

**Comment by ingrove** [comment]
I'm seeing this as well on my Honeywell thermostats using the Honeywell Total Connect Comfort integration.  Unfortunately, these thermostats do not have a heat-cool mode so the temperature settings control is not available.

**Comment by ianmcorvidae** [comment]
@ingrove it looks like that integration always sets itself to support the `TARGET_TEMPERATURE_RANGE` regardless of what's available on the actual thermostat, so looks like you're right and the controls won't show up for you until this is fixed: https://github.com/home-assistant/core/blob/ec53241/homeassistant/components/honeywell/climate.py#L117-L121

Thanks for providing another example of this!

**Comment by fenichelar** [comment]
@elupus The change that was reverted undid the fix for this issue: https://github.com/home-assistant/frontend/issues/13450.

**Comment by fenichelar** [comment]
@Theflxkid I also have a Honeywell T6 Pro but am seeing a different issue where too many temperature controls are shown: https://github.com/home-assistant/frontend/issues/13450. I am not sure why we are seeing different behavior.

I am using the Z-Wave JS integration with ZWave2MQTT's WS server. Are you using ZWave2MQTT? If yes, are you using MQTT or WS? If no, what are you using?

My T6 Pro is using firmware 1.3, what is yours using?

**Comment by elupus** [comment]
Yes.

**Comment by elupus** [comment]
This must be fixed in core. Z-Wave should not provide both sets of ranges.
