### ISSUE TITLE
Automation not saving the tag name in the trigger

### ISSUE THREAD

**Issue by raidnet-ms** [home-assistant/frontend#13785]
### The problem

I'm tring to create an automation with a label as a trigger. Unfortunately the automation is not saving the label name (after saving the field result empty)

### What version of Home Assistant Core has the issue?

core-2022.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

automation

**Comment by frenck** [comment]
I cannot reproduce this on 2022.9.
I'm either reproducing it incorrectly or the bug is fixed?

![CleanShot 2022-09-17 at 10 43 08](https://user-images.githubusercontent.com/195327/190848433-d20ed2c7-5609-42c5-b45f-e129a645b3d8.gif)

Could you check and, in case not fixed, provide step by step instruction on how to fix the issue?

Thanks! 👍 

../Frenck

**Comment by raidnet-ms** [comment]
Hi Frenck!
Probably this has been solved with latest release!

Thank you!

**Comment by raidnet-ms** [comment]
Changes on HA 2022.9 has solved this issue.
