### ISSUE TITLE
Statistics Graph card: time span differs for "5 minute" & "hour"

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13796]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Create a new card, select "sensor.processor_use" entity (System monitor integration).
After some time (a month in my case) open the card again and change the "period" option:

![Untitled Project11111](https://user-images.githubusercontent.com/71872483/190871699-cc10c6c8-a39c-4510-9f7c-8f98ee9046de.gif)

I realized this issue accidentally.
First I created a card for with "5minutes" option; recently I realized that time span became about 10 days...

### Describe the behavior you expected

Time span does not depend on the "period" option.

### Steps to reproduce the issue

Described above

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127

**Comment by jetpacktuxedo** [comment]
I don't know how to solve this, but I at least know _why_ it happens which may help you dig further:

In [statistics.py](https://github.com/home-assistant/core/blob/7c448416e1667427491ff55d3389a4c049a08106/homeassistant/components/recorder/statistics.py#L1123-L1131) there is a block that pulls from "short term" statistics rather than pulling from the normal statistics data. I assume the "short term" statistics are more granular but not stored as long, while the "long term" statistics are less granular but stored longer. 

If you limit "days to show" to like 5 days or something then you may not see this time range jump.

**Comment by ildar170975** [comment]
> If you limit "days to show" to like 5 days or something then you may not see this time range jump.

Probably yes, but the main reason of using "statistics graph card" & `state_class: measurement` is having a graph for a LONG PERIOD.
According to your  investigation, this "short term statistics" is just a bit better than the usual "non-statistical" data.

**Comment by ildar170975** [comment]
Starting from 2022.10 - statistics with `period: 5minutes` is displayed for 7 days.
Earlier it was 10 days.
Btw, my Recorder's setting is `purge_keep_days: 10`.

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Seems that "5minute" statistics is a part of data which exists with a "purge interval".
This fact makes this statistics "short-term".

**Comment by ildar170975** [comment]
up
Docs definitely should be updated to reflect a difference between 5minute & hour

**Comment by ildar170975** [comment]
up

**Comment by karwosts** [comment]
What fix are you looking for here?

5-minute statistics are kept in a separate short_term_statistics table and are regularly purged. The card can't show 30 days of them because they don't exist. 

If you want a documentation update, please go to home-assistant.io and click the "provide feedback" link, that will open an issue in the documentation repo. But I don't think there's any change to be made here?

**Comment by ildar170975** [comment]
@karwosts 
With this issue I have 2 goals:
1. Get a confirmation from Dev that "5minute" statistics is purged like a "normal" history (i.e. kept within `purge_keep_days` interval). I asked this question several times in Community & did not get any answer, only answers like "yes, it seems to be purged" from users (not Devs).
2. Specify explicitly in Docs ([here](https://data.home-assistant.io/docs/statistics/), for instance) that "5minute" statistics is kept within `purge_keep_days` interval. Currently many users believe that LTS is kept forever & get surprised when "5minute" data are only shown for a short period.

Check [here](https://data.home-assistant.io/docs/statistics/):
![изображение](https://github.com/home-assistant/frontend/assets/71872483/a1092aaa-6e20-46b1-84d6-e6719770a1b9)

As a result of your answer:
-- I suggest to close THIS issue;
-- and propose necessary changes for [this](https://data.home-assistant.io/docs/statistics/) page.

**Comment by karwosts** [comment]
I'm not an expert on this area, but looking at the core code, the short term statistics do look like they are purged at the same time as the states table, with the same purge_before date based on keep_days. 

Really this is more of a backend question.

If you would like to request an update to that documentation page, please open an issue ticket here:

https://github.com/home-assistant/data.home-assistant/issues/new

**Comment by ildar170975** [comment]
For the record - here are good corrections in Docs, now Docs became more consistent: https://github.com/home-assistant/data.home-assistant/pull/284
