### ISSUE TITLE
The History integration is no longer persistent

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#13792]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The History integration is no longer persistent after its graphical makeup: for example, if I view an entity on one browser, I don't see it on other browsers or even in the companion app.
Also, the Registry no longer stores everything I include, as it did before.
Is this an intentional choice?
The guide regarding integration has never been updated!

### Describe the behavior you expected

If I view an entity on one browser, I expect to find it on the other browsers as well as in the companion application. As was the case before.
I would also expect Registry to store what I include in it.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.4

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
This  page (https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/history.markdown) still has info about settings - which seem to be ignored now.

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
@WRoss7 
Seem that the situation here a bit complex.
Here is how I see it:

1. Earlier the `history` integration allowed users to define a subset from _recorded_ entities. Then graphs for this subset are displayed on History page. If you select manually some entity from a picker - then a graph for only THIS entity is displayed. (if I remember this correctly)
2. Docs described this functionality (conformed it).
3. Some time ago the History page was rewritten: user can select one/several entities, then graphs for the selected entities are shown. And if I am not mistaken - the last selected entities are memorized, you will see them even after HA reboot. Also, this selection is reset when a browser's cache is cleared (if I am not mistaken).
4. But Docs still were not changed.
5. Then this issue was created and some other similar (I only know about this - https://github.com/home-assistant/core/issues/74956).
6. Some time ago Docs were corrected - all old description was deleted.
7. The 2nd mentioned issue was closed then.

So, the current status is:
-- History page is as described in pt. 3;
-- Docs do conform this functionality;
-- users who needed the old functionality now have to use the new one (which in some aspects is better, in other aspects - worse).

Means, the current implementation became NORMAL, and prolonging this issue became useless(((.
Imho the only possible option now is creating a FR for adding old features to the current implementation (to have benefits of each way).

**Comment by WRoss7** [comment]
@ildar170975
Thank you for the comprehensive response of which I agree on every point and which brought me to the knowledge of [this complete replacement of History.](https://github.com/alexarch21/history-explorer-card)
Thanks again
