### ISSUE TITLE
Door sensor TS0203 - ok in phoscon but not update in HA

### ISSUE THREAD

**Issue by groovy-ka** [home-assistant/frontend#14054]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,
I have a problem with my TS0203 door sensor.
Before, all was ok, but recently, i have noticed that phoscon doesn’t send state to HA.
All is ok in phoscon app, when i open, the state is on, when i close, the state is off immediately.
I also have lights that work good in HA.
It is like phoscon won’t communicate whit HA.
Sometimes, when i refresh deconz and open a door, that work on time, and stop after.
Have you an idea ?
Ps : im french sorry for my bad english

### Describe the behavior you expected

The deconz add-on should send sensor state to HA when an event is fired.

### Steps to reproduce the issue

1. Restart HA
2. Refresh Deconz
3. Open door
4. State is immediately open in deconz/phoscon app
5. Sometimes, at first time, new state is sended to HA
6. Close the door
7. State is immediately close in deconz/phoscon app but nothing happen in HA

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.1 Supervisor 2022.09.1 Operating System 9.0 Interface utilisateur : 20221006.0 - latest

**Comment by Quentame** [comment]
Hi !
You are on the wrong repo, please close this issue and create a new one on home-assistant/core.
This repo concerns frontend problems, your issue is a backend problem.
Thanks 😊

-------

Salut !
Tu es dans le mauvais repo, ferme cet issue et crée en une nouvelle dans home-assistant/core.
Ce repo concerne les problèmes de frontend (design/affichage), ton problème concerne le backend ("intelligence"/connectivité/traitements/automatismes).
Merci 😉
