### ISSUE TITLE
Can't add Gas Consumption with device_class energy 

### ISSUE THREAD

**Issue by dklemm** [home-assistant/frontend#14292]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I can't select a this entity when trying add gas consumption 

state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:fire
friendly_name: Gas Consumption (Year)

I think it was caused by this change https://github.com/home-assistant/frontend/pull/13968

### Describe the behavior you expected

Can select the sensor

### Steps to reproduce the issue

1. Add energy sensor
2. Select energy sensor from list
3.
...

### What version of Home Assistant Core has the issue?

2022-11

**Comment by dklemm** [comment]
Correction to the above, I think this was cause by the addition of water.  

https://github.com/home-assistant/frontend/blob/c810c67a539f16f250d30f755832ebd9ad990707/src/panels/config/energy/dialogs/dialog-energy-gas-settings.ts#L110

`include-device-class="gas"` should be `.include-device-class=${[ "gas", "energy" ]}`

**Comment by purcell-lab** [comment]
@emontnemery @bramkragten would you be able to have a look at this? A few of us are having some challenges with the gas dashboard after the release of 2022.11

**Comment by Rothammel** [comment]
+1

**Comment by glitter-ball** [comment]
+1 me too.

I had gas working with device_class = energy and unit = kWh. Now it's broken. Anything set up like this isn't available as a gas source in Energy Dashboard since I upgraded to 2022.11. Please fix!

**Comment by amitlalani** [comment]
Having the same issue here

**Comment by purcell-lab** [comment]
> Correction to the above, I think this was cause by the addition of water.
> 
> https://github.com/home-assistant/frontend/blob/c810c67a539f16f250d30f755832ebd9ad990707/src/panels/config/energy/dialogs/dialog-energy-gas-settings.ts#L110
> 
> `include-device-class="gas"` should be `.include-device-class=${[ "gas", "energy" ]}`

Have you been able to test that this is the fix?

Can you submit a PR to rectify?

**Comment by Jordan87** [comment]
Same issue here, I have addad those sensor from last few months and they are working but if i remove them from energy tab i cant add them again.
![image](https://user-images.githubusercontent.com/10414918/202840977-7d2eba8e-e4e8-485c-9f33-8ed6311f2603.png)
And what's funny, on this list for gas consumption most or all of visible sensors are no longer in HA, water, electricity and solar panel lists are correct.

**Comment by TomHBP** [comment]
I am also experiencing this issue. Is there a roadmap for when it will be resolved?

**Comment by dklemm** [comment]
I'll try to look at it later, I was hoping it would have been picked up by the dev that caused the issue by now as it seems like such a quick fix.  I don't have a Dev env setup so can't promise I will resolve.

**Comment by mobiledude** [comment]
> I'll try to look at it later, I was hoping it would have been picked up by the dev that caused the issue by now as it seems like such a quick fix. I don't have a Dev env setup so can't promise I will resolve.

That would be great! considering this has been in the Nov release from the start on. Would be great to see some progress on this. Much appreciated!

**Comment by purcell-lab** [comment]
This issue appears to be fixed in the 2022.12 beta release.

**Comment by dklemm** [comment]
https://github.com/home-assistant/frontend/pull/14448/files

**Comment by purcell-lab** [comment]
I reported this closed in December, but there doesn't seem to be anyone around to close this issues.

**Comment by dklemm** [comment]
closed, sorry I didn't see this before

**Comment by ccristal** [comment]
I still have this issue. 
<img width="351" alt="image" src="https://github.com/home-assistant/frontend/assets/5416417/23624482-52c1-4ba9-94f7-fb765db8245b">
Home Assistant 2023.5.2

**Comment by igorsantos07** [comment]
Currently at 2023.6.1, HA only states the gas units when trying to add a gas source - what... makes sense, I guess?

![image](https://github.com/home-assistant/frontend/assets/532299/64a3e332-0764-4a24-9f17-9461a689ca88)

Do people really measure gas consumption in energy units in other countries, or are they all just trying to [hack the Energy Dashboard](https://community.home-assistant.io/t/energy-cost-for-the-individual-devices/334932/50?u=igorsantos07)?

**Comment by Jordan87** [comment]
In Poland it's calculated to kWh (Viessmann entity and billing)

**Comment by igorsantos07** [comment]
Amazing, doesn't make much sense to me but if it works that way, it works that way! I thought it was just people trying to hack out the Energy dashboard.

I guess the inclusion of energy sensors got reverted by someone else who also didn't know it was possible to sell gas in energy units. Any chance @bramkragten could help again?

**Comment by Spottycat** [comment]
Problem still exists in Version 2023.10.1.

<img width="406" alt="image" src="https://github.com/home-assistant/frontend/assets/1735055/d5e1f4a5-08eb-4ca2-b243-deb978c15e37">

There are varying explanations depending on what dialogue you open. In the "add gas source"-dialogue kWh is still listed as possible unit for the gas source. It even explains that you cannot add both "volumetric" and "energy based" sources together.. which makes sense of course.

It would be great if it would be possible again to use kWh as a unit for the gas consumption.. as m3 is not as practical.. if you get billed in kWh ;)

@igorsantos07 I find it interesting that you think that way. For me it doesn't make sense to bill based on volume of gas.. because the volume itself doesn't define how much energy is within it. So billing based on volume makes no sense at all.. as the energy contained in it varies. So we use the caloric value of the gas to base the bill on.. and the quality of the gas (2 numbers) to calculate how much you'll have to pay.

Basing the bill on sheer volume alone means you can be ripped off easily if the amount of energy in the gas changes based on air pressure and temperature of the gas and the are around it. So you will only get a fair price for gas if you get billed on energy.. and not volume.

**Comment by purcell-lab** [comment]
I'm running 2023.10 and that version allows me to add  consumption sensors in kWh. This issue is closed so you should raise a new issue with more details.

![Screenshot_20231010-062343](https://github.com/home-assistant/frontend/assets/79175134/1adb6089-560c-4256-b006-0a870969b244)


What are the other attributes of your sensor?

![Screenshot_20231010-062554](https://github.com/home-assistant/frontend/assets/79175134/27bb0a0c-013d-40ba-941d-e6c2bcf48c76)

**Comment by Spottycat** [comment]
> I'm running 2023.10 and that version allows me to add consumption sensors in kWh. This issue is closed so you should raise a new issue with more details.

I see the same dialogue as you do.. and can add the sensor in kWh. But after clicking "save" the dashboard complains that its the wrong unit and cannot be used. And while the dialogue there says you can use kWh..  the dashboard will not accept the source once its added. And also the text on the dashboard is different than in that pop up dialogue (It doesn't list kWh as valid unit). 

I'll open a new issue.
