### ISSUE TITLE
NFC - Error while writing NFC Tag 

### ISSUE THREAD

**Issue by marc4s** [home-assistant/frontend#14419]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I own a lot of small iso15693 tags (SLIX-L, but SLIX and SLIX2 should be almost the same) which would be perfect for Homeaiutomation. small,selfadhesive... and the already have a UID - but it seems that phones can read those tags, but are not able to write them (sure privacy mode is NOT set!)
so why try to write a UUID to them if nobody uses so many of them that there will be a conflict...? For cloud-mode there could be a warning that the UID Tags wioll NOT be supported...

It would be great to support tags by their existing UID which enables much more tags to be supported by HA

### Describe the behavior you expected

einstead of writing an UUID - read and use the UID of the Tag

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.11.2

**Comment by spacegaier** [comment]
This is not a bug, but a feature request. Please raise it here: https://github.com/home-assistant/frontend/discussions

I think your main feature should already be possible since you can specify your own UID when creating a tag in HA. We however do not have an easy way to scan in the UID during HA tag creation which would make that easier.
