### ISSUE TITLE
Imperfection in opening the notifications tab.

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#14530]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On Dashboard pages that have scrollbars (where one or more cards leave the visual area), when I open the notifications tab, the scrollbar disappears and the page slides to the right

### Describe the behavior you expected

The page should not shift, and the scrollbar should not disappear

### Steps to reproduce the issue

1. I go to a Dashboard page in which one or more tabs are beyond the visible area
2. I open the notifications tab
3. The bug shows up
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.5

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.73

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
To make sure we are talking about the same thing: With tabs you mean views in the horizontal top header bar of the dashboard, right? The scrollbars you talk about are the "left" and "right" buttons that appear in that case?

![image](https://user-images.githubusercontent.com/114137/205455478-193796ff-0691-42d2-9da5-ef57515943ff.png)

If you are indeed talking about that, then I cannot reproduce any issues with opening the notifications. The page itself does not change or jump since the notifications are just overlayed on the left side.
Or are you talking about something else? In that case it is not clear to me.

**Comment by WRoss7** [comment]
Oops, I wanted to write cards. I corrected the report

**Comment by WRoss7** [comment]
![Img1](https://user-images.githubusercontent.com/74879713/205458291-5774eb4f-6c9f-47cd-82a9-59b1c4b181f4.png)

![Img2](https://user-images.githubusercontent.com/74879713/205458308-23fbf046-056d-4d1d-906b-17e44162e2ce.png)

As you can see in the second image the scrollbar disappears and the page expands to the right

**Comment by WRoss7** [comment]
Persistent in Home Assistant 2023.3.1

**Comment by WRoss7** [comment]
Persistent

**Comment by WRoss7** [comment]
Persistent

**Comment by WRoss7** [comment]
Persistent in HA 2023.11.3
