### ISSUE TITLE
[local calendar]: Adding event to calendar in unknown timezone

### ISSUE THREAD

**Issue by SkeLLLa** [home-assistant/frontend#14684]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While adding new event to calendar there's no indication in which timezone it will be saved. Local timezone of device? Timezone that configured in HA? UTC?

### Describe the behavior you expected

Add clear note about timezone or add timezone selector dropdown.

### Steps to reproduce the issue

1. Set device timezone to different from HA.
2. Open Local calendar integration.
3. Add event.
4. Try to set date/time.
...

### What version of Home Assistant Core has the issue?

core-2022.12.1

### In which browser are you experiencing the issue with?

Home assistant app

### Which operating system are you using to run this browser?

Android

**Comment by spacegaier** [comment]
The calendar uses the HA configured timezone. I am not sure if we need to add that to the form or whether that would confuse most users. We are not showing timezones anywhere in the frontend AFAIK (e.g. also not for `input_datetime` although I think that one technically has no timezone and just stores the values provided by the user).

@allenporter @matthiasdebaat What do you think?

**Comment by SkeLLLa** [comment]
Maybe at least add some text snippet about timezone. Or a hint that below the input will show the time in HA instance timezone.

Naturally users think about time in a timezone they are currently in. Therefore if some user currently situated in a different timezone rather than HA configured, when they add an event from 11:00 to 12:00 and immediately after that go to calendar, they will see different time. And that might be confusing.

**Comment by allenporter** [comment]
In general as I've learned about calendar systems I believe the work this way:
- A calendar itself will have data stored in a particular timezone (or it can be floating w/o, but we're not doing that). Home Assistant is definitely using the home assistant timezone for this.  (Technically this can be per event event)
- A viewer or attendee may be in a separate timezone and view the calendar in that timezone.  This has an impact on how things like "All day" events are sorted in with events with a specific timezone.

We also want to ensure a viewer has a consistent view of times across the Home Assistant frontend independent of calendar. For example, if you are viewing the Log Book which has a list of events that occurred those would also need to be in sync with the Home Assistant calendar events and timezones.  There are some other technical details about how core itself needs a timezone to work in for automations and fetching from calendar APIs like Google Calendar, but i think the general point I'm assuming we'd likely not show different timezones based on the viewers browser.

I *think* the issue may be that if you enter 11:00 to 12:00 then it should be created at 11:00 to 12:00 in the home assistant timezone, rather than converting from browser time to home assistant time. (You're saying that is what is happening, but i haven't tried it myself, but it makes sense).  If that were the case, then i think it wouldn't be surprising and consistent with dates shown across the entire system.

**Comment by SkeLLLa** [comment]
So I see that with updated core-2022.12.4 the behavior had changed. Now events are added in local browser timezone.

**Comment by spacegaier** [comment]
> 2022.12.4

That version did not contain any local calendar changes in the frontend. Not sure if something was changed in the backend.

@allenporter Did you adjust something in core?

**Comment by allenporter** [comment]
Thanks, i think we have enough info, i'll take a look.
