### ISSUE TITLE
[German]: translations for 'no motion' on motions sensors are bad/confusing

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#14807]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Motion sensors have logically two statuses:

- motion
- no motion

Somehow in the German translation the 'no motion' part have three different texts showing up in different locations in the GUI and none of them make sense:

- As status in Lovelace's *entities* it's 'Normal' - English = 'normal'
- In the log view it's 'zurückgesetzt (kein(e) erkannt)' - English = 'reset (no detected)'. German here is also grammatically wrong in the brackets: correct would be '(Niemanden erkannt)' or '(nichts erkannt)'.
- In the History it's shown as 'Aus' - English = 'off'. That's kinda confusing as it sounds on its own like the motion detection is turned off. 

![Screenshot from 2022-12-16 17-40-55](https://user-images.githubusercontent.com/614929/208147674-239d82de-4a58-4881-88c7-230bde9428cf.png)

In English the values are:

- 'Clear'
- 'Cleared (no detected)'
- 'Off'

### Describe the behavior you expected

A German translation which sounds correctly to me would be:

'Nein' for no motion and 'Ja' for a motion. 

That's 'no' and 'yes' in English.

### Steps to reproduce the issue

1. Use a motion sensor
2. Select German translation for the frontend

### What version of Home Assistant Core has the issue?

core-2022.12

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 106.0.5 / Chromium 107.0.5304.87

### Which operating system are you using to run this browser?

Arch Linux

**Comment by spacegaier** [comment]
Translations are handled by the community, see https://developers.home-assistant.io/docs/translations/.

Reg. your second point: I think "nichts erkannt" is better, since a motion sensor does not necessarily only detect people. Could be used for anything, also objects, animals, ...

And if I remember correctly this somewhat weird "kein(e)" construct has to be used since those translations are somewhat generic for all different device classes of binary sensors as it also has to work e.g. for "no sounds" =( kein Geräusch) or "no moisture" (= keine Feuchtigkeit).
