### ISSUE TITLE
How do I setup a webcam in HA?

### ISSUE THREAD

**Issue by LucidEye** [home-assistant/frontend#14870]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

How do I setup a webcam and a microphone in hass.io?
I asked in the discord and was answered with: "Why would you need a camera for automation"?
ARE YOU FUCKING KIDDING ME?!?!?!?
Motion detection for one.  
Sound detection for another... as in maybe I would like to use the microphone on my webcam for trying out the voice control like Rhasspy or Ada.
And how do I connect a simple speaker?  I have a nice Oontz Angle 3 Bluetooth speaker with a mic, and there is NO WAY TO CONNECT THAT EITHER?!?!?!?!?!!!!!??????? WTF??!?!?!

One would think this should be plug and play... as pretty much all webcams and speakers are today.  But it seems like I need a degree in software engineering just to get a simple microphone working in HA?

What is the point of Home Assistant if it wastes so much more time than it saves?
If I need to spend months learning 3 different programming languages just to get a microphone working, then what is the point?  How is that being an "assistant"?
Is HA a joke?  Is it still in alpha development, because it doesn't really seem like it is even in beta stage yet if you can't use it without knowing so much coding?

### Describe the behavior you expected

Plug and play ease of use for standard hardware like a webcam or a Bluetooth speaker... all I really want is to connect a microphone to HA so I can try out the Rahsspy or Ada voice control!!!  It should be simple plug and play to get this ubiquitous hardware working!!!

### Steps to reproduce the issue

1.
2.
3.
...
This issue is reproduced every time a new user tries HA.

### What version of Home Assistant Core has the issue?

latest hass.io on a 8gb Pi4

**Comment by frenck** [comment]
> ARE YOU FUCKING KIDDING ME?!?!?!?

> 

Closing this issue for two reasons:

- Let's keep things civil. There is no reason to use such language or shout (referencing the full caps sentences).
- This is an issue tracker, which we use for tracking frontend bugs. This issue is not reporting a bug but letting out frustration in a pretty offending way.

Please, if you want people to help you or have a conversation with you, the above tone in this issue won't help.

Consider this a warning for violating our Code of Conduct.

Nevertheless, still the kindest regards and happy holidays!

../Frenck
