### ISSUE TITLE
Submit button is missing

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#14948]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to change the device area of an entity, the „submit“ button is not being displayed/invisible:

![98C042BD-B25B-40B5-BD54-A72B99EA2535](https://user-images.githubusercontent.com/71203830/210172462-27a71fef-e227-4662-8082-b4cd83492966.jpeg)

### Describe the behavior you expected

A visible button

### Steps to reproduce the issue

1. Choose a dashboard view
2. Choose an entity
3. Call the more info dialogue 
4. Click „Change device area“ link (or whatever it is in English)
5. Change the assigned area and try to find the submit button
...

### What version of Home Assistant Core has the issue?

core-2023.1.0b3

### In which browser are you experiencing the issue with?

Safari 16.2, Chrome 108.0.5359

### Which operating system are you using to run this browser?

iPadOS 16.2, IOS 16.2

**Comment by karwosts** [comment]
Might be the same as https://github.com/home-assistant/frontend/issues/14873

The button is there, but it has no label because the translation for "submit" is not loaded into the translation dictionary.

**Comment by piitaya** [comment]
Some dialogs uses `panels` translations. Panels translations are only loaded from the panel page.
If you open the dialog from device page, it works
If you open the dialog from dashboard, it doesn't work

**Comment by karwosts** [comment]
Note the text for the toggle is also missing. The particular translations missing here are all "ui.panel.config.*" translations, which are not loaded, when arriving here by refreshing, opening an entity "more-info" popup, and then changing the setting from there. 

Seems like there are probably several ways to navigate to this window. If the keys should be changed, than changed to what? 

Similar thing happens when you try to open a group from the dashboard, it is also missing translations from ui.panel.config.

**Comment by pedolsky** [comment]
Back since core-2023.2
