### ISSUE TITLE
Unable to pick gas source with unit of measurement m³ on energy dashboard

### ISSUE THREAD

**Issue by fhwi93ne** [home-assistant/frontend#15108]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am not able to add my gas sensor as gas source to the energy dashboard. It does not show up.
The gas sensor was set up by MQTT-discovery, the sensor meter itself is an AI-on-the-edge-device.
The sensor was set up as device class gas with unit of measurement m³ --> see MQTT diagnostics
[mqtt-674ff52a4dab16712426a6d9b70c7bba-esp32-gaszaehler-0ff24dd3b234988b20946b1663dc5577.json.txt](https://github.com/home-assistant/frontend/files/10418883/mqtt-674ff52a4dab16712426a6d9b70c7bba-esp32-gaszaehler-0ff24dd3b234988b20946b1663dc5577.json.txt)

### Describe the behavior you expected

The sensor can be picked on the energy dashboard as gas source.

### Steps to reproduce the issue

1. Open Energy Dashboard
2. Add gas source
3. type sensor name

### What version of Home Assistant Core has the issue?

2023.1.4

### In which browser are you experiencing the issue with?

Chromium 109.0.5414.87

### Which operating system are you using to run this browser?

Windows10, also iPadOS 16.2

**Comment by alvinchen1** [comment]
Interesting because m³ should be able to be added.  There are some gas with units of measurement that aren't supported to be added right now, see https://github.com/home-assistant/frontend/issues/15038, but m³ should work.

Check one more thing, in developer tools, states, your gas meter, make sure you have the following attributes:

state_class: total_increasing
device_class: gas

If you are missing either of those, that may be what is preventing you from adding your gas meter to the Energy Dashboard.  If you don't have either of these attributes, you might want to add them to customize.yaml

sensor.your_gas_meter:
  device_class: gas
  state_class: total_increasing

Reboot and see if that fixes it.  Gas Meters must have these attributes to be added to Energy Dashboard, and some your MQTT sensor may not add it in.

**Comment by alvinchen1** [comment]
Resolved in 2023.1.  Can be closed
