### ISSUE TITLE
Renaming of entity ids is not working correctly

### ISSUE THREAD

**Issue by flobernd** [home-assistant/frontend#15253]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When renaming a device, a dialog pops up:

```
Do you also want to rename the entity IDs of your entities?
```

When choosing `RENAME`, the friendly name of the device and all the related entities is updated, but the `entity_id`s remain unchanged.

### Describe the behavior you expected

The entity ids are renamed like the dialog suggests and it is documented in the official documentation.

### Steps to reproduce the issue

1. Rename a device
2. Choose `RENAME` in the folloing `Do you also want to rename the entity IDs of your entities?` dialog
3. See that the related entity friendly names are renamed but the entity ids are not

### What version of Home Assistant Core has the issue?

2023.1.6

### Additional information

I originally opened an issue in the `home-assistant/core` repository but was asked to instead open an issue here.

Reference: https://github.com/home-assistant/core/issues/86786

**Comment by piitaya** [comment]
Only entity ids containing device name will be renamed.

### Example
You have a **Bed Light** device with some entities : 
```
light.bed_light
sensor.bed_light_power
sensor.bedroom_light_temperature
```

If you rename your device to **My Light** and choose "rename entities", the entities will become : 
```
light.my_light
sensor.my_light_power
sensor.bedroom_light_temperature
```

The last one is not changed because it doesn't contain the previous device name.

**Comment by flobernd** [comment]
Thanks for your reply! Technically it should match in my case. For example I have the device `Ceiling Light 1` and the entities:

```
light.ceiling_light_1_4
```

Still renaming does only work for the `friendly_name` of the entity, not for the `unique_id`.

**Comment by piitaya** [comment]
I have this behavior


https://user-images.githubusercontent.com/5878303/215513387-5f84fde7-0ec3-4f5c-88cf-8379772efb93.mp4

**Comment by piitaya** [comment]
The entity renaming feature can be frustrating. I hope we can improve the UX in the future 🙂

For your question : 
The front-end use the `config/entity_registry/update` websocket endpoint to change the entity.

```ts
{
    type: "config/entity_registry/update",
    entity_id: "light.old_id",
    new_entity_id: "light.new_id",
}
```

Personally, I spend lot of time to rename my entities manually 😂

**Comment by flobernd** [comment]
Thanks a lot, that should get me started 🙂 

> Personally, I spend lot of time to rename my entities manually 😂

Yeah, me too, but after I integrated Hue with ~100 devices, I thought it might be good to automate this somehow.

**Comment by Roarrk** [comment]
I am currently having a huge headache renaming several hundred entities after migrating from z2m to ZHA. ZHA misnamed all the enteties despite the correctly named devices. So I am now sitting with a list of entities like "lumi_lumi_weather_humidity" on a device otherwise correctly named "Office Temperature". This goes on for all entities of around 40 devices. When renaming the parent-device, I get the dialog to rename all entities, but this does not work.

My request is that, since HA is obviously aware of the device->entity relationship, it should also be able to rename all entities despite substring matching not working.

**Comment by RN-Say** [comment]
I recently ran into a similar issue with failed entity renaming for my Apollo multisensor under the esphome integration and I solved it as follows:

1. Take note of the name pre-pended to the device's entities: sensor.apollo_msr_1_6aeddb_xxxxxxx
2. Rename the device to match that name: apollo msr 1 6aeddb
3. Click Update.
4. Rename the device again: Master Bedroom Multisensor
5. Click Update
6. Agree to rename entities.

After that I had: sensor.master_bedroom_multisensor.xxxxxxx. 
Thank goodness since there are 81 entities associated with this sensor!!!!
