### ISSUE TITLE
undefined is not an object (evaluating 'e.map')

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#15430]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since core-2023.2 (Supervised), every few days I get the following error:

```

Logger: frontend.js.latest.202302020
Source: components/system_log/__init__.py:254 
First occurred: 13:55:58 (10 occurrences) 
Last logged: 16:48:41

http://192.168.178.24:8123/frontend_latest/b1148040.js:1:5378 TypeError: undefined is not an object (evaluating 'e.map')

```

I have absolutely no idea where to start. 

### Describe the behavior you expected

No error message ;) or a message with a hint, where to start to solve the problem. 

### Steps to reproduce the issue

1. ???
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2023.2.3

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.77/78, Safari 16.3

### Which operating system are you using to run this browser?

IOS 16.3, iPadOS 16.3

**Comment by pedolsky** [comment]
Not solved.

**Comment by PeteKraft** [comment]
I just upgraded to 2023.7.0 and this issue started popping up in my log as well...

**Comment by karwosts** [comment]
If you can find any action or page which triggers this (open your browser console since it will likely be displayed there as well), that would help isolate where it's coming from.

**Comment by PeteKraft** [comment]
Aha !
Apparantly this error appears when I look at one of my Dashboards...

It is caused by the sensor card, more particular, I have excluded this particular sensor from my recorder data, because it was filling the home-assistant_V2.db... 

So obviously there is no data in the data for the sensor card to display... and thus it throws this error.
Maybe a more gracefull error would be nice..

The full error inside the browser inspector is this:

`[Error] TypeError: undefined is not an object (evaluating 'e.map')
	a (28922-Nx-Fg0vPO5M.js:2:14621)
	(anonymous function) (28922-Nx-Fg0vPO5M.js:2:18892)
	(anonymous function) (core-Bgg17Xv0dRA.js:1:5852)
	forEach
	(anonymous function) (core-Bgg17Xv0dRA.js:1:5775)`

**Comment by karwosts** [comment]
I actually just fixed this same issue in sensor card for a different user (#17181)

Lets see if it is fixed for you and OP after next release.
