### ISSUE TITLE
Zwave Thermostat Card: Temperature Set point 'jumps back'

### ISSUE THREAD

**Issue by marlemion** [home-assistant/frontend#15776]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a bunch of thermostats connected via Zwave. Naturally, those devices are powered by battery and hence will wake up from time to time (300s in this case). Thus, if I set a temperature in the thermostat, it might be that this value is set over four minutes later (and thus can be verified by that time only).

When I set the temperature by the thermostat card, the slider jumps back to the original value after about ~2s. Nevertheless, when the device wakes up, the set temperature is correctly updated and the slider jumps to the selected temperature.

However, this is very annoying and irritating, as one never really knows to which temperature the slider has been set. Or one would like to check the newly set temperature a few minutes later just to see still the original value.

### Describe the behavior you expected

The thermostat should respect the sleeping interval of the underlying device, e.g. the zwave device in this case. Only after the next update, the slider should go to the newly set temperature (or maybe the original value).

### Steps to reproduce the issue

1. Install a zwave thermostat
2. Add it to a zwave network (Zwave JS addon)
3. Find the thermostat in lovelace
4. Set temperature at the thermostat
5.  See the slider jump back to the original value after 2s
...

### What version of Home Assistant Core has the issue?

 Home Assistant 2023.3.2 Supervisor 2023.03.1 Operating System 9.5 Frontend 20230306.0 - latest 

### In which browser are you experiencing the issue with?

Firefox 100.0 64bit Windows

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Yes this was changed in https://github.com/home-assistant/frontend/pull/15497, based on a few user requests, and to match the already existing behavior in more-info. 

Sorry it's not working out for your usecase, I wasn't aware that some devices would have such a long lag time between update and response. I'm trying to think of what could be done. I'm not aware that the frontend has any visibility into the backend details of the climate, like if it is a battery device or not, or how long its refresh interval might be, so I'm not sure if we can toggle behavior based on that. 

I could maybe imagine an option in the card settings like `optimistic: true` which disable this behavior, but that's somewhat esoteric, so I'm not confident if the devs would go for it. More opinions welcome.

**Comment by marlemion** [comment]
Thanks for your reply. Good to know that something has been changed, I was worried that my setup was borked (actually, I reinstalled the whole zwave thing to be sure that it is not related thereto).

I wonder whether my usecase is so rare. I think a lot of thermostats are battery driven and thus have wake up intervals in the range of minutes.

How about a freely adjustable 'waiting' interval before jumping back? According to my understanding, the 2s are hardcoded now (what is actually anyway not the best idea to be hones). If that could be reached somehow through the GUI and set by the user... 

Nevertheless, reading the devices specs in this direction would be the best solution....

**Comment by sgbirch** [comment]
No, it's not rare.  I am sure this will be a very common problem for battery operated devices.   Let's start with (imho) an ideal solution ... to display the requested temperature AND the acknowledged temperature until they both match after an update.  That way it is clear what is actually happening.

Incidentally, trying to use z-wave thermostat devices in scenes is hopeless with similar delayed behaviour presenting.   I wonder if the set/update mechanism needs a rethink?

**Comment by karwosts** [comment]
>  Let's start with (imho) an ideal solution ... to display the requested temperature AND the acknowledged temperature until they both match after an update. 

I just want to point out that the requested temperature is not stored anywhere. If you for example switch to a different tab and switch back, or refresh the page, you will not see the requested temperature. That would have been true even before my change. 

That's why I'm not a fan of trying to make it the responsibility of frontend to hold onto state that isn't stored anywhere, since then just toggling tabs is going to change what is displayed.

And this behavior is similar to what you'll see for things that have long update times. For example if you have a switch and you toggle it, you'll see the switch turn to on for a second or two, and if the entity state does not update, it will revert back to showing off. Then if and when the entity does update, it goes back to on.

**Comment by karwosts** [comment]
In the meantime while this is being discussed, if you need something to show the last requested temperature, you can always capture it in an automation and display it. This will have the advantage of being persistent across page refresh.

![climate_last_temp](https://user-images.githubusercontent.com/32912880/224407880-08407094-b804-4c85-927f-06d2647fe791.gif)

```
alias: Climate Temperature
description: ""
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: climate
      service: set_temperature
condition: []
action:
  - service: input_number.set_value
    data:
      value: "{{ trigger.event.data.service_data.temperature }}"
    target:
      entity_id: input_number.climate_target_temperature
mode: single
```

**Comment by sgbirch** [comment]
Very clever suggestion.  Thank you.

**Comment by karwosts** [comment]
The entity_id of the climate object that was changed is available in the triggering service_data. But lets not let this issue thread get sidetracked in automation debug; if you need more help, suggest heading to the discord or asking on a community forum for help for how it can be extended.

**Comment by liquidat** [comment]
Since I just found this:
@marlemion, you are not alone in this. I have the exact same problem, with Zigbee and Zwave thermostats alike. The UI experience for battery powered thermostats is pretty bad now: people who are not aware of the underlying technical details are now constantly setting the new temperature, while getting very frustrated with the setup. Also, current UI behavior is inconsistent: the main dial jumps back, but when I go into the details, it does not jump back:
![image](https://github.com/home-assistant/frontend/assets/1998084/b44826ce-9e3f-4df8-9cd7-fb62689d4f5d)

From where I am, https://github.com/home-assistant/frontend/pull/15497 should not have been merged. The "jumping back after 2s" ONLY works for non-batter powered devices if I am not mistaken. I would bet that this is the less common use case! And just jumping back doesn't really help anyone:

- No indication that there was any mismatch. Users will have no idea why it jumped back (Did I really set the new temperature or did I just zone out for a second? Or was this a UI glitch?)
- No information what the difference between the value set and the value we currently still have is there, so I don't even know what it was set to until the next sync.

A better UI solution (no idea how to make this real with the underlying setup) would be to indicate in the card that there is a certain value set and that the communication to the device still takes place, that the newly set thing is not in effect as of yet.
