### ISSUE TITLE
Energy dashboard shows negative bar (returned energy) 

### ISSUE THREAD

**Issue by bestrocker221** [home-assistant/frontend#15803]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I setup a simple energy meter that gives the local consumption via rest API.
The assistant is fetching that and the energy sensor works properly if I open the entity.

In the energy dashboard the bar charts are wrong, sometimes it shows "energy returned" (and that means negative bars) while it should be "energy consumed" instead.

![Screenshot from 2023-03-13 07-03-18](https://user-images.githubusercontent.com/11471776/224621096-0d654045-0b85-4269-b9f4-b5d8cd74ae2b.png)

The values are correct in the meter, as the proper data is correctly shown in the energy sensor below:

![Screenshot from 2023-03-13 07-10-37](https://user-images.githubusercontent.com/11471776/224621231-d7d4d472-f844-426b-abd2-f03ce4820066.png)

### Describe the behavior you expected

I would expect the bar chart to only show energy consumed, as I have not set up any energy sensor that provides electricity.

### Steps to reproduce the issue

1. point energy meter to real time REST API 
2. look at the energy dashboard

### What version of Home Assistant Core has the issue?

2023.3.3

**Comment by karwosts** [comment]
I think you must have a sensor configured incorrectly. 

Your sensor which is "energy consumed in the last hour" is being interpreted by HA as "total amount of energy consumed", that it expects to see increasing. 

That's why when the value decreases from 12am to 1am, HA thinks you actually used negative energy, not just that you used a bit less than in the previous hour. 

I would review here about the different energy state classes: 

https://developers.home-assistant.io/docs/core/entity/sensor/#how-to-choose-state_class-and-last_reset

And please provide more details about this sensor - exactly how it was configured, and what is shown for all attributes in the developer tools.
