### ISSUE TITLE
Home Assistant Cloud Netatmo - Dimmer switches are not working properly

### ISSUE THREAD

**Issue by DR-WIFI** [home-assistant/frontend#15969]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have Netatmo Dimmer switches and when I turn on the light, it turns on but from the dashboard the toggle switch goes on and then goes back to off.

When the light switch is already on, from the Dashboard will show as On but when I turn it off, it goes back to Off and then goes back to On from the switch. Actual light will go off. 

Sometime, the toggle switch will actually move within few mins. It seems to be there's delay.

Any reason why?

### Describe the behavior you expected

Toggle switch should move to the position and stay.

### Steps to reproduce the issue

1. Turn On
2. Actual Light goes On
3. Dashboard toggle switch will go On but goes back to Off
...

### What version of Home Assistant Core has the issue?

2023.1.6

### What was the last working version of Home Assistant Core?

2023.1.6

### In which browser are you experiencing the issue with?

111.0.5563.65

### Which operating system are you using to run this browser?

Win 10 Pro

**Comment by karwosts** [comment]
Your light is either too slow in updating state in response to the commands, or not updating at all. 

Frontend toggles the switch immediately when you click it, but if it does not receive an update from the light indicating that the state changed within a few seconds, it assumes the command failed and the frontend switch display goes back to off, because the state of the light is still "off". 

You would need to investigate in the backend why your light is not updating promptly, but from the perspective of the frontend this is working as intended.

**Comment by DR-WIFI** [comment]
Hi, Thanks for your reply.

I found out that, it works but there's a delay in updating the dashboard.
How do I investigate this issue going forward? Any suggestion? 

If I use Legrand Home+ App and Google Home works fast. HoA is the only one that works slow..
