### ISSUE TITLE
Action button overlaps last item in list preventing list item options being esily clicked

### ISSUE THREAD

**Issue by deosrc** [home-assistant/frontend#16210]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When browsing a large list in settings, there is no padding/margin at the bottom of the list. This means that the action button can overlap the buttons on the list items.

I am experiencing this on the backups page. In order to delete the oldest backup, the scroll must be adjusted slightly up from the bottom so that the delete button for the backup is visible between the "Create Backup" button and the bottom of the browser window.

Delete backup button obscured by create backup button:

![image](https://user-images.githubusercontent.com/50599779/232471382-e65e4763-60a2-4e41-869e-731eb9b30fe4.png)

Workaround to scroll up slightly so that the button can be clicked below:

![image](https://user-images.githubusercontent.com/50599779/232471489-e63011c1-63cf-4d51-8958-e6a2c49281ea.png)

### Describe the behavior you expected

There should be margin/padding at the bottom of the list so that scrolling to the bottom of the page does not obstruct the last page in the list.

### Steps to reproduce the issue

1. Go to backups page in settings
2. Create enough backups or resize window so that the list can scroll
3. Scroll to the bottom of the list
4. Attempt to download/delete the last item in the list. The buttons are obscured by the create backup option.

### What version of Home Assistant Core has the issue?

2023.4.4

### In which browser are you experiencing the issue with?

Firefox 109.0.1

### Which operating system are you using to run this browser?

Windows 10

**Comment by santosh-kuchetti** [comment]
@deosrc 
demo.home-assistant.io](https://demo.home-assistant.io/
is this the website link you are facing the issue or another, because i can't see settings here in this website
please let me know,with details,
i would love to work onthis issue

**Comment by blueskiestailwinds** [comment]
I find the same behavior on the Blueprints and Scripts pages. I don't normally have the problem on those pages because I don't have enough of those items to fill the screen, but if I shrink the Y axis of the window the "Create..." button does interfere. 

![overlapping scripts](https://github.com/home-assistant/frontend/assets/71535066/6a55d17a-fd9f-4e9e-8dc5-87de3d88ab05)

![overlapping blueprints](https://github.com/home-assistant/frontend/assets/71535066/40f40137-2bc8-4d12-bdfa-de93b0351338)

A minor scroll does work to expose the icon enough to click. I also worked around it by temporarily deleting the ha-fab element via Chrome Inspect.
