### ISSUE TITLE
History graph is sometimes misaligned on the right hand side with show_names: false

### ISSUE THREAD

**Issue by kchiem** [home-assistant/frontend#16269]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some times, the right edge of the two different types of history graphs shown below become misaligned.  

![ScreenClip](https://user-images.githubusercontent.com/17679003/233727817-bfaffe16-f1e8-4404-9a8b-0e579515e469.png)

The graphs will be aligned, then suddenly it'll pop out of alignment, then slowly re-align over several minutes.  This repeats.

Not shown, but I've also noticed that the left edge of the top bar graph pops in and out of alignment occasionally as well, but that only lasts 1-2 secs.

### Describe the behavior you expected

I expect the left and right edges of the graphs to stay aligned.

### Steps to reproduce the issue

1. create a history graph with a combination of sensor and binary_sensor entities
```
type: history-graph
entities:
  - entity: sensor.something
  - entity: binary_sensor.something_else
refresh_interval: 60
hours_to_show: 2.1
show_names: false
```
2. observe over time
3. profit

### What version of Home Assistant Core has the issue?

2023.4.5

### In which browser are you experiencing the issue with?

Google Chrome 112.0.5615.138

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.2846

### Additional information

Have observed this behavior in Microsoft Edge 112.0.1722.48 as well.

**Comment by kchiem** [comment]
@karwosts Is this up your alley?

**Comment by karwosts** [comment]
I think probably what is happening is when chartjs draws an axis label right at the very end, it compresses the chart area horizontally so that it can fit the axis label that overflows off the edge within the same area. 

![image](https://user-images.githubusercontent.com/32912880/235355137-6699345b-cc20-477c-9612-60bbab83e574.png)

I saw the same thing in the other direction as well, with the timeline chart getting squished for the label:

![image](https://user-images.githubusercontent.com/32912880/235355203-88e129ea-48db-45e3-b3d7-1efd4579eb5d.png)
