### ISSUE TITLE
Energy cards not following Theme

### ISSUE THREAD

**Issue by criticallimit** [home-assistant/frontend#16699]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Two of the energy cards are not showing themes:

type: energy-date-selection
type: energy-sources-table

but these are following the theme:

type: energy-distribution
type: energy-devices-graph

### Describe the behavior you expected

all energy cards should follow theme settings

### Steps to reproduce the issue

create lovelace cards and set a theme

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Safari actual release

### Which operating system are you using to run this browser?

macOs 13.4

**Comment by karwosts** [comment]
It may help if you can be a little more specific, which elements/colors are not as expected, and include screenshots.

**Comment by criticallimit** [comment]
Here a screenshot:

![Bildschirmfoto](https://github.com/home-assistant/frontend/assets/5613811/08795b6e-bf01-4194-bd25-5d22bc81043c)

As you can see, shadows are not shown in two of the energy cards

**Comment by ChristophCaina** [comment]
at least the date selector is somehow a special case, because it is transparent.
If you select another theme with a background image, you can see, that the date selector is just showing elements placed on that image - without the typical "Card" options.

![image](https://github.com/home-assistant/frontend/assets/26391061/9204cba0-b391-4693-b0c5-5ac71e08198a)
![image](https://github.com/home-assistant/frontend/assets/26391061/3481a121-73f2-479a-a4ca-dba8b741987b)

But for the sources table I would agree - this should be a "regular" card that also apply theme changes.

![image](https://github.com/home-assistant/frontend/assets/26391061/60f48ac2-9061-4e91-834e-e9b636fe29dd)
![image](https://github.com/home-assistant/frontend/assets/26391061/29b3e3ec-2021-48c8-aab4-6a928613d4cb)
