### ISSUE TITLE
Translation missing for HVAC Fan modes

### ISSUE THREAD

**Issue by Flappiee** [home-assistant/frontend#17175]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi have an MHI airconditioner.
I'm using ESPHome with the MHI components from ginkage/MHI-AC-Ctrl-ESPHome from Github.

When i check my Home Assistant developer tools is says:

fan_modes: auto, low, medium, high, quiet

I have my Home Assistant in Dutch.
When i'm controlling the fan speed i see:

Hoog (=high)
Gemiddeld (=medium)
Laag (=low)
quiet (=quiet, this one is not translated)

### Describe the behavior you expected

Fan mode "quiet" should be translated as something like "Stil"

### Steps to reproduce the issue

1. Use HVAC unit that supports high, medium, low and quiet
2. Set language to "Dutch"
3. You will see that "quiet" is not translated
...

### What version of Home Assistant Core has the issue?

2023.7.0

### In which browser are you experiencing the issue with?

All browsers and Companion App

### Which operating system are you using to run this browser?

Windows 11, Android

### State of relevant entities

```txt
hvac_modes: off, heat_cool, cool, heat, fan_only, dry
min_temp: 18
max_temp: 30
target_temp_step: 1
fan_modes: auto, low, medium, high, quiet
swing_modes: off, vertical
current_temperature: 25
temperature: 21
fan_mode: quiet
swing_mode: off
friendly_name: woonkamer-airco
supported_features: 41
```

**Comment by Flappiee** [comment]
![2023-07-05 22_23_49](https://github.com/home-assistant/frontend/assets/55132512/28e92583-67d4-463e-87c8-9324a865e012)

**Comment by piitaya** [comment]
Hi 👋
State translations are managed by backend, not frontend. Also, according to the developer documentation, climate has support for the following built-in [fan modes](https://developers.home-assistant.io/docs/core/entity/climate#fan-modes) :
- on
- off
- auto
- low
- medium
- high
- middle
- focus
- diffuse

It can also support custom ones (in your case the quiet mode). But, as it's custom, backend can not provide translations for this mode, that's why you don't have it. Integration can also provide custom translation using [entity state attributes](https://developers.home-assistant.io/docs/internationalization/core#entity-state-attributes) but that's not possible with esphome. 
I can suggest you to open an issue in the ginkage/MHI-AC-Ctrl-ESPHome repo to use one of the built-in mode if you want translations.
