### ISSUE TITLE
Entity picker: list contains entities which do not conform to a selected filter

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17386]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

First was observed in History view - but this was also observed in Entities card (may be a common behaviour).

Start creating a new Entities card, then start typing an entity_id in a corresponding field.
The list of entities contains not only entities which have a defined substring - but also other entities which have "similar" names:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/67624133-9e3e-426f-933c-cd53529f99a8)
Here a user defined the `availability_u` substring - but many entities w/o this substring are displayed.
Do not think this is a correct behaviour.
You need to continue typing a substring; for `availability_un` substring only needed entities are included.

### Describe the behavior you expected

Only entities which have a defined substring in their entity_id (or a name) should be included in a list.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.7.1

### In which browser are you experiencing the issue with?

Chrome 115.0.5790.102

### Which operating system are you using to run this browser?

Win10

**Comment by karwosts** [comment]
I guess you're probably seeing the result of this, I think the filters were changed to a fuzzy search which forgives some small percent of mismatching characters. 

https://github.com/home-assistant/frontend/pull/16912

**Comment by ildar170975** [comment]
Thanks for a reply!
Seems that this whole "add fuzzy logic" idea came from users who prefer using names instead of entity_ids.
As a result - the list contains lots of items not matching a defined filter (none of these items contain an `availability_u` substring).

**Comment by cdonovan** [comment]
There shouldn't be anything stopping you from continuing to use `entity_id`; the filtering & sort matches against *both* `entity_id` and `friendly_name`. **Exact** partial string matches will always rank higher than fuzzy ones and therefore appear at the top.

There will now likely be additional, potentially less relevant items below the exact matches, but the exact matches should always appear first.

E.g. I have entities with the following entity ids:
* media_player.master_bedroom_androidtv
* media_player.master_bedroom_tv
* remote.master_bedroom_androidtv

If I perform a search for `master_bedroom_tv`, all three appear, **but** `media_player.master_bedroom_tv` appears first in the list, since it's the "closest" (exact partial) match.

I noticed in your screenshot that you've already scrolled the list a good ways down from the top.  It would be a helpful to see what the top results are. I'm *guessing* they will all be items that contain the exact partial string `availability_u` (which is why you needed to scroll down to get to the less relevant results).

I did mark my PR as a breaking change, expecting that some people might be a bit thrown off by the change in UX, but I guess that never made its way to any release notes.

Going forward, perhaps we could look into making this user-configurable in some manner (e.g. a toggle in the user settings menu).

Since being implemented I've found it *much* easier to get to what I want. With many thousands of entities, I don't always remember the specific string that I provided, or (more frequently) the system generated for me. But I do know the "general" idea of the name (either `entity_id` or `friendly_name`) and with a tiny adjustment in the way I think about searching, am able to get what I want typically in less than half the time it took previously. E.g. typing what I *think* it's named, getting no results, backtracking, trying slight variations, etc. and eventually many times, going to the "quick search" feature where this fuzzy logic was pulled from and using that to figure out the right entity string.

**Comment by karwosts** [comment]
I wouldn't consider that a breaking change, a breaking change is something that requires users to modify something in their configuration or else something will stop working. This is just a slight adjustment in UI behavior.

> Going forward, perhaps we could look into making this user-configurable in some manner (e.g. a toggle in the user settings menu).

I very much doubt that maintainers would ever want to add this.

**Comment by karwosts** [comment]
I'll close this, as I don't think there is an active issue here. The fuzzy search was definitely an intentional change, and the behavior described here is expected. 

If you want to debate the merits of fuzzy search, feel free to continue this in the discussions section.

**Comment by ildar170975** [comment]
@karwosts 
OK, here is the discussion: https://github.com/home-assistant/frontend/discussions/17474
I am absolutely sure that this "fuzzy logic" may give absolutely wrong results, like here:

![image](https://github.com/home-assistant/frontend/assets/71872483/e467893d-0e23-4dce-b913-486c10a033b3)

So, I consider this as a bug, not a subject to discuss...
