### ISSUE TITLE
Automations editor assumes automations.yaml included

### ISSUE THREAD

**Issue by akonradi** [home-assistant/frontend#17805]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding automations via the UI, they get successfully written to automations.yaml. If that file isn't included by configuration.yaml, the added automations never show up in the UI, even after saving.

### Describe the behavior you expected

Either the automations should be added to the section in configuration.yaml, or an include should be added there, or an error should be surfaced in the UI. It should not silently do the wrong thing (save to a file that is never used).

### Steps to reproduce the issue

1. Create a configuration.yaml without an automations section
2. Create an automation via the UI and save
3. Look at the list of automations

### What version of Home Assistant Core has the issue?

2023.8.4

### In which browser are you experiencing the issue with?

Firefox 117.0, also Home Assistant companion app

### Which operating system are you using to run this browser?

Android 13

**Comment by KevinCathcart** [comment]
As a rule, Home Assistant does not modify user YAML files (automation.yaml is a generated yaml, not a user yaml), so some form of warning or error is the appropriate approach. Do keep in mind that users may have only some automations in automations.yaml, and others included from packages or labeled automation keys, and also that we need to handle the case where automations.yaml is `!include`d, but is currently empty. 

Thus in order to check this ahead of saving, the key would be knowing that automations.yaml is not included. This is actually complicated. A simple string search will not work, because the user might have [added a label](https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-combine-include_dir_merge_list-with-automationsyaml), or reformated the line. Furthermore, this line could have been moved from configuration.yaml to some other `!include`d file. 

Home Assistant does not record the list of !included files when parsing a full config. It does record that a list came from a specific file, but that still won't work. See if the user uses the [packages](https://www.home-assistant.io/docs/configuration/packages/) feature, then this data is not preserved when merging those into the config (as it was really only intended for error messaging during initial validation). And this is not hypothetical, I've literally seen people who moved the `!include` for automations, scripts and scenes into a package.

So now this would suggest that to error ahead of time, either the view must reparse the configuration.yaml file, without merging packages, and look for any dictionary that has `__config_file__` set to automation.yaml, or yaml loading must be change to better track what files are `!include`d, or something alone those lines.

What might be more feasible is to error after saving by checking that the newly written automation shows up when reparsing the config, and if not, providing an error message instructing users that they need to add that include.

---

As for why Home Assistant does not edit user yaml files, well for one thing, it is nearly impossible to do safely without upsetting users. Users get upset if their comments get removed, or if their `!secret my_password` values get replaced, or just having their strings reformatted from they way they like them, etc. That basically rules out parsing to a simple object model and  serializing back again. So a special format preserving parser that understands the home-assistant specific directives would be needed to do it right, and even then users may be unhappy about the output stuff even if everything else was left untouched.

The mere fact that automations, scripts, and scenes created in the UI are stored as generated yaml files is already a compromise, because normally this UI created data gets stored as json inside the .storage folder. This could have been possible here too, even with the editor still offering a yaml view, as dashboards actually work that way. However, given considerations like the following, generated yaml was determined to be a reasonable compromise:
- automations being the heart of the platform so it doesn't feel right hiding them in .storage
- how much more readable they are in yaml vs json
- ease of being able to copy UI yaml into a package

**Comment by akonradi** [comment]
> What might be more feasible is to error after saving by checking that the newly written automation shows up when reparsing the config, and if not, providing an error message instructing users that they need to add that include.

That sounds like it should be doable, right? Shouldn't there already be some step to reload the automations when a new one is added, so that it can take effect? If, after that reload, the new automation is not present, it would indicate that the file wasn't being `!include`d.
