### ISSUE TITLE
Template Helper for Sensor shows incorrect list of Device Classes (in Dutch)

### ISSUE THREAD

**Issue by Madhondt** [home-assistant/frontend#17920]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Home Assistant **Dutch** version

When generating a sensor using the Template Helper, a Device Class can be selected using a drop-down list. In my case the list starts with English Device Classes, but after device class 'PM 2.5' it continues with Dutch Device Classes. Some Device Classes are missing, such as 'Power'.

![template_helper_list_device_class_1](https://github.com/home-assistant/frontend/assets/145016677/497b96da-c0c5-4215-b739-64a237c5fd14)

![template_helper_list_device_class_2](https://github.com/home-assistant/frontend/assets/145016677/cd78505f-8e57-424d-8b5e-9bec949fbac7)

### Describe the behavior you expected

Gettting the complete English list with all Device Classes

### Steps to reproduce the issue

1.Add Helper Template
2.Select 'Template a Sensor'
3.Select list 'Device class'
...

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Firefox 117.0.1 / Edge 115.0.1901.200

### Which operating system are you using to run this browser?

Windows 11 Home 22H2 / Windows 10 Enterprise 22H2

### Problem-relevant frontend configuration

```yaml
Home Assistant **Dutch** version
```

### Additional information

Home Assistant **Dutch** version

**Comment by silamon** [comment]
Since it's a new feature, not all device classes have been translated to Dutch. Those that have been translated appear in Dutch,  those who have not been translated appear in English for now. Power appears as "Stroom" since that one has been translated.
 
If you want, you can [contribute to the translations](https://developers.home-assistant.io/docs/translations/). Join the backend team and use this as a filter "component::template::selector::sensor_device_class" to find the untranslated device classes. Once translations are added, they'll be picked up with the next Home Assistant release.

**Comment by Madhondt** [comment]
Thanks for your prompt anwser and feedback!
Based on your answer I understand it is not really a bug, so I appologise for posting it here. However, the Dutch translation of 'power' was buggy: this is not 'stroom' but 'vermogen'. 'Stroom' is Dutch for 'current'. That  is why I couldn't find it ;-)

I have followed your instructions and have entered the Dutch translations for all component::template::selector::sensor_device_classes. Happy to contribute a very little bit in this way in this great product!
