### ISSUE TITLE
Broken functionality new climate entity dialogs W/ Xiaomi fan

### ISSUE THREAD

**Issue by iddiek** [home-assistant/frontend#17942]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Really love new climate interface but with this fan (Xiaomi) can't move it to right/left anymore because "direction", previously used as switch, was changed from buttons to select type.
Before update selecting buttons l/r there was 5° rotation  to left/right

### Describe the behavior you expected

Possibility to select same direction multiple times or input as a slider

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2013.9.2

**Comment by karwosts** [comment]
I'm having a hard time parsing what you're describing. Do you have a screenshot of the previous version and how you updated it, and a screenshot of what is not working for you currently?

**Comment by amurelk** [comment]
Two buttons is replaced with one button where is select. Now is not possible move. Now is selection button
![fiaomi__fan](https://github.com/home-assistant/frontend/assets/92201791/0ab573f9-643a-4ad0-a0f8-e6b161496b56)

**Comment by karwosts** [comment]
Ok I see now what you mean. Interesting, though I suspect that the Xiaomi fan was not using this feature as it was intended. It looks like "direction" is intended to only be two states, either forward or reverse (like the direction of airflow), not intended to be for the _orientation_ of the fan. 

If that's the case, I'm not sure if there will be any desire to revert back to how it used to be.

**Comment by karwosts** [comment]
Actually I'd be curious of two things:

- Does the fan report a `direction` attribute in developer tools?
- If you set it to forward, then close the more-info dialog and re-open it, are you able to select forward again a second time and have it move?

**Comment by iddiek** [comment]
Thanks for your reply.
Probably there was a misunderstood about the function, but 
as worked before there must be code for that function that we can use for implement two buttons.. can you point us to the right direction? Thanks

**Comment by karwosts** [comment]
The control you're referring to is here [more-info-fan.ts](https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/controls/more-info-fan.ts), but it is shared code for all fans across all integrations.

**Comment by iddiek** [comment]
> Actually I'd be curious of two things:
> 
> * Does the fan report a `direction` attribute in developer tools?
Direction:none
> * If you set it to forward, then close the more-info dialog and re-open it, are you able to select forward again a second time and have it move more?

Yep

**Comment by karwosts** [comment]
I think at least in theory this should be possible to update the frontend to make this work, though I'm not certain if it makes sense to do so. 

When you select "forward" or "reverse" in the dropdown, it seems like perhaps it could be made to reset back to unselected in a moment later since the state attribute `direction` did not change to match the requested setting. For now once you set "forward", the entity's state does not change, so the control never re-renders to reset from `forward` back to null/unselected. 

I think this would also work if instead of saying "none" for the fan entity, if it updated the direction attribute each time the service was called, then I think it would reset after each call. Maybe the entity could report the angle or something in direction, though I'm not sure if that's against the rules of the fan class. I think it would fix the control through.

**Comment by amurelk** [comment]
Today I control my dmaker.fan.p18 with Nodered. Nodered node for Xiaomi fan I got from here [https://github.com/stason325/node-red-contrib-miio-localdevices/blob/master/DEVICES.md](url)
