### ISSUE TITLE
Historical graph looping

### ISSUE THREAD

**Issue by mr2toyou** [home-assistant/frontend#18344]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When accessing a historical graph (show more - last week) and selecting a data point the graph will return to a previous view.  This started with 10.1 and I have tried every update since with the same results. 

### Describe the behavior you expected

Data point showing

### Steps to reproduce the issue

1.History
2.Show more
3.Select Date
4.Last week
5.Select a data point
...

### What version of Home Assistant Core has the issue?

10.1

### What was the last working version of Home Assistant Core?

9.3

### Additional information

OS 11.0, frontend 20230911.0, Supervisor 10.0

**Comment by mr2toyou** [comment]
https://github.com/home-assistant/frontend/assets/101832565/1cb036ac-9064-4f56-907b-639fe79a6a0a

**Comment by mr2toyou** [comment]
This has been resolved with core update 2023.11.2

**Comment by k3a** [comment]
If you want to inspect individual data points in the History section, you can tap and swipe the finger over those data points to see the tooltip. Is that problematic?

**Comment by mr2toyou** [comment]
The issue #18198 I experience that as well with the HVAC history graph, what I am seeing is a little different where select a data point will loop back to the originating screen.. previously I could select any data point and the tool tip would show.  Re-uploading screen capture of the issue..

**Comment by mr2toyou** [comment]
https://github.com/home-assistant/frontend/assets/101832565/7d193c32-c39c-4d08-8eab-e1d39bbab0f9

**Comment by k3a** [comment]
I understand that loop and it is unnecessary in this context. But you should be able to prevent opening More Info dialog again by simply tapping on the point (as you do) but not releasing the finger and instead moving it to the next data point. You should be able to display tooltips for all points this way, by tap and move. Does that not work for you?

**Comment by mr2toyou** [comment]
yes the tap and swipe will display information without looping, that is not historically how the graphs would function.  It can be challenging to select and swipe to the data point you are actually trying to look at.

**Comment by k3a** [comment]
Of course it is not as it used to be because it is a new feature. I don't see a problem in that. Previously, you would hardly tap on the exact point at the first try either. The only difference is:

- previously you would just tap and release and the popup will stay. If you missed it, you would tap and move or tap again.

+ now, you tap and hold the finger. If this is wrong point, you just move the finger. Tooltip will stay if you release your finger after moving it slighly. If you just tap and release you will get More Info. More Info is useful in other contexts, especially for timeline history chart with 6+h history display where for example door sensor changes are hard to read. Now you would tap on it and see all events nicely in More Info.

The main reason behind this feature was timeline history chart and a click on it to open More Info. But for me it made sense to do that for graph charts as well to keep it consistent. I don't see this change as problematic in any way, even in your use case. But if more people don't like this, maybe we could set up some poll. Because you know, one person likes something the other one dislikes it.

**Comment by mr2toyou** [comment]
I do understand there are situations and context that I am not using that others might.  Can you help explain the default timeline history graph interaction vs selecting any other time/date range. It appears they do function differently

**Comment by mr2toyou** [comment]
Adding another example

**Comment by k3a** [comment]
I mean timeline chart like this. It is 12h. Door opens are barely visible (some have Closed label but some don't).
<img width="489" alt="Screenshot 2023-12-15 at 21 40 57" src="https://github.com/home-assistant/frontend/assets/966992/b0226958-82a5-4060-a96c-7a65d7b312a7">

Now with this new functionality I can click on a door sensor and I see a nice history with "... ago" texts for every change.
<img width="580" alt="Screenshot 2023-12-15 at 21 43 08" src="https://github.com/home-assistant/frontend/assets/966992/4bcd915e-20ba-4742-9054-0d99a493ac0b">

And I thought it is a pity that there was no action for clicking on a chart so it made sense to add it.
But it is true that while it seem like no brainer on destko it is a bit more complicated on touch devices because they don't have hover like mouse hover for those tooltips. But I still think tap and hold should be sufficient, or at least it is sufficient for me when I want to see a tooltip on mobile.

But different people have different opinions and usages so as I said, maybe some poll would be sensible to make or maybe it could be made configurable.

**Comment by mr2toyou** [comment]
https://github.com/home-assistant/frontend/assets/101832565/aac29351-1891-4c74-a75e-629dea01a698

**Comment by k3a** [comment]
so you can't tap and hold (or tap and move) in that History chart shown on 0:13 of the recorded video?

**Comment by mr2toyou** [comment]
Yes I can tap/hold swipe.. why is there a functionality difference when a date range is selected outside of the default?.. the first part of the video is just taps

**Comment by k3a** [comment]
ah this - because it is disabled. It was evident soon that it would loop, i.e. clicking on the chart in More Info would immediately display More Info again so it was disabled for charts in More info. By default it is enabled on all charts but it can be disabled in some contexts.

As for this History section, maybe it would be possible to disable that there too. But I don't have the source code at hand to inspect and don't have more time today. But I will look into it when I have time and let you know. It may be on Monday though, will see.

**Comment by mr2toyou** [comment]
Thank you for looking into this.  Really appreciate the time and effort you have contributed to HA.

**Comment by k3a** [comment]
Sorry for taking so long to respond. I had to re-create the dev environment and it is a painful procedure.

So yes - it can definitely be disabled for History section (page).

I think it sounds sensible because at that time the user often knows the entity, it is filtered there and there is little need for More Info dialog at that point. It would be helpful to have feedback from more people though. I also asked in the another similar issue (18784). I would like to avoid the situation where after this commit an another issue would appear that "History is broken now as it doesn't respond to a tap or click". :D

**Comment by mr2toyou** [comment]
Sorry for the delay, holidays where crazy this year.  I think the (i) info button will be a value added option for mobile users.  Thank you again for working/ investigating this issue.

**Comment by karwosts** [comment]
As of https://github.com/home-assistant/frontend/pull/19606, graph touches on mobile no longer activate the more-info window, that's now a mouse feature only.

I believe that resolves the concern with this issue.

**Comment by karwosts** [comment]
The only fix was that touches on mobile no longer open more-info. And that should have been released for 2 months now. 

Are you expecting some other behavior?

**Comment by ryamoo** [comment]
@karwosts exactly that, if I tap a point in the history graph, it opens more info. 
I go to the history dashboard (or get there by tapping "view more",  load up a graph for temperature, tap a point, and the tooltip  displays but I'm immediately taken to the graph showing the last day with the "view more" link. I tap tap view more, load a history graph again, and tap a point and repeat.. 

At some point in this video I tap and hold (and you can see the text selection ui briefly flickers in, which is why I don't like to tap and hold), but the rest are just normal single taps. 

https://github.com/home-assistant/frontend/assets/13999873/bc9ae3b0-fc84-4be9-8eb8-adf5b44047e7

 I'm currently on core 2024.3.0 and frontend 20240306.0
![IMG_8933](https://github.com/home-assistant/frontend/assets/13999873/13ad5c75-2365-4a0c-8f79-d277d33d5a28)

**Comment by karwosts** [comment]
Hmm strange. I'm on 2024.2 and I can't open more-info from my mobile app. 

My only thought is maybe try making sure to clear your app's cache, sometimes it holds old versions of frontend elements until the cache is cleared.

**Comment by ryamoo** [comment]
@karwosts i thought if that, but ios doesn't let us clear cache. So I tried chrome, and it's the same there. I've also tried chrome incognito, and safari (which I never use), just in case chrome had something cached, and it's the same behavior on those too. 

Any chance the fix was pulled? Or you're on a bugfix branch or something that includes it?

**Comment by k3a** [comment]
It was fixed by this commit https://github.com/home-assistant/frontend/commit/fb73bfb96402b1f03bcf8c09251c3b34195c0982 

And in the commit header (after you click on the commit hash on github webui) you can see tags which include the commit: [20240307.0](https://github.com/home-assistant/frontend/releases/tag/20240307.0)  [20240306.0](https://github.com/home-assistant/frontend/releases/tag/20240306.0) [20240304.0](https://github.com/home-assistant/frontend/releases/tag/20240304.0) [20240301.0](https://github.com/home-assistant/frontend/releases/tag/20240301.0) [20240228.1](https://github.com/home-assistant/frontend/releases/tag/20240228.1) [20240228.0](https://github.com/home-assistant/frontend/releases/tag/20240228.0) [20240207.1](https://github.com/home-assistant/frontend/releases/tag/20240207.1) [20240207.0](https://github.com/home-assistant/frontend/releases/tag/20240207.0) [20240205.0](https://github.com/home-assistant/frontend/releases/tag/20240205.0) [20240202.0](https://github.com/home-assistant/frontend/releases/tag/20240202.0)

**Comment by ryamoo** [comment]
That is strange! 
Any chance it works different on iOS versus android? 
I've got an android around here somewhere, I'll dig it out and see if it's any different on there.

**Comment by ryamoo** [comment]
Yeah - seems to be an ios thing. 

I've just tried on Chrome on my OnePlus 9 Pro, and tapping a point on the history graph just displays the tool tip, it doesn't take me to the more info view. 

I've tried it on Safari and Chrome on my iPad, and it's the same as my iPhone, the tool tip appears but then the more info view immediately pops up.

**Comment by karwosts** [comment]
If you find it's still a problem on iOS, feel free to open a new issue describing that. Perhaps the logic that was written to discern touch vs mouse doesn't work the same way there.
