### ISSUE TITLE
"Triggered by" in automation editor is not translated to Polish despite being translated in Localise

### ISSUE THREAD

**Issue by Maaaciek1** [home-assistant/frontend#18406]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The entry "Triggered by" isn't translated to Polish in Home Asistant automation editor despite being translated in Localise since February 2022. 
https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?k=98787193 - link to the entry.

### Describe the behavior you expected

The entry should be translated.

### Steps to reproduce the issue

1. Go into automation edit while having Polish set as a language
2. See it is not translated

### What version of Home Assistant Core has the issue?

2023.10.5

### In which browser are you experiencing the issue with?

Google Chrome 118.0.5993.89

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Can you include screenshot showing the specific element you're referring to?

**Comment by srozb** [comment]
I'm also using polish language in the home-assistant and have very similiar issue.

When creating an automation in Home Assistant's web frontend, the entity states are automatically localized. For instance, instead of the word "on" the user may see a localized shortcut like
"wł." (which stands for "włączony" in Polish). This can cause issues when using the web frontend to edit automations in languages other than English, as the expected entity state name will not be recognized.

Easy workaround is to switch to yaml and manually change "wł." to "on".

<img width="744" alt="image" src="https://github.com/home-assistant/frontend/assets/16724544/9c5437f1-6234-4158-bd2f-9261c22d3200">

has to be changed to english word for automation to trigger properly:

<img width="458" alt="image" src="https://github.com/home-assistant/frontend/assets/16724544/7b1f72b0-64a9-4b2b-aba4-03e93a838526">

**Comment by karwosts** [comment]
Proposed fix in #18488.

@srozb - I don't quite understand what issue you have, but it does not seem similar or related to me. Yes the UI translates some entity states, that's not a bug.
