### ISSUE TITLE
Sliders (and maybe more) are missing on-primary styling

### ISSUE THREAD

**Issue by KTibow** [home-assistant/frontend#18697]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

`ha-slider` has no `on-primary` styling
![image](https://github.com/home-assistant/frontend/assets/10727862/13fcd783-9665-40ea-a178-c377c26ecaf9)
this makes it look bad when the primary color isn't dark

### Describe the behavior you expected

it should set `on-primary` to `--text-primary-color`

### Steps to reproduce the issue

go to a more info of a media player with a volume slider or anywhere else with a slider. observe styles.

### What version of Home Assistant Core has the issue?

2023.11.1

**Comment by silamon** [comment]
We need to come up with a default theme and some research should happen for material design 3. Unfortunately, it's not easy to pick this up, since the package isn't complete as of now and the codebase is large. I'm not sure right now, if we should continue to adopt this given that there's still many issues with it next to not being complete. I will open a PR if you don't plan to fix this, so this one gets fixed.

**Comment by KTibow** [comment]
confirmed still present on https://demo.home-assistant.io
