### ISSUE TITLE
Temperature problem below 0°C

### ISSUE THREAD

**Issue by LatchyRed** [home-assistant/frontend#18855]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello, temperature rise below 0°C problem with OVERKIZ via Connexoon
![1](https://github.com/home-assistant/frontend/assets/62942235/0c90aa40-e212-43a5-b49a-aeaccb13d877)
![2](https://github.com/home-assistant/frontend/assets/62942235/e7819dd4-7816-4faa-84ce-0092f5ffcb99)

### Describe the behavior you expected

Display temperature below 0°C

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2023.11.3

**Comment by ildar170975** [comment]
@LatchyRed 
Are you saying that a graph in HA on your 1st screen is wrong - since the temperature was below 0 according to your mobile app for this device?
1. The 1st graph seems to be a statistics graph from more-info. Statistics is not as precise as History. You should have checked a History for this sensor.
2. The mobile app may show data based on it's OWN readings from the device. Assume the app shows data polled every 10 sec - and HA integration for this device is polling data every 1 minute, so these 0 readings may be not read by HA.

**Comment by ildar170975** [comment]
> HA sets unknown temperature.

The this may be an issue with a corresponding integration. Not a frontend issue.

**Comment by LatchyRed** [comment]
Yes, certainly

**Comment by karwosts** [comment]
Please open this in home-assistant/core. Not a frontend issue.
