### ISSUE TITLE
Negative solar production in energy dashboard after no production for a period of long time

### ISSUE THREAD

**Issue by doe81** [home-assistant/frontend#19073]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have my solar production added to the energy dashboard.
![image](https://github.com/home-assistant/frontend/assets/80957589/277a99b0-2f34-42b0-a1e9-54e9cf110881)
The panels were covered with snow for several days/week(s) and did not produce any energy.
Yesterday they produced some energy, but the energy dashboard showed a negative production even though the values increased since the last update. 
![image](https://github.com/home-assistant/frontend/assets/80957589/09c5e2d7-8e91-4c8a-93a0-96d327b70b67)
![image](https://github.com/home-assistant/frontend/assets/80957589/505682ae-2874-4225-b9d5-6fd3ba163d69)
![image](https://github.com/home-assistant/frontend/assets/80957589/77c71a9a-2ea0-493d-9f6c-fad0fe52f465)
Could this be related to the long gap between the last production and the current one, so that some history/data was lost?

### Describe the behavior you expected

It should just show the production. It works as expected again after the large negative entry.
This is from today: 
![image](https://github.com/home-assistant/frontend/assets/80957589/9968bfd4-e13b-4c0c-bd0e-6aa38cab47ce)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

Edge 120.0.2210.77

### Which operating system are you using to run this browser?

Windows 11 Version: 10.0.22631 Build:22631

### State of relevant entities

```txt
State: 11195.7

state_class: total
device_id: RPHECM701C
Data Source: raw_mqtt_sensors
unit_of_measurement: kWh
device_class: energy
icon: mdi:solar-power
friendly_name: RPHECM701C Power Generation - Total (pvenergytotal)
```

**Comment by karwosts** [comment]
This is due to a bad value in your statistics database, this happens to me too sometimes on occasion. Something to do with HA restarts after long period of sensor inactivity. 

Anyway you can mitigate it in developer-tools/statistics by locating the bad databpoint and adjusting it to 0.

But as this flows from a bad value in the statistics table, it is not an issue that can be fixed in the frontend. 

If you want to pursue an actual fix (instead of just mitigating it), suggest opening an issue in home-assistant/core, which is reponsible for recording these values.
