### ISSUE TITLE
Energy dashboard in :30 minute time zone incorrect

### ISSUE THREAD

**Issue by bindismal** [home-assistant/frontend#19082]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am in a time zone that doesn’t fall on a whole hour. The time zone falls on a half hour boundary.
All of the buckets in the energy dashboard show the energy used between x:30 and x+1:30 rather than x:00 to x+1:00. I think this is likely a bug caused by the 30 minute time zone that is configured on the host.

### Describe the behavior you expected

Described above already.

### Steps to reproduce the issue

1. Set hass to to x:30 (eg +9:30)
2. Set up hass to recieve energy usage information
3. View energy dashboard
4. Hover mouse over energy chart 
...

### What version of Home Assistant Core has the issue?

2023.12.3

### Which operating system are you using to run this browser?

iOS 17.2

**Comment by Namdrib** [comment]
I'm also running into this issue. In addition to this, because the energy import and export values are reset between 2330 and 0030, there is a huge spike at the end of the day, effectively doubling the import and export for the day. Notice that the values of the spike are approximately half of the day's import and export.
![image](https://github.com/home-assistant/frontend/assets/9072806/50ab93b9-d9e8-4b60-9d41-fbcad667829b)

This is on Home Assistant Core 2024.2.2 (Docker), rendered on Firefox 123.0. The same is true on Android 2024.1.5-full.

**Comment by bindismal** [comment]
This is still a current issue.

**Comment by conformist66** [comment]
This issue would apply to all of the zones with 30 minute offsets including parts of Australia, India, Canada, Sri Lanka and so on.
There are also a small number of zones with 15 minute offsets so maybe this should be considered too??.  
https://www.timeanddate.com/time/time-zones-interesting.html

**Comment by Namdrib** [comment]
This seems to be resolved as of:
Core 2024.10.0
Frontend 20241002.2
![Screenshot_20241105-110328](https://github.com/user-attachments/assets/4c2338f7-4104-4766-ae56-edf977550e96)

**Comment by WillBishop** [comment]
This is not resolved.

**Comment by bindismal** [comment]
> This is not resolved.

Agreed.
