### ISSUE TITLE
History Graph Card not showing entities if they have been constant for too long

### ISSUE THREAD

**Issue by darrenfreeman** [home-assistant/frontend#19139]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a few History Graph Cards configured to display temperature sensors, along with the high and low setpoints. The setpoints are number helpers.

Today, I found that a number of these graphs are no longer displaying the setpoints. They are not mentioned in the legend, it's like they aren't listed anymore in the YAML, but they are.

When I look at the state history, there is none. I guess it's been purged, as there have been no changes for a while.

The helpers themselves appear to be healthy, and when I change the values, they reappear on the charts, missing the old values.

### Describe the behavior you expected

I mostly expect to see horizontal lines for the temperature setpoints. But sometimes, when I change the setpoints, I expect to see a chart of those changes.

### Steps to reproduce the issue

1. create a number helper, and set a known value
2. leave it unchanged for a long time
3. confirm there is no state history
4. add the helper to a History Graph Card

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

Chromium Version 119.0.6045.199 (Official Build) snap (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 23.10

### State of relevant entities

```txt
input_number.fridge_temp_warn_max
Fridge Maximum Temperature, Warning Issued
5.0	initial: null
editable: true
min: -20
max: 20
step: 0.5
mode: box
unit_of_measurement: °C
icon: mdi:thermometer-high
friendly_name: Fridge Maximum Temperature, Warning Issued
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: input_number.fridge_temp_warn_max
    name: Warn Max
  - entity: input_number.fridge_temp_warn_min
    name: Warn Min
  - entity: sensor.fridge_temperature
    name: Fridge
title: Fridge
```

**Comment by darrenfreeman** [comment]
After updating HA core to the latest, I see the helpers have appeared again, as if I had just changed their values. The graph starts at the present time, the prior history is not shown. I assume the issue is affected by the time since last restart.

**Comment by ildar170975** [comment]
Here is a number which was set a long time ago.
There is History displayed.

![image](https://github.com/home-assistant/frontend/assets/71872483/38682ba2-b381-4f59-938f-05b1e5fbd164)

![image](https://github.com/home-assistant/frontend/assets/71872483/f2473853-88d2-4513-89a5-edfac366c5bf)

**Comment by karwosts** [comment]
This happens when there are no datapoints for your entity in the states table. It can happen if it is unchanged for long enough that the last state change got purged if its older than the recorder keep_days. Also restarting HA will write a state either at shutdown or startup (not sure which), so anytime you restart the system you won't see the problem.

You can simulate a similar effect by running recorder.purge_entities. After you purge an entity it it won't be graphed again until it changes or until you restart.

**Comment by ildar170975** [comment]
> so anytime you restart the system you won't see the problem for another ~10 days.

This explains my case because I usually restart HA < 10 days.

> This happens when there are no datapoints for your entity in the states table. It can happen if it is unchanged for long enough that the last state change got purged if its older than the recorder keep_days

Results could be confusing.
I just recall that same behaviour was already reported:
[history-graph: reporting "no history" when entity was not changed](https://github.com/home-assistant/frontend/discussions/17479)
Totally forgot about it.

Similar issues:
[Logbook does not show a state for a newly created sensor](https://github.com/home-assistant/core/issues/104056)
[Map card: shows an incomplete track for a period](https://github.com/home-assistant/frontend/issues/18768)

**Comment by darrenfreeman** [comment]
Perhaps the purge can always leave the most recent state in the table?

**Comment by karwosts** [comment]
> Perhaps the purge can always leave the most recent state in the table?

Might be a cool idea to consider someday, but that's far outside the scope of a frontend issue. 


Even when the recorder is empty for an entity, we do have a little bit of data we can use in the entity state object, which has the current state, and a last_changed timestamp. So in theory we could maybe leverage that data to make a limited display for the history graph, which would be better than displaying nothing.
