### ISSUE TITLE
User Agent override when using mobile app ?

### ISSUE THREAD

**Issue by titiviking** [home-assistant/frontend#19374]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Please refer to https://github.com/home-assistant/android/issues/4116

### Describe the behavior you expected

Consistent user agent for requests that originate from the android app

### Steps to reproduce the issue

Monitor requests issued by Android app and look at UA values

### What version of Home Assistant Core has the issue?

2024.1

**Comment by steverep** [comment]
AFAIK, the frontend only specifies a `User-Agent` header as "Home Assistant" when fetching map data from Open Street Maps.  Otherwise it will be whatever the browser sets unless it's overridden elsewhere (e.g. by the mobile apps).

In the Android issue you mention that it only happens when fetching `/api/calendars/`?  Or is that just one example?

**Comment by titiviking** [comment]
Just one example I'm aware off...
When looking at the Cloudflare events, all /api/... seem to use the "Home Assistant" user agent when originating from the android app. Calendars seem to use another UA, while still being sent from the same app...

**Comment by steverep** [comment]
> Just one example I'm aware off... When looking at the Cloudflare events, all /api/... seem to use the "Home Assistant" user agent when originating from the android app. Calendars seem to use another UA, while still being sent from the same app...

Is the protocol the same between the calendar and others?

At least for the frontend, I'm inclined to close this because the frontend does not (and should not) modify the UA when doing raw fetches.  As I said the only current exception is fetching from Open Street Maps, but I believe that's just so they can white list on their end.  @bramkragten can you confirm?

**Comment by mckennajp** [comment]
I am seeing this as well with Android app.  When viewing `Settings -> Devices & services` the tabs `Devices`, `Entities`, and `Helpers` retrieve data using a different user agent.  For example, the path `/frontend_latest/sort-filter-worker.47BKuNgJVxI.js` has the user agent set to `Mozilla/5.0 (Linux; Android 14; SM-S911U1 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.39 Mobile Safari/537.36` when it should be something like `Home Assistant/2024.10.3-14058 (Android 14; SM-S911U1)`.
