### ISSUE TITLE
Confusing dutch translation in tooltip of calendar time-ago field "Laatst gewijzigd", "Laatst bijgewerkt"

### ISSUE THREAD

**Issue by GrumpyMeow** [home-assistant/frontend#19383]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I understand what is being meant, but it's a little bit ambigous.
In tooltip:
```
Laatst gewijzigd: 1 uur geleden
Laatst bijgewerkt: 1 uur geleden
```

### Describe the behavior you expected

I don't know exactly what i expect, but this is slightly confusing. Because in the dialog time-ago field also "1 uur geleden" is displayed. But when hovering over the time-ago field two times are displayed. 
I think i would choose either to not display the "1 uur bijgewerkt" text in the tooltip as it's technical information which HASS should only display if it's really needed.

### Steps to reproduce the issue

1. Hover over the time-ago field

### What version of Home Assistant Core has the issue?

core-2024.1.3

### In which browser are you experiencing the issue with?

Version 119.0.6045.159 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Nixos 23.05beta-356385.gfedcba (Stoat) (KDE-desktop)

**Comment by karwosts** [comment]
If your issue is specifically with the dutch translation of the english string, then you would take that to lokalize and suggest a change there if you want a different translation.

If you simply don't agree the way the UI is presenting information (regardless of the language), than I would suggest to change your comment to fully english and not mention translations, otherwise I expect it might get closed, since typically we don't handle "translation" issues here. 

But it sounds like your concern might be the latter, so I will leave this open for the moment, as I'm not quite sure.
