### ISSUE TITLE
Carbon consumed gauge reports 100 % for curretn quarter and current year instead of real value (84% in my case)

### ISSUE THREAD

**Issue by Alfred99-HA** [home-assistant/frontend#19399]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Problem occur in Carbon consumed gauge card in energy dashboard https://www.home-assistant.io/dashboards/energy.
Problem reproduced with firefox and chrome.
Actually current periods week / month show values which seem reasonable to me - actually around 85 %
both current quarter and current year however show 100 %

### Describe the behavior you expected

Incomplete quarter and incomplete year should show the same value as the incomplete month January - actually around 85 %.
See screenshots for all mentioned periods.

### Steps to reproduce the issue

1.Select week / month / quarter / year 
2.
3.
...
![low carbon week 20240114-20120120](https://github.com/home-assistant/frontend/assets/133593172/43176aaf-3f16-4481-9f8e-292ca18b8796)
![low carbon month 202401](https://github.com/home-assistant/frontend/assets/133593172/e4f4ea2b-e3c4-418e-96fc-f4df203fe15e)
![low carbon quarter 202401-03](https://github.com/home-assistant/frontend/assets/133593172/4d8bb9fd-8b81-4456-92df-65f15518bc79)
![low carbon year 2024](https://github.com/home-assistant/frontend/assets/133593172/b27a61f4-158c-4363-a832-e93a4b7f9f34)

### What version of Home Assistant Core has the issue?

2024.1.3

### In which browser are you experiencing the issue with?

Chrome 120.0.6099.217 

### Which operating system are you using to run this browser?

 x86-64 Using Live OS 11.4

**Comment by ThePatricide** [comment]
Maybe my issue is related (otherwise, please let me know and I'll submit a separate issue):
For January '24, my low-carbon energy consumption is 56%:
![image](https://github.com/home-assistant/frontend/assets/15046966/79fbe0c7-18a8-4e60-b144-74efe631216a)

However, if I look at the total of 2024, it is reported 100% and you can see that the low carbon energy consumption now equals the total consumption (falsely of course):
![image](https://github.com/home-assistant/frontend/assets/15046966/a816402e-5be1-48c3-b52b-ef3d71347504)

Mind you I had a little interruption in the dashboard data this month due to reconfiguration of my DSMR integration, because I noted it had changed all names of the sensors. I first changed it to the new ones in the energy dashboard settings, but later reverted to the old names and renamed all new sensor names to the old ones (all manually).

**Comment by Alfred99-HA** [comment]
Actually I am pretty sure, I did not change any names of relevant entities during the last thee weeks - and the problem occours with 1. month and 1. quarter which should equal (and year should be equal as well).
Thanks for taking this issue in your pipe to consider.
