### ISSUE TITLE
Removed storage still appears in Media-My Media

### ISSUE THREAD

**Issue by sycorax** [home-assistant/frontend#19968]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I had a Network storage drive added in /config/storage and removed it. Then I added another one. When I go Media-My Media that deleted drive still appears.

### Describe the behavior you expected

When I go Media-My Media the deleted drive should not appear.

### Steps to reproduce the issue

1. Add a Samba Network share in /config/storage
2. Reboot machine
3. Remove the network share from /config/storage
4. Add a different Samba Network share in /config/storage
5. Go to Media-My Media and see both shares

### What version of Home Assistant Core has the issue?

2024.2.5

### Which operating system are you using to run this browser?

Win11_64

**Comment by karwosts** [comment]
I think this would probably have to be a home-assistant/core issue, frontend doesn't know about any of this filesystem stuff on its own, it just asks core for a list of the users media sources and displays what returns. So if it's getting something back in that response that doesn't belong, that would need to be fixed in core.
