### ISSUE TITLE
more_info light sliders inconsistently working

### ISSUE THREAD

**Issue by aegjoyce** [home-assistant/frontend#20080]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The light sliders in the more_info box don't slide with your finger under certain conditions:

Affects iOS app and iOS safari only - works as expected in MacOS safari
Seems to affect certain types of bulbs only - for me, only affects Hue and IKEA bulbs connected in Z2M
My Z-wave bulbs, and light groups (including light groups containing the Z2M bulbs above) are unaffected
Happens both in dashboard and when viewing entity through entities list in developer tools

As seen in the video, I try three times to slide up from the bottom of the slider but it immediately bounces back to 0%. I then tap on the slider and it jumps to the brightness I tapped (68%). Further attempts at sliding from here result in the same behaviour of bouncing back.

https://github.com/home-assistant/frontend/assets/47081267/d2acc723-159b-482b-abc5-4daba8da6b85

Interestingly, if I use a Tile card with a brightness slider for the same entity, this works fine:

https://github.com/home-assistant/frontend/assets/47081267/62a36af3-ba1f-49f9-a0de-dbe8e219cf6f

### Describe the behavior you expected

Expect smooth sliding of the light slider to follow

### Steps to reproduce the issue

As described above

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

iOS app 2024.561, iOS safari

### Which operating system are you using to run this browser?

iOS 17.4

**Comment by lbr-dev** [comment]
Same here :(
Any update or temporally fix? It bugs me for over a month 

https://github.com/home-assistant/frontend/assets/49651393/7058962a-9477-41cd-8364-c704f8927a52

**Comment by mattiasa** [comment]
I've been looking into this (after family members started asking me why they can't set the light temperatures anymore after their phones updated)

This appears to have changed between iOS 17.2 and 17.4 as can be seen with the Bar lamp light on demo.home-assistant.io using the iPhone simulator in XCode. In this video I'm testing with 3 different iPhones, two normal sized screens (iPhone 15) running 17.2 and 17.4 and one 15 Pro Max running 17.4. The 17.2 works as expected when sliding, as does the Max running 17.4 (most likely because of the larger screen fitting the entire more_info box as @antonio1475 pointed out). The iPhone 15 running 17.4 however shows erratic scrolling behaviour.

https://github.com/home-assistant/frontend/assets/1186119/ba6a9964-ff7d-4d6e-b280-e5ef48f6e4df

If I attach a debugger to the simulator I can see that the slider's container element on the working phones get a state of "pressed" while sliding but on the non-working one it just briefly flashes. This is about where my ability to work with and debug React applications comes to an end so I don't really know why we're seeing this difference in behaviour. I'm happy to help debug this further however with some guidance.

![Screenshot 2024-04-15 at 01 10 05](https://github.com/home-assistant/frontend/assets/1186119/135a2f1e-f257-49ba-bfd4-cb7b9543a5e1)

**Comment by illiteratealliterator** [comment]
I setup Home Assistant last week and I was very surprised/disappointed to see something as widely used as this work so badly. I'm relieved to see it's a recent iOS-only bug! That said, it's the only thing really holding me up getting my family to install the app rather than use Apple Home.

I'm on an iPhone 11 and I see the problem with every bulb. Nice diagnostic work @mattiasa, hopefully we can get a dev to take a look at this soon?

**Comment by piitaya** [comment]
Looks like it's a regression on Safari on iOS. I open a PR to fix the issue on Home Assistant side but I need to look deeper if it's really a webkit issue.
