### ISSUE TITLE
ZHA Visualization showing disabled devices

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20717]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

ZHA Visualization map is showing disabled devices, which I'm like 95% sure never happened before. I think it's a regression from the recent improvements in https://github.com/home-assistant/frontend/pull/20511 , or perhaps the colors just made it easier to spot.  Either way, behavior seems wrong?

Noticed this with a temperature sensor that accidentally got thrown out in recent kitchen remodel. I disabled it and you can see from the screenshot below it's disabled and last seen Sept 13. It doesn't show up as selectable in the "Zoom to device" dropdown (expected behavior), but appears on the map (unexpected behavior). 

![IMG_0564](https://github.com/home-assistant/frontend/assets/9065557/e50ab793-563d-45e5-859a-71b134426ec6)

![IMG_0565](https://github.com/home-assistant/frontend/assets/9065557/f33a8836-ab68-4788-ac6b-be4ac8613056)

### Describe the behavior you expected

Don't show disabled devices

### Steps to reproduce the issue

1. Disable a device belonging to ZHA integration
2. Open ZHA Visualization
3. See disabled device

### What version of Home Assistant Core has the issue?

2024.5

### In which browser are you experiencing the issue with?

iOS app

### Which operating system are you using to run this browser?

iOS 17.4.1

**Comment by puddly** [comment]
Devices disabled in Home Assistant may still be on your mesh and act as parent routers so I don't think this is incorrect behavior.

**Comment by SeanPM5** [comment]
Ok, that makes sense. Thanks.

**Comment by lubosz** [comment]
@puddly So what is with devices that have been powered down and put in a box? I have disabled them, but they are still floating as disconnected nodes in the graph. They have the same visualization as devices that are still in place but powered down lights due to a wall switch or disconnected due to interference.

Should I delete the unused devices or write a patch to ZHA map that hides disabled devices? I would actually like to keep track which devices I have in my box.

Does the mesh network still try to find these powered down and disabled devices, so I should really delete them and rebind when needed?

**Comment by puddly** [comment]
It would be best to differentiate between online, disabled, and unavailable devices in the visualization.

As for differences, I will have to check. We do disable polling for disabled entities but I'm not sure if that's done if the entire device is disabled.
