### ISSUE TITLE
Can not set device_class to none on UI binary template

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21123]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title, creating a new Helper template binary

<img width="635" alt="Scherm­afbeelding 2024-06-21 om 11 55 21" src="https://github.com/home-assistant/frontend/assets/33354141/997ed696-8bc1-4cd5-8611-db5c19c84345">

then check the config options in the more info reveals:

<img width="630" alt="Scherm­afbeelding 2024-06-21 om 11 44 53" src="https://github.com/home-assistant/frontend/assets/33354141/10336f19-20ef-4c2d-9131-277389fe667f">

but we can not select the None as displayed on:

https://www.home-assistant.io/integrations/binary_sensor/#device-class

which is the only possible option  to show those icons And the correct state

### Describe the behavior you expected

be able to select None

I did try to click the X in that Show_as dropdown, and save. It returns to the Active device_class though

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.3

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Mac OS

### State of relevant entities

see screenshot

### Additional information

Note the icon in the preview on the UI is correct below the template field, and how that differs from the one in the show as line

Note there also is an odd separator line, that probably shoulknt be there

**Comment by Mariusthvdb** [comment]
made a second one:

<img width="1165" alt="Scherm­afbeelding 2024-06-21 om 12 01 57" src="https://github.com/home-assistant/frontend/assets/33354141/54063532-9470-4bcc-880d-1a934df9799d">

and that does show alright. checking the entity_registry on those reveals something interesting:

```
{"aliases":[],"area_id":null,"categories":{},"capabilities":null,"config_entry_id":"c81b18ff91b463722f311755b7c13f6d","device_class":null,"device_id":null,"disabled_by":null,"entity_category":null,"entity_id":"binary_sensor.donker_thema_2","hidden_by":null,"icon":null,"id":"8fed530249c0e3efe9f8afa346ff2a9f","has_entity_name":false,"labels":[],"name":null,"options":{"cloud.google_assistant":{"should_expose":false},"conversation":{"should_expose":false}},"original_device_class":null,"original_icon":null,"original_name":"Donker thema","platform":"template","supported_features":0,"translation_key":null,"unique_id":"c81b18ff91b463722f311755b7c13f6d","previous_unique_id":null,"unit_of_measurement":null}
```

has device_class seen to null, while the first try has:

{"aliases":[],"area_id":null,"categories":{},"capabilities":null,"config_entry_id":"6b66880d8b2992b11a731f176d96997a","device_class":"","device_id":null,"disabled_by":null,"entity_category":null,"entity_id":"binary_sensor.donker_thema","hidden_by":null,"icon":null,"id":"9ba19e6d01b96ae70c7fb6d89adc9b89","has_entity_name":false,"labels":[],"name":null,"options":{"cloud.google_assistant":{"should_expose":false},"conversation":{"should_expose":false}},"original_device_class":"running","original_icon":null,"original_name":"Donker thema","platform":"template","supported_features":0,"translation_key":null,"unique_id":"6b66880d8b2992b11a731f176d96997a","previous_unique_id":null,"unit_of_measurement":null}

device_class set to "".

**Comment by karwosts** [comment]
I don't think there's anything that can be done from the frontend. 

No matter what is sent in the `config/entity_registry/update` API for device_class, core will always revert back to the entity's original_device_class if we request a nullish value for device_class. That logic in the entity registry would need to be changed.

**Comment by Mariusthvdb** [comment]
but... are you saying now that if we dont set a device_class (I did not do that), it would set it to active? Because that is what happened and really shouldnt.


And, as Ive found, the X does not do anything in this case, while it should really unset any choice previously set?

**Comment by karwosts** [comment]
No I'm not saying that. 

Entity registry has two fields: `original_device_class` and `device_class`. 

`original_device_class` is set by the integration. In the case of the template binary sensor, it is set by the choice made in the config flow when the entity was first created. This can't be changed after creation. 

`device_class` can be set by user picking a value in the show_as field. This can be changed at any time. 

Even after changing `device_class`, the `original_device_class` always remains its original value. The device class attribute for an entity is defined as: if `device_class` has a value, use that, else use `original_device_class`. 

This means when you clear the device_class/show_as field in the registry settings, the device class attribute reverts back to `original_device_class`. 

If clearing device_class field sets your entity to `Active` device_class, than I believe that would have been the value selected at entity creation, and that must be the value of `original_device_class`. You can check this in your entity registry entries that you posted. If you claim you didn't set that, I would ask you to try one more time to make sure, since if I do:

* create a template binary_sensor
* leave the device_class blank,
* and then assign a show_as class, 
* and then clear the show_as class...

it reverts back to no device class as expected.

**Comment by ChristophCaina** [comment]
not sure, if I understand it correct - but:
If it is about a binary_sensor template - then, where should "original_device_class" come from?

I would expect to be able to set "none" when I create the template... or not?
![image](https://github.com/home-assistant/frontend/assets/26391061/ed4655fb-a7be-4f7d-b73f-756b502872a4)

**Comment by hmmbob** [comment]
This is also happening to `ping` binary sensors.  I'd very much would like to be able to override the device class also to `none`, instead of the default 'connectivity'.

Fun fact: an older ping sensor I have shows perfectly fine as "none" (reverting to default device class`none` ), while a newer one cannot be set to `none`.

`none` is supposed to be a supported device class though:
![image](https://github.com/home-assistant/frontend/assets/33529490/943a0814-9cc0-4292-b180-43a238445bc3)
https://www.home-assistant.io/integrations/binary_sensor/#device-class

The one ping sensor that has `none` as device class:
![image](https://github.com/home-assistant/frontend/assets/33529490/e0117912-04df-4c6b-8457-8152c4d983a9)
Shows as 
![image](https://github.com/home-assistant/frontend/assets/33529490/7889321b-dab4-40d9-9567-e72b12741fe7)


And the one I cannot clear out (as empty is not accepted, and `none` is not in the list):
![image](https://github.com/home-assistant/frontend/assets/33529490/74a1b884-12c0-4f63-912f-81c5d8a7b6e4)
Shows as
![image](https://github.com/home-assistant/frontend/assets/33529490/3efb23c6-3510-48e5-b99d-faa12be218a1)
