### ISSUE TITLE
Self-consumption is incorrectly displayed when used with the battery

### ISSUE THREAD

**Issue by JHAvB** [home-assistant/frontend#21682]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The power from the grid used for the battery is added to the self-consumption of the home, which is incorrect. The consumption of the home should be 2.1 kWh instead of 4.6 kWh.

![Afbeelding1](https://github.com/user-attachments/assets/001f718e-37a5-4d42-beee-1dd28e1a861c)

### Describe the behavior you expected

The formula for the home's consumption is not correct; the expected value is 2.1 kWh instead of 4.6 kWh.

### Steps to reproduce the issue

1.Adding import and export energy data for the battery to the energy dashboard.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.1

**Comment by Wendelstein7** [comment]
Could this perhaps be because you did not add your solar panels (if you have any?) because adding solar panel dedicated measure can help interpret the numbers and they might actually make sense. I think right now the logic is: You imported 3,7 kWh from the grid, you discharged around 1,0 KWh from the battery, but also returned 0,1 kWh to the grid. 3,7 + 1,0 - 1,0 = 4,6 kWh. Because energy cannot be lost, this energy "must have" gone to your house usage.
