### ISSUE TITLE
"visibility" config section: unexpected colored background

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21915]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider a theme:
```
test_minimal:
  ha-card-background: red
```
When applied - all cards got this nice look:
![image](https://github.com/user-attachments/assets/f4a2f8ce-dbf5-49f6-9743-ebaf51cd0e3c)

Select any card, open UI config:
![image](https://github.com/user-attachments/assets/9f75b0e4-ee8a-471c-a2fe-a91a3a30fc96)

Then switch to "visibility" tab & select some option:
![image](https://github.com/user-attachments/assets/c7f2aa2e-e482-43b0-bef5-448bffeff010)

The config UI part gets this red background too.
Probably because it contains the `ha-card` element as well.

One more weird thing - it gets the `.type-entity` class )))):
![image](https://github.com/user-attachments/assets/d34528f3-3987-42ea-a87b-8a27abc8401e)
If you experiment with Entities card - then this panel will have `type-entities`.

This implementation makes this panel behave like a stock card - and thus gets a customized theme.
[Not to mention card-mod issues.](https://github.com/thomasloven/lovelace-card-mod/issues/402#issuecomment-2334716839)

### Describe the behavior you expected

Config panels should not contain standard cards.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.9

### In which browser are you experiencing the issue with?

Chrome 128.0.6613.114

### Which operating system are you using to run this browser?

Win10x64

**Comment by piitaya** [comment]
ha-card-background it not only used in dashboard cards. You should also notice colored cards in the automation editor, right?

**Comment by ildar170975** [comment]
Paul, you are probably right about the automation editor. Have not checked it (honestly, I am not using themes with background at all and observed the issue only while investigating the card-mod issue mentioned above). 

IMHO the main issue is - these “collapsible” panels are styled by a theme, and other elements of UI editor - not. 
Should not we provide a way of “themeing” cards to avoid a possible interference on UI editor? (and probably other system parts)

**Comment by piitaya** [comment]
The dashboard card are using the same `ha-card` to have consistent experience in the app. It's also possible to theme the dashboard only by applying a theme on a view.

I think your issue is more a `card-mod` issue than a front-end issue. `card-mod` should not target `ha-card` outside of the dashboard.

**Comment by ildar170975** [comment]
> think your issue is more a card-mod issue than a front-end issue

This current issue is about a variable in a theme which makes some part of UI Editor be colored. If someone wants all cards have some particular background (or opacity) - he/she would not expect the some part of UI Editor be colored as well.

**Comment by MichaelMKKelly** [comment]
I am the creator for the cardmod issue that was linked above
whilst colour is a great example of this issue its not the only thing. I came across the issue when the visibility part of the interface was totally non usable because I had disabled interaction with the card on the dashboard using cardmod (by adding "pointer-events: none; "). I am sure there are various other things which could probably further break the visibility interface perhaps catastrophically.

I think the crux of the matter is: why is this particular section of the interface different to the others?

1. its a newer addition so Is this a sign of what is to come and further interface changes will move over to this style?
(therefore perhaps making cardmod disrupt further parts of the interface in the future.)

2. or will this part be brought in line with what everything else is in the HA UI?

3. or will this specific part of the UI remain this way whilst the others are not?

if 1 then its an issue cardmod will have to deal with
if 2 then its a temp bug that a HA update will resolve
if 3 then its a perm bug that someone may solve at some point in the future

it seems that its just a matter of working out what the plan is for the HA UI and then plans can be made to go from there.

I don't think either side is to "blame" but instead just a matter of getting everyone on the same page.
