### ISSUE TITLE
Energy dashboard shows total value of energy sensor instead of daily increase - HA 2024.9.3

### ISSUE THREAD

**Issue by thel1988** [home-assistant/frontend#22151]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

From day to day, I check the energy dashboard in HA and i see that the total amount of the increasing energy meter, is being counted as energy used today, even though it is used through out of the lifetime of sensor, which doesn't make any sense.
![image](https://github.com/user-attachments/assets/be99c18e-f3fa-45b9-8070-847dc94aaed5)

I'm Using a shelly pulse counter, which is usually working fine.
![image](https://github.com/user-attachments/assets/62cece44-044a-4712-8c70-d7356b42993d)

I'm using a template sensor with rising total.
![image](https://github.com/user-attachments/assets/574545c2-841a-4648-a5c1-e4b96e4dad02)

The enties from developer tools
![image](https://github.com/user-attachments/assets/856ce3d1-5a35-4d06-a284-6a36ecc736c8)
![image](https://github.com/user-attachments/assets/58318660-9ee7-4be3-a6d7-797dc439505b)

From shelly:
![image](https://github.com/user-attachments/assets/b5c5cf47-8cf6-4255-87e8-5e939e32420d)

Some days it works just fine
![image](https://github.com/user-attachments/assets/9b35b7b6-4df5-4e64-925a-623e5378a277)

### Describe the behavior you expected

The total should not count towards the energy usage for the day. Just count towards the increasing total.

### Steps to reproduce the issue

1. Not sure how to replicate this, but it seems to be when the shelly device is somehow disconnected (happens often), but not sure if this is related, as it is located on a mesh WIFI AP. And then reconnects.

### What version of Home Assistant Core has the issue?

2024.9.3

### In which browser are you experiencing the issue with?

Seems to be an issue with all browser

### Which operating system are you using to run this browser?

Both MacOS and Windows 11 tested.

### Problem-relevant frontend configuration

```yaml
Template sensor:
{{ states("sensor.varmepumpe_counter_value") | float(0) | round(2) }}
```

**Comment by thel1988** [comment]
I'm unsure if this is a gui problem or somewhere else? So sorry if this is posted in the wrong git.

**Comment by karwosts** [comment]
This is a problem with your template, you should not use float(0) in a template that you want to pass into statistics. 

This means anytime your source sensor goes unavailable, your template sensor will momentarily change to 0, and then change back to the original value when it is restored, which will be counted as a huge jump in consumption. 

Instead of using float(0) you want to use an availability template to make your template go to unavailable when the source sensor is unavailable. Then when it returns available it won't be counted as an increase in consumption. 

As this is not a community support channel, I will close this, and please follow up in forums or discord if you need further help or clarifications with these instructions.
