### ISSUE TITLE
Hard to find conditional card in "Configure UI"

### ISSUE THREAD

**Issue by caro-coder** [home-assistant/frontend#3624]
**Home Assistant release with the issue:**
0.98.3

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Newest Firefox and Windows 10 (not browser specific)

**Description of problem:**
I have a view with nearly 20 conditional cards. It's a nightmare to find the right one, I want to edit.
Conditional cards should be visible in "Configure UI" to solve that problem. An alternative would be, that at least the name or title of the card is shown - but I think showing the whole card makes more sense.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
Yeah, we need this. For entity-filter as well. @bramkragten what do you think? we pass editMode down to cards?

**Comment by bramkragten** [comment]
Yeah, let's do that

**Comment by caro-coder** [comment]
Hi! Are there any updates on this issue?
I wish you all a happy new year 🎉

**Comment by kathy705** [comment]
Oh yes please! This is highly needed! I also have views with lots of conditional cards - and especially because the card layout in HA is different everytime depending on the screen width and the state/size of the conditional cards, I have always click through countless cards before I find the right one.
