### ISSUE TITLE
(Python) Script reload deletes description

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#3870]
**Home Assistant release with the issue:** 0.100.0.dev0

**Last working Home Assistant release (if known):** Not known

**Operating environment (Hass.io/Docker/Windows/etc.):** virtualenv

**Integration:** https://www.home-assistant.io/integrations/python_script

**Description of problem:**
PR home-assistant/home-assistant#26069 introduced user-defined descriptions of python scripts. This works as expected after Home Assistant is launched. Unfortunately these descriptions get lost after calling python_script.reload. The descriptions are not reloaded either.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
python_script:
```

**Additional information:**

**Comment by Santobert** [comment]
This is still an issue with version 0.104.3

**Comment by Santobert** [comment]
Still an issue with 0.108.6

**Comment by Santobert** [comment]
Still an issue with 0.111.2

**Comment by Santobert** [comment]
Still relevant in 0.115.0b7

**Comment by spacegaier** [comment]
I can confirm the issue, but not the root cause. I verified that the backend/core successfully loads the description information and stores it in the internal structures, but for some reason the frontend does not see it, meaning that during the frontend update only the "reload" service is available as metadata and therefore no description can be shown for the reloaded python scripts.

@bramkragten Any spontaneous ideas what/where I should check next? Specifically where the handover from core to frontend happens.

**Comment by spacegaier** [comment]
Issue still persists.
