### ISSUE TITLE
Add Fill Example Data button to Automation and Script Editors

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3934]
**Home Assistant release with the issue:**
0.100b

**Description of problem:**
A button to Fill Example Data was added to Services panel in https://github.com/home-assistant/home-assistant-polymer/pull/3596

This should also be expanded to the "Call service" actions in Automation Editor and Script Editor if possible. I think it's even more useful in these sections because these areas are aimed at a wider audience, and they don't have the table listing all possible parameters etc... So being able to fill in the example data would help a lot.

Mockup:
![mockup](https://i.imgur.com/VxmHeHC.jpg)

An extra benefit to making this button "re-usable" is that they could maybe be added to the Lovelace Card Editors down the line (when setting call-service on tap/hold actions etc).

**Comment by bramkragten** [comment]
I think there is more work to do, the developer-tool service page has a lot more features than the automation and service editors. The automation and service editor should give the same and more user friendly functions like explanation and entity pickers.

We know what parameters you can enter in a service, so why not have input fields for them instead of writing YAML?

**Comment by bramkragten** [comment]
#3696
