### ISSUE TITLE
Move position of card editor toggle button to bottom left

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4086]
If I recall correctly, the button to toggle between code and UI editor originally used to be in the bottom left corner. I think we should consider moving it back down there.

![editor-toggle](https://i.imgur.com/8w9dmgu.png)

**Benefits**:
* It makes all the card editors look significantly cleaner IMO: 
  * Lines up with the other cancel/save buttons
  * Always in a consistent spot rather than having a random button in the middle
  * Saves a little screen real estate in some cases, see the red rectangle in my gauge card example above
  * Button would now be visible at all times. The current placement of the button means that if a scrollbar becomes visible, the button becomes "invisible" and must be scrolled into view ([pic](https://i.imgur.com/k7LBGEe.jpg)) 
* Better mobile editing experience
  * Prevents accidental taps, because the button will be out of the way when scrolling. Right now you have to scroll past this button in order to see the preview (edit the "Entertainment" card in the demo on a mobile device to see what I mean). It is possible to accidentally enter the code editor, which I suspect most people do not want to do on a phone.
  * Moving the button will allow you to see a little more of the preview on mobile without scrolling

**Drawbacks**:
There is only one drawback to this as far as I can tell, which is demonstrated in the screenshot comparison below. Top screenshot is the current behavior and bottom screenshot is what it would look like under this proposal.

![drawback](https://i.imgur.com/m43Jeno.jpg)

Basically when the preview is significantly taller than the editor area, there can be a noticeable gap before you see the toggle button. This scenario is pretty rare and mostly only occurs when you switch to the Code editor on cards with little to no configuration options. The above screenshot is the most extreme example I could create using the demo.

Visually this gap is not ideal, but I personally don't consider it a dealbreaker, especially when taking into account the other benefits. Curious what others think, is this acceptable or not? I feel like in these instances where there's such limited configuration options, the user wouldn't really be toggling the editor back and forth anyway, so they wouldn't notice this.

Here is how the same Thermostat card looks in visual editor with this change: 

![thermostat-card-visual-editor](https://i.imgur.com/QUnkXtu.jpg)

It doesn't have the huge gap that the code editor does, and the user would have no reason to switch to code editor anyway since all the options are present here. So maybe the drawback mentioned above isn't such a big deal? I dunno.

Hopefully I did a decent job demonstrating the pros and cons.

**Comment by springstan** [comment]
I would like to take this issue :)

**Comment by springstan** [comment]
If I move the button from [hui-card-editor.ts](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/editor/card-editor/hui-card-editor.ts) to [hui-dialog-edit-card.ts](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts) I will have to check which GUIMode (Editing mode) is currently used by getting the `HuiCardEditor` instance and its attributes, right? 
Because how do I get its attributes before it is even rendered? e.g. for the title of the button if it is disabled or not and so on.

Or am I thinking around this problem completely wrong and it would be easier to create the GUIMode in [hui-dialog-edit-card.ts](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts) and then pass it onto [hui-card-editor.ts](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/editor/card-editor/hui-card-editor.ts) instead?

**Comment by bramkragten** [comment]
You have acces to `hui-card-editor` in the dialog: `this. _cardEditorEl`, if that is `null`, we shouldn't show the button. `_cardEditorEl` has a public method `toggleMode()` you can use to toggle the editor. To check if it should be enabled you can use `this. _cardEditorEl.hasError` and create the same getter for `_warning`.

**Comment by springstan** [comment]
Great to hear your take on this. I have actually implemented all of this before I asked the question, still I wanted to know if there is a better way.
I will make a PR then :)
