### ISSUE TITLE
Group automations/scripts/scenes

### ISSUE THREAD

**Issue by mcinnes01** [home-assistant/frontend#4542]
**Is your feature request related to a problem? Please describe.**
When you have a lot of automations the UI looks cluttered and its difficult to find the automation you are interested in.

**Describe the solution you'd like**
Add ways to group automations, a field to group the automations by would be the simplest option. This should be used for structuring the display of automation, but it should also enable a search facility to be available. As there is already more information that can be used from the detail in an automation, this should also be surfaced to the search facility such as device/service/group/etc.

Another dimension to this is that from a device/entity/integration etc, you could also provide the ability to display the automations related to that device/entity/integration.

**Describe alternatives you've considered**
I don't think there is a good alternative, the UI doesn't make it easy to manage, view or find automations when you have a fair few of them.

**Comment by zsarnett** [comment]
Had an idea for this before but hadn't gotten around to doing a mockup yet, will share what I had in mind. Basically I think the system can and _should_ handle everything here, where things would just work without any manual organization required on the users part. 

I think having the following three filters would handle like 95% of use cases:
1. **Domain** - filter by any domain. So you can see all automations with a light entity, anything with a lock, person, media player, vacuum, alarm panel, etc.
2. **Device Class** - any binary sensors with motion, door, window, occupancy, etc. So if you wanted to see all automations involving your windows or doors, can do that very easily.
3. **Integration** - with this filter you could see any automation that involves entities belonging to Plex, or Google Cast, or Hue, etc. 

This would make finding things super easy even if you had hundreds of automations. You'd be able to filter the list within just two clicks the majority of the time. These filters would also be tailored to the users personal setup too - if they didn't have any smart locks, lock wouldn't show up under the domain filter for example. So that would keep things clean and manageable. 

The challenging part would be figuring out a good filtering UI. I was thinking when the filter button is pressed, it would show these three filters as "chips" each on their own line, and you'd just horizontally scroll them. But that might not be ideal for users with very large setups that have dozens of integrations, domains, etc.


From SeanPM5

**Comment by alex6480** [comment]
The filtering sounds very useful. I don't think horizontal scrolling is the way to go as it's often unintuitive to use. It's probably better to just let each filter occupy multiple lines and let the chips wrap so all filters are visible when you press the filter button. Another option is to implement it as a searchable dropdown. If you know what you are looking for you just begin typing the name of the integration and it autocompletes it for you and suggets things along the way. And if you need to, you can use the drop down to scroll through all available values.

I also still think groups could be useful for many people. I find that even simple tasks in Home Assistant often require several automations, so it would be nice to be able to display them together.

I've made a mockup as to how it might work.

![automation_panel](https://user-images.githubusercontent.com/8026279/94994302-0a8ac800-0597-11eb-8037-13629a8dedf9.png)

![edit_automation](https://user-images.githubusercontent.com/8026279/94994300-09599b00-0597-11eb-8bd3-9e24fd41502d.png)

![automation_group](https://user-images.githubusercontent.com/8026279/94994301-09f23180-0597-11eb-9edd-5867c0380e77.png)

**Comment by mrand** [comment]
@alex6480 Tags (rather than folders) would allow all options: things can be filtered visually or viewed globally (which might help see things when re-using)

**Comment by LucaDev** [comment]
What if we would add search folders and labels? A search folder could display automations based on user-defined criteria, while labels would provide a good way to actually tag the automation. Seems a bit too overcomplicated for me though.

I would prefer simple folders as @alex6480 described. As long as you're able to create folders inside of another folder, there are basically like tags while keeping everything much more clean looking.

**Comment by ludipq** [comment]
I would love the ability to group automations into categories of my choice. For example, I could create a category (or a "folder") where I put automations that has to do with my garage.

**Comment by xthedakmanx** [comment]
+1 for this. I'm approaching 50 automations and being able to sort them would be perfect

**Comment by ludipq** [comment]
This is actually the one reason I have moved all my automations to Node-RED. Not because Home Assistant can't do the same things, but because it's much easier to organize them there.

**Comment by lukastillmann** [comment]
I feel like this folders vs tags discussion has been going on a while. However, as it becomes easier and easier to manage automations in the frontend, the issue becomes more and more urgent. I really feel that we need some way to organize automations. Wether we use a folder or a tags logic might not be as important in the end.  

Has anyone tried implementing a version of this? I am not proficient enough in Python, but I would love to help in some way if I can.

**Comment by Misiu** [comment]
> @alex6480 Tags (rather than folders) would allow all options: things can be filtered visually or viewed globally (which might help see things when re-using)

The advantage of tags is the ability to add more than one. For example, you could add <kbd>Living room</kbd> and <kbd>Light</kbd> tag to automation, this way when filtering you will be able to filter all automations for the living room or all automations that interact with lights.
Folders can't do that.

**Comment by malgoe** [comment]
I don't really see why folders would be any better than tags. The ability to use multiple tags would be great.
The lack of organisation is what keeps me from migrating most of my automations from Node Red. The automation system has really matured lately and this is the piece of the puzzle that is missing for me.

**Comment by frenck** [comment]
Home Assistant 2021.4.0 adds filtering support to the automation list, which is more flexible.

<https://www.home-assistant.io/blog/2021/04/07/release-20214/#filtering-automations-scripts-and-scenes>
