### ISSUE TITLE
Edit home zone should link update general options

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4786]
## The request

In the zones editor, the edit button for the home zone is disabled. This can be confusing. Instead we should link to the general options page where the user can change their home location.

Whenever we design UI, let's keep this in mind: avoid dead ends. When something is not possible because the user needs to do something else first, or do it somewhere else, let's help them get there. Only show dead ends if it's out of our control, ie we can't set up X if you don't have a login etc.

**Comment by sgttrs** [comment]
Currently, it is not possible to edit the radius of the home zone in the user interface. Is it possible to make it editable?

**Comment by SeanPM5** [comment]
If it's technically possible, I think my personal preference would be to just allow the Zones editor to edit home zone.

* Zones UI is a bit more well suited for this, with the ability to easily change the radius with the handles etc. It also gets the full-screen map view where you could drag it around after saving.
* Gets people familiarized with the new Zones panel
* For those already on the Zones panel, prevents them from being sent elsewhere. Would make Zones the one stop shop for all location stuff like this.

So basically the current flow would be reversed. Rather than sending people from Zones -> General, we would be sending people from General -> Zones. I think this makes sense?

General Config would maybe have the mini map removed from it and replaced with an "entity row" type thing that just displayed your home zone info as text with an edit (pencil) icon to the right of it. This would take you to the Zones panel with the "Edit Home Zone" dialog already opened. 

Editing Home zone from Zones panel would be the same UI except with the Delete button removed obviously, and probably the Passive toggle too.

**Comment by balloob** [comment]
I like that idea Sean. 

We should only allow changing home zone from the big map, not from a dialog. 

For home radius, that would require a backend change.

**Comment by jes1417** [comment]
Not sure if this is an issue or not but I ha e changed the name of my home zone from the default of Home to Office as that is where I use this instance. But when viewing my location it says I am home and doesn't display the name I have put in. If I create a new zone and travel to that area my location updates to display the name of that zone and I think the "home" zone should do the same?
