### ISSUE TITLE
Place the sensor value to the right on a the sensor card

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/frontend#4909]
## The request

Currently, the current sensor leaves a lot of white space on the right:

![image](https://user-images.githubusercontent.com/18319734/74690681-fd5acd80-51ad-11ea-95b9-c8379f9dc6a3.png)

It is the same even when we hide the graph:
![image](https://user-images.githubusercontent.com/18319734/74690701-18c5d880-51ae-11ea-838d-66249c8e8424.png)

It may be better to move the sensor value to the right. @zsarnett created a mockup on Discord

![image](https://user-images.githubusercontent.com/18319734/74690723-35faa700-51ae-11ea-9132-a41c98a8735b.png)

**Comment by vMeph** [comment]
would be great is to have a option to put to the right or to the left, cause personaly i like it more on the first picture on the left
so it seems this a question of tastes,  so why not add options for it?

**Comment by SeanPM5** [comment]
I prefer the value on the left too, personally. I think that the revised styling in 0.106 is pretty much perfect as-is:

![sensor-card](https://i.imgur.com/1MQAf0S.png)

There's no eye travel needed as the name and value are in the same spot. The text lining up on the left looks super clean and ensures a consistent style every single time, while the icon on the right solves the white space issue described in OP.

Placing the value on the right like that mockup means the sensor value will vary in position depending on the length of the `unit_of_measurement` text. Sometimes the value will display on the far right (if it's a short unit like `%` or `m` while other times the value will appear more towards the middle (`UV index` on the Dark Sky sensors, `pending update(s)` in hacs sensor, etc). This would result in an uglier, more inconsistent and cramped appearance.

Especially when you consider these sensor cards are often placed inside a horizontal stack. If you had a horizontal stack with Speedtest download, upload, and ping sensor cards the values won't line up because two would have a `Mbit/s` unit and one would have a `ms` unit (a third of the character length). That wouldn't look good.

Or if the value gets displayed underneath when shrunken (due to narrow width/stacks), why not just keep the value underneath at all times then anyway? It'd be more consistent than "sometimes it's on the right, and sometimes underneath." 

IMHO this proposal has more drawbacks than benefits.

**Comment by arsaboo** [comment]
@SeanPM5 I am not arguing with what you say, but we follow the same logic for all our other cards. Look at the entity card below:

![image](https://user-images.githubusercontent.com/18319734/74697867-f17d0480-51c9-11ea-99b5-ec4d13d22e54.png)

With your argument, we should change that as well. I just feel like there is lot of empty space on the card right now that can be better utilized. This absolutely makes no sense to me:
![image](https://user-images.githubusercontent.com/18319734/74697955-3f920800-51ca-11ea-8411-6071d2bc6037.png)

**Comment by zsarnett** [comment]
I mean if that's the case why not use an entities card for your use case. My initial thought was that the way the data is presented now is more aesthetically pleasing as it doesn't just show data in a table format. (Title | Value) I see your reasoning for the change but with balloons recent PRs that make the data hug the title more.

**Comment by SeanPM5** [comment]
> I am not arguing with what you say, but we follow the same logic for all our other cards. Look at the entity card below:

There's one huge difference though, the sensor card contains different font weights, colors, and sizes for all of the text. Which is a good thing in the current design as it provides emphasis on the sensor value and makes things easily glanceable. 

However if you were to place all these different font weights, colors, and sizes all on the same line as in the proposed design, it would look ugly IMO, a mish-mash of different styles. And it'd also be more cramped, especially when in a stack or mobile. 

Here is a quick mockup of them side by side in a horizontal stack. The proposed design (left) still would have white space from lacking the second line of text. But now the top line is super cramped as well. And this is one of the most generous examples with a tiny unit of measurement `°C`. 

![stack](https://i.imgur.com/FlRJR4s.jpg)

Any longer unit than this and you'd have to start wrapping text or decreasing text size or whatever. Then it makes the appearance even more inconsistent. Here's another quick mockup, of how the proposed design would look with varying unit of measurements. Maybe there would be a more elegant solution, but imo the card on the right does not look good:

![mock2](https://i.imgur.com/V43vvVr.jpg)

I already use the mini-graph card in my setup, so I would be fine continuing to use that card if this style is what people prefer. I'm just pointing out why that design (and the current 0.106 design) makes more sense IMO.

**Comment by arsaboo** [comment]
My overall argument is still aesthetics. I want to use the graph in the sensor card and I feel that the current card can be improved:
1. Having the icon on the right by itself is not consistent with any other card. Moreover, it is serving no purpose there. 
2. The extra line for the value creates a lot of empty space. 

The only downside is that the values may not align, but 1) that assumes everyone is using them in a stack, and 2) that is already the case with all our other cards. 

Please feel free to close the issue if you feel the current card is optimal (you won't hurt my feelings 😉 ).

**Comment by SeanPM5** [comment]
It's fine, aesthetics are subjective, and others should weigh-in so we can come to a consensus 😉 

The icon being on the right does serve a purpose, as it fills in some empty white space on the right side of the card (aka what this feature request is all about). It also keeps the left side of the card cleaner looking since it allows the text to line up.

You're correct that other cards don't have the icon on the right currently, but I think this is fine since users already have the expectation that different cards are styled differently. Entity Row, Glance, and Light cards have the icon positioned in different locations already for example. The way I see it, if the icon can be on the left or center depending on the card type, why not the right too? 🤷‍♂ 

But my main issue with this proposal is that it focuses entirely on the sensor card being standalone and taking up a full column, when the majority of people seem to use these sensor cards inside of horizontal stacks - temperature and humidity, download and upload, CPU/RAM/Disk etc. I think it's important to consider how it looks and behaves in both scenarios (standalone and in stack).

**Comment by zsarnett** [comment]
I believe we have decided to continue using the current design of the sensor card
