### ISSUE TITLE
Update mdi icon repository (March 2020)

### ISSUE THREAD

**Issue by Tamadite** [home-assistant/frontend#5094]
## The request

As loads of new **mdi icons** have been delivered, please update the HA mdi repository.
Some of the previously existing ones are no available in HA as they have changed name, e.g. `wall-sconce-variant` changed name to `wall-sconce-round-variant`.

## The alternatives

To download the icon to `config/www/` folder and make a local reference to it although it does not become fully functional, e.g. automatically change colour status.

## Additional information
https://materialdesignicons.com

**Comment by goyney** [comment]
MDI core contributor here. We typically open a PR here to introduce new versions of MDI, however 5.0 is very different and contains lots of breaking changes (icon removals, renames, etc.)

https://dev.materialdesignicons.com/changelog#version-5.0.45

Unfortunately, it's not going to be a simple update this time. We've been in communication with the maintainers of Home Assistant and recommended a mapping approach to not break existing uses of the icon, but I'm not sure the decision they've made on that front. That being said, we're not planning on opening a PR for this version because it seems like something the HA team should probably tackle after they determine the best path forward for HA.

**Comment by FredericMa** [comment]
Bumped into the same issue. Wanted to use the new pump icon that's available since 5.1.45...

**Comment by timbru31** [comment]
This issues should be closed as it was update via https://github.com/home-assistant/frontend/pull/6357
