### ISSUE TITLE
Documentation Links in more places - (?) icons

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#5654]
## The request

Add (?) icons to places in the UI. 

Card Picker - Next to the name of the card
Card Editor - Next to the title
Configure UI Popup - Right side button for `Take me to Docs`

## Additional information

Make it easier for the Users to find documentation of lovelace

**Comment by SeanPM5** [comment]
I don't think it's needed in the Card Picker personally. There's already a preview for each card to give an idea of exactly what it's like. Putting two dozen help icons on the card picker would just add clutter imo. And it would make it slightly more annoying to select the card, because now some of the tap target would have to be given up in order to make those help icons clickable.

For the Card Editors I think it's a good idea but would prefer it in the top right corner imo.

**Comment by zsarnett** [comment]
Yea I dont think we should add it in all places for sure. And I agree top right of the editor in the title space is the best place

**Comment by bramkragten** [comment]
And a back button in the card editor to return to the picker :-)
