### ISSUE TITLE
Condensed UI for Integrations

### ISSUE THREAD

**Issue by GauthamVarmaK** [home-assistant/frontend#5666]
## The request
The new integrations page is well designed, kudos on that. But it is taking up a lot of space, not ideal with many integrations. Hence it would be great if we can have a more condensed UI on the integrations page, (with icon to the left and text to the right as in Supervisor>Addons Page). 

![image](https://user-images.githubusercontent.com/43441192/80671298-0d086380-8ac7-11ea-82c4-ccb712acd779.png)
![image](https://user-images.githubusercontent.com/43441192/80671353-2d382280-8ac7-11ea-9ef0-b7989c2bdf7c.png)

## The alternatives
Maybe having an option to toggle between condensed and regular UI in case people are not happy with the new UI

## Additional information
Thank you, home assistant devs and community for making Home Assistant what it is.

**Comment by zsarnett** [comment]
A redesign is not really something we would look to do. a lot of work for no real benefit. Adding a search bar instead would be a beneficial addition

**Comment by SeanPM5** [comment]
I explored this idea before and made some mockups, but came to the conclusion it was not worth it. You can't really do a compact mode in a clean way without dropping features.

The cards on the Integrations page have five different tap targets - Rename, Options, X devices, X entities, Overflow menu. Cramming all this into a much smaller card is challenging especially if you're trying to be finger friendly on mobile. You'd have to move most things inside the overflow (3 dots) menu, but that overflow menu already has a bunch of things inside it. 

Main challenge though would be trying to implement the grouping of config entries. It's just not possible to do in a nice way IMO. You can't really have a scrollable list because there's no room for that in such a tiny card height. You'd only be able to see like one thing at a time. 

In the end the user experience would suffer too much IMO. Pretty much every action would take at least one more tap/click, and it would be so cramped and cluttered.

**Comment by bramkragten** [comment]
> A redesign is not really something we would look to do. a lot of work for no real benefit. Adding a search bar instead would be a beneficial addition

We have a search bar? 😄
