### ISSUE TITLE
Revised Move to View Modal

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#5675]
## The request

![image](https://user-images.githubusercontent.com/18730868/80732389-3c749b80-8ada-11ea-95f7-a6cc4f35562b.png)

With Lovelace now allowing for multiple dashboards. I see a real use case of moving cards between them. This new Move to View modal would allow specifying the Dashboard and view you would like to move the card to.

I have not looked up the specifics for making this happen just a thought from the issue: #5668 

Use Case: Duplicate Card. Move to new Dashboard

## The alternatives

Copy Yaml or remake card in the new dashboard

**Comment by bramkragten** [comment]
Maybe add a extra step before showing the views when the user has more than 1 dashboard

**Comment by zsarnett** [comment]
Yea I was thinking default the current dashboard. And then leave view empty

**Comment by SeanPM5** [comment]
This is what I had in mind (rough idea): 

![dashboard](https://i.imgur.com/dRpwz9v.jpg)

Will always show your default dashboard first because I think 95% of the time you'll want that.

If you want to select a different dashboard, you click the little arrow icon and it would show your dashboards. Once you choose a dash, the views shown in the dialog below will update.

Keeps it mostly similar to how it works today but with added functionality.

**Comment by zsarnett** [comment]
I'm not sure that's obvious enough that you can switch the dashboard

**Comment by SeanPM5** [comment]
Maybe something like this? But the "Change Dashboard" would be a dropdown list instead or something.

![image](https://i.imgur.com/ilFL2Yw.png)

I'm just a little iffy on the idea of showing a dedicated "choose your dashboard" screen first because I think that 90% of the time you're gonna be sticking within your main/default dashboard.

If you're seeing a screen 100% of the time for a functionality you only use 10% of the time or less, feels like that could get annoying? But I dunno, maybe I am overthinking it.

**Comment by zsarnett** [comment]
That's why I like the original image I posted.

It would be a dropdown of all the dashboards but with the dashboard, you are currently on as the selected default value. Then the View field would be drop-down but blank and required to save.

**Comment by bramkragten** [comment]
I like your second proposal @SeanPM5 leave it like it is, just add a dropdown for the dashboards on top.
