### ISSUE TITLE
Weather card: truncated weather status

### ISSUE THREAD

**Issue by Molodax** [home-assistant/frontend#5923]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The weather status is truncated even if there is enough space in that line.

## Expected behavior
The weather status should not be truncated.

## Environment

- Home Assistant release with the issue: 0.110.0b3
- Last working Home Assistant release (if known): 0.108.x
- Browser and browser version: Chrome 81.0.4044
- Operating system: Android 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![20200518_213626](https://user-images.githubusercontent.com/22867988/82252737-d7c99580-994f-11ea-8024-95d1b55a787a.jpg)

**Comment by Mariusthvdb** [comment]
Still happening on 0.114.1:

![image](https://user-images.githubusercontent.com/33354141/90344563-1dfbc700-e01b-11ea-872f-cb63fa62e554.jpeg)

**Comment by spacegaier** [comment]
@Molodax Some context info: Even though it looked like there was enough free space for the weather condition, there actually was less, since internally there are two parts. The wider the right one is (combined both temperature plus the secondary attribute below), the less space the actual condition text has.

The linked PR from @zsarnett now replaces the text from the secondary attribute with icons so more space should be available for the condition text. Depending of the width of the card that of course is no guarantee, but the best thing we can do I think. Please report back once you had a chance to test the new frontend version.

![image](https://user-images.githubusercontent.com/114137/96301249-32e2df80-0ff7-11eb-91f6-032aaa77a93c.png)
