### ISSUE TITLE
Deprecate and remove `extra_html_url` config option

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#6028]
## The request

We used to allow the user to specify HTML files via `extra_html_url` that we would import into the page. When it became clear that HTML imports were not going to make it, we replaced that with `extra_module_url` and `extra_js_url_es5` (https://github.com/home-assistant/core/pull/24675 by @thomasloven, June 21, 2019).

I think that it's time to deprecate and remove this option. Because we still support this, we have been including it in the main entrypoint of our app, 450 lines of JS 🙄 

Note that this does not impact referencing `html` in Lovelace resources.

Places to update:

 - Remove polyfill from `app.ts`
 - Remove `<link rel="import"` writer from `index.html.template`
 - Remove options from `frontend/__init__.py` (in core)

**Comment by Mariusthvdb** [comment]
many people love and use the custom-ui plugin to add customizations to Homeassistant the current core Lovelace frontend doesn't cater for (global customization), and their frontends depend on that. Some custom cards can customize on an entity or card level, but none have the power nor possibilities of custom-ui.
Making custom-ui a unique and essential plugin, which should be preserved, at least until a core Lovelace replacement has been created. I've had a friendly nod at Bram, but he has understandably replied facing the time to do so, or at least maintain that.

That being the case, Id like to add to this discussion, to please not break custom-ui until then. 

So let me ask if your plan above will, knowing that Custom-ui can be loaded via either

```
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
```

or:

```
customizer:
  custom_ui: local
```
which in itself loads custom-ui again via:

```
        if custom_ui == LOCAL:
            add_extra_html_url('/local/custom_ui/state-card-custom-ui')
```

HA110 broke original custom-ui because if the new icon handling, but Bram and I managed to fix that, and people are able to use custom-ui from 110+.

Would there be an alternative way to load custom-ui when the 'extra_html_url' would be deprecated? (I take it the customizer way would also fail?)

Thanks for considering.

**Comment by bramkragten** [comment]
@Mariusthvdb `custom-ui` can perfectly be imported as a Javascript module, would just need to change the way it is built. We can not keep things around because of custom projects that are not being updated anymore.

**Comment by thomasloven** [comment]
I assume there'll be a two version deprecation warning or so?

In the custom-ui case it *may* just be as simple as removing the first and last lines of `state-card-custom-ui.html` and changing `extra_html_url` to `extra_module_url`. I may also absolutely wrong. Perhaps you could be so kind as to test this, @Mariusthvdb?

**Comment by bramkragten** [comment]
Oh yeah it is just wrapped in a `script` block... That should work

**Comment by Mariusthvdb** [comment]
testing... Thanks for the suggestion, how great this would be... while at it, and assuming this would work, shouldn't we rename the file and add it as resource .js as we do with all other custom cards?

**Comment by thomasloven** [comment]
It was a bit of a long shot, but it **could** have worked.

**Comment by Mariusthvdb** [comment]
error in inspector:

<img width="971" alt="Schermafbeelding 2020-05-25 om 13 08 36" src="https://user-images.githubusercontent.com/33354141/82808003-50b57980-9e89-11ea-8a95-0bb64a5af9e1.png">

**Comment by thomasloven** [comment]
Ah. Try just renaming it from `.html` to `.js` then. (and change the filename in the settings too)
The .gz file might still cause trouble, though, but it's worth a try.

**Comment by Mariusthvdb** [comment]
no .gz file in my folder, only the html, now .js file.

It is loaded, and proof of that is:

<img width="497" alt="Schermafbeelding 2020-05-25 om 13 39 55" src="https://user-images.githubusercontent.com/33354141/82809808-3da4a880-9e8d-11ea-9a72-cc76137da260.png">

it now shows an new error:
<img width="966" alt="Schermafbeelding 2020-05-25 om 13 38 48" src="https://user-images.githubusercontent.com/33354141/82809946-8cead900-9e8d-11ea-8d69-308ae6026964.png">

fear there's a bit more to in than this..

fwiw, Ive loaded it via

```
frontend:
  extra_module_url:
    - /local/custom_ui/state-card-custom-ui.js
```
which in itself works, as this exercise proofs ;-)

**Comment by Mariusthvdb** [comment]
have to report succes on custom-ui after all. Thomas's suggestions work. I made the edits in the original file, and not my own edited custom-ui file.... really sorry for the confusion.

Ive branded the file with `JS 20200520-adapted-for-HA110` locally as to be sure it is loaded correctly:

<img width="466" alt="Schermafbeelding 2020-05-27 om 10 09 12" src="https://user-images.githubusercontent.com/33354141/82994254-23400b80-a002-11ea-8f17-7796583cc193.png">

@supremelink made me see that... here https://github.com/andrey-git/home-assistant-custom-ui/issues/184#issuecomment-634395655

so Thomas: thanks again! 
hope this stays now....

**Comment by Mariusthvdb** [comment]
small update: no longer need the frontend: method for custom-ui, now use resources. Made a rudimentary [dedicated repo](https://github.com/Mariusthvdb/custom-ui) for easy downloading and instructions. Hope this is ok. All credits to Andrey.

**Comment by KTibow** [comment]
Time to close?
