### ISSUE TITLE
Home/Away state coloring not consistent

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#6035]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
For one person, the away state is purple and home is turquoise:
![image](https://user-images.githubusercontent.com/1368405/82793386-18a23c80-9e71-11ea-9ff0-b971b76c2ef2.png)

For another person away is turquoise and home is purple:
![Screenshot_2020 05 25_10h15m01s_012_](https://user-images.githubusercontent.com/1368405/82793482-438c9080-9e71-11ea-9278-b8e914067ea5.png)

## Expected behavior
The colors should be consistent. 

## Steps to reproduce

1. Have two device trackers each attached to a different person
2. Have a look at the state history

## Environment

- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): none
- Browser and browser version: Chrome Edge 83
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Colors are not ties to states (or the most states) just a few exceptions.

We could maybe add home and away to this list, not sure if that will work with coloring the other states (zones) a device tracker could be in.

https://github.com/home-assistant/frontend/blob/lazy-get-card-size/src/components/state-history-chart-timeline.js#L75-L81

**Comment by SeanPM5** [comment]
How about always ensuring green for home and red for away (like on binary sensors). And then the zones would just be random colors.

**Comment by Mariusthvdb** [comment]
Maybe out of scope here, but since you’re talking state colors:
Why not make those user configurable. Somewhere in /configuration, allow to set on_color and off_color and use those anywhere for home/true/on and not_home/false/off and the other binary states.

Not taking custom_ui here, or even templates (would be great too though...). No, simply allow the user to set the state colors used throughout HA.

I mean who would want Color red to dominate the frontend, it is so ugly and harsh.... I always use firebrick, or maroon ;-)

**Comment by bramkragten** [comment]
That would be theming, not something that should be in config

**Comment by Mariusthvdb** [comment]
well, when you think of it, why not? Wouldn't it be handy to have that in the GUI too. Theming now is very much a yaml driven process, needing acces to the file system etc etc.
Since HA is heading more and more to a Gui driven way of configuration, I would certainly see the merits of a view where we can set all used fields in the Frontend.

It would also prevent the many questions/challenges people face when using a theme that doesn't (yet) use all needed and/or available/necessary color settings, and their states get lost because the background uses the same color as the secondary-color..... liken the dark color themes lately.

As said, probably out of scope here, but please consider that elsewhere in the frontend/gui development?

getting it back in scope: a small subset of these theme colors, like primary and secondary-colors, or these on/off colors, could be added to /profile page where we now also have the theming settings.

**Comment by Mariusthvdb** [comment]
> That would be theming, not something that should be in config

talking to theming, please allow me this here (dont want to bother you with a dedicated issue/FR)
before we could set themes per entity, so the icon, name, and state would get the color set in that theme.
via custom_ui we could do this:

```
    automation:
      templates: &state_color
        theme: >
          if (state == 'on') return 'gold';
          return 'steelblue';
```

this entity theming has long been gone since Lovelace doesnt support it, but Ive never thought of using you if this would be an minor tweak in the custom-ui, or if that is simply no longer possible using Lovelace.

Reason I ask is that theming was a perfect way of accenting the state of an entity that has an entity_picture and not an icon. The entity_picture can be the same for all states, but the color could then reflect the state, and signal the user in the frontend.

If at all possible, Id take this to a dedicated thread, and as for some assistance to bring that back too, just like icon_color. Of not, Ill forget about it.
thanks for not killing me here...

**Comment by TheZoker** [comment]
@bramkragten Any news/idea on this?

**Comment by bramkragten** [comment]
A PR is welcome, add the colors to <https://github.com/home-assistant/frontend/blob/dev/src/components/state-history-chart-timeline.js#L75-L81> and make sure it doesnt overlap with the other colors zone can get.

**Comment by TheZoker** [comment]
Thanks I will try 👍 
Just a quick question: Wouldn't it be also possible, that the frontend decides for a color for each state on load and uses this color across this session of the frontend? So at least every state has a certain color and not multiple like it is now
