### ISSUE TITLE
Sony PlayStation 4 file not parsed correctly

### ISSUE THREAD

**Issue by nikiyao** [home-assistant/frontend#6124]
@bskaplou 
#35778

In 0.111.0b1-4 I keep receiving this error in my logs that is not there in 0.110.6

```
Log Details (ERROR)

Logger: homeassistant.components.ps4
Source: components/ps4/__init__.py:170
Integration: Sony PlayStation 4 (documentation, issues)
First occurred: 8:41:31 AM (3 occurrences)
Last logged: 8:41:42 AM

Games file was not parsed correctly
```

**Comment by SeanPM5** [comment]
This is the wrong place, specific integration bugs should be reported on the "core" repo here: https://github.com/home-assistant/core/issues/ That way it can be properly labeled and tracked. This frontend repo is more for user-interface related issues.

I don't have the ability to move it for you otherwise I would. Thanks for reporting it though :)

**Comment by nikiyao** [comment]
Thank you
