### ISSUE TITLE
mdi:apple-airplay icon is not showing

### ISSUE THREAD

**Issue by Quentame** [home-assistant/frontend#6160]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

mdi:apple-airplay icon is not showing

![image](https://user-images.githubusercontent.com/14821482/84570503-3dae0f00-ad8e-11ea-95e6-8f49041f744f.png)

## Expected behavior

Display the icon

## Steps to reproduce

Set a entity icon to `mdi:apple-airplay`

## Environment

- Home Assistant release with the issue: 0.112.0.dev0 - Frontend version: 20200603.2 - latest
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 77 & Chrome 83
- Operating system: Linux Fedora & Mac

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

The icon exists : https://materialdesignicons.com/icon/apple-airplay

**Comment by SeanPM5** [comment]
Try simply `mdi:airplay` instead. This was one of the many (~120) icons renamed in Material Design Icons v5.0.45, which Home Assistant doesn't use yet (HA uses v4.9.95). 

I'm not sure what the plan is for this, due to the [huge number of breaking changes](https://github.com/Templarian/MaterialDesign/issues/4901) in MDI v5.0.45. It might be possible to remap the old icon names to the new ones, but that wouldn't help with the ~75 removed icons obviously. Perhaps it's best to just do it and let users handle the breaking changes on their own?

Until the version in HA gets updated to match, their website will be "inaccurate" with lots of names that don't work in HA and 450 newer icons not available to use in HA. You can use [this page](https://cdn.materialdesignicons.com/4.9.95/) instead to see what is currently available in HA.

**Comment by Quentame** [comment]
It fixes indeed.
Thanks for the link of available icons :+1: 

Haven't seen an issue to track this, should we add one ?
Or add an alert ?

**Comment by SeanPM5** [comment]
@Quentame that's a good idea, I just opened an issue here: https://github.com/home-assistant/frontend/issues/6162
