### ISSUE TITLE
Automation folder structure

### ISSUE THREAD

**Issue by overkillthemighty** [home-assistant/frontend#6437]
## The request

Would it be possible to organizationally group automations? I am thinking a folder structure or something that allows groups to be collapsed (Also, being able to clone an automation would be cool):
```
-Home
   -Alarms
      -Alarm 1
      -Water Alarm
      -Data Usage
   -Auto Unlock
      -Fred
         -Away Long Enough (Fred)
         -Auto Unlock (Fred)
      -Larry
         -Away Long Enough (Larry)
         -Auto Unlock (Larry)
   -Lights
      -Front Light
         -Front Light On
         -Front Light Off
```

## The alternatives

Maybe a way to hide/unhide automations so I can reduce clutter while I am working on something as an alternative?

**Comment by bramkragten** [comment]
I think something like tags and some way to filter them be better

**Comment by SeanPM5** [comment]
Had an idea for this before but hadn't gotten around to doing a mockup yet, will share what I had in mind. Basically I think the system can and _should_ handle everything here, where things would just work without any manual organization required on the users part. 

I think having the following three filters would handle like 95% of use cases:
1. **Domain** - filter by any domain. So you can see all automations with a light entity, anything with a lock, person, media player, vacuum, alarm panel, etc.
2. **Device Class** - any binary sensors with motion, door, window, occupancy, etc. So if you wanted to see all automations involving your windows or doors, can do that very easily.
3. **Integration** - with this filter you could see any automation that involves entities belonging to Plex, or Google Cast, or Hue, etc. 

This would make finding things super easy even if you had hundreds of automations. You'd be able to filter the list within just two clicks the majority of the time. These filters would also be tailored to the users personal setup too - if they didn't have any smart locks, lock wouldn't show up under the domain filter for example. So that would keep things clean and manageable. 

The challenging part would be figuring out a good filtering UI. I was thinking when the filter button is pressed, it would show these three filters as "chips" each on their own line, and you'd just horizontally scroll them. But that might not be ideal for users with very large setups that have dozens of integrations, domains, etc.

**Comment by bramkragten** [comment]
Would like to add Area to that list

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/4542
