### ISSUE TITLE
Please bring back Alarm.com

### ISSUE THREAD

**Issue by cjeffcoat80** [home-assistant/frontend#6570]
## The request

 
 I would like to be able to arm/disarm my alarm and be able to do so by using a tracked device to automatically arm and disarm the alarm.

## The alternatives

I had used honeywell alarm panel in my old home. But my provider that I am with does not use honeywell, only alarm.com

## Additional information
I seen where alarm.com use to be in HA. Not sure what happened but hopefully it can come back.

**Comment by frenck** [comment]
The Alarm.com integration has been removed. The website of Alarm.com changed, causing the integration to break because it relied on web scraping, which is no longer allowed (ADR-0004).

We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
