### ISSUE TITLE
Device summary no list scripts when use service

### ISSUE THREAD

**Issue by shirou93** [home-assistant/frontend#6631]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When i use service like turn on switch on device summary no list scripts. I have to use device turn on/off to show scripts on summary.

Automation list working when use services.

## Expected behavior
Showing list when use service without use devices on scripts.

## Steps to reproduce
Use only services like turn on light in scripts and check device on settings. List scripts show nothing. (With automation work)

## Environment
Ha 114.1 on hassos. Chrome/Firefox and android app

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by shirou93** [comment]
0.115.4 same problem. Device when use on automation with services like turn on switch have show on list. Scripts show list always empty. Only when use device turn on etc. Scripts have list on summary.

**Comment by spacegaier** [comment]
I had some trouble understanding the issue, but since I finally got it, I thought I'd leave a comment for clarification.

If you create a script that uses a sequence step of type "Device", then the device summary page correctly lists this script. If however create a script that only "indirectly" uses the device, e.g. via a "Call service" of "switch.turn_on" connected to an entity of the device, then the device summary page does not list this script, although it has a logical relation.

**Comment by shirou93** [comment]
> I had some trouble understanding the issue, but since I finally got it, I thought I'd leave a comment for clarification.
> 
> If you create a script that uses a sequence step of type "Device", then the device summary page correctly lists this script. If however create a script that only "indirectly" uses the device, e.g. via a "Call service" of "switch.turn_on" connected to an entity of the device, then the device summary page does not list this script, although it has a logical relation.

Yes, but when use service in automation summary page device show up on list. Issue only on scripts.

**Comment by spacegaier** [comment]
It also does not work with automations for me (minimal automation with HA start trigger and call service for entity of device).

Either way, I think it is a core issue, since the search logic `search/related` is implemented in the core. However, judging by a quick glance at the code, it seems to be by design that does automations and scripts are currently not found, since apparently that made some trouble in the past: https://github.com/home-assistant/core/pull/30511#issuecomment-571118953

**Comment by shirou93** [comment]
> It also does not work with automations for me (minimal automation with HA start trigger and call service for entity of device).
> 
> Either way, I think it is a core issue, since the search logic `search/related` is implemented in the core. However, judging by a quick glance at the code, it seems to be by design that does automations and scripts are currently not found, since apparently that made some trouble in the past: [home-assistant/core#30511 (comment)](https://github.com/home-assistant/core/pull/30511#issuecomment-571118953)

I noticed when add  reperat sequence in automation also this automation not show in this device page assume.

`repeat:
  count: '12'
  sequence:
    - type: toggle
      device_id: aa15c40bccae27e1dfa0ff6ed23dc70f
      entity_id: light.lozko
      domain: light
    - delay: '1'`
