### ISSUE TITLE
"Dismiss" button on snackbar 

### ISSUE THREAD

**Issue by turleo** [home-assistant/frontend#6649]
## The request

Make snackbar able to dismiss on button click

## The alternatives

Wait for the snack bar to close

## Additional information

Snackbar hides the profile button and sometimes actions like launching can take a long time.

![image](https://user-images.githubusercontent.com/34786670/90585714-d0e54400-e218-11ea-83ea-caca690eedfc.png)

**Comment by SeanPM5** [comment]
I'm 99% sure these can be dismissed with the escape key. (If you had another dialog open or something you might need to click the snackbar first to give it focus and _then_ press ESC.)

The startup message in your example pic is really the only outlier that stays on-screen for more than a few seconds. All the other ones will already be automatically dismissing by the time you read the message and maneuver your mouse down there. So while a dismiss button might be useful on this particular one, I don't think it's needed on all the others tbh...

Another alternative would be to move this one to the center of the screen so that it doesn't cover up the Profile in sidebar. But then it might possibly cover up Lovelace cards instead.

**Comment by turleo** [comment]
Sometimes the snackbar does not dismiss itself, and sometimes it closes Lovelace cards on the phone.

**Comment by IIAIronWolf** [comment]
Maybe have an option to click those messages to dismiss them?

**Comment by gilsonmandalogo** [comment]
I'll do, assign to me, please.

**Comment by andrewbranch** [comment]
☝️ PR was merged, should this be closed?
