### ISSUE TITLE
Automation editor always needing saving even when nothing has changed

### ISSUE THREAD

**Issue by darthsebulba04** [home-assistant/frontend#6652]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X]I have tried a different browser to see if it is related to my browser.

## The problem

If you open up an automation to look at it via the ui, it always has to be saved whether you make changes or not.

## Expected behavior

To be able to look at, but not change, an automation without having to save it.

## Steps to reproduce

This can be discovered by opening up an automation, making no changes, and hitting the back button.  You'll be prompted if you want to discard your changes. Selecting 'yes' does not go back to the automation list or seem to discard anything.

## Environment

- Home Assistant release with the issue:
0.114.2
- Last working Home Assistant release (if known):
Unknown.
- Browser and browser version:
Safari 13.1.2 on MacOS 10.15.6
Firefox 28.0 on iPad
iOS app on iPad
- Operating system:
See above

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I ran some tests on my 0.115.0 dev instance:

 When I opened an old existing automation, I also was asked to save, without making any manual changes. The reason: This PR https://github.com/home-assistant/frontend/pull/6367 introduced the new script and automation modes, that are now also part of the UI (see docs https://www.home-assistant.io/integrations/automation/#automation-modes). 

=> So if you open an old automation that does of course not have a mode value set, the UI will auto-select "Single" as the default, which constitutes a change, hence the UI is asking you to save. Once you did and then then go into the automation again without changing anything, it will not ask again.

Can you verify if you see the same behavior on your end?

@bramkragten Might it make sense to show a short info snackbar if the UI auto-set the mode for existing scripts/automations so that users understand why the automation/script is considered changed?

**Comment by darthsebulba04** [comment]
In my 0.114.4 instance, any automation created before that automation mode addition always requires saving whether it has been saved previously or not.  Anything after, doesn't appear to require saving.

Not quite ready to run the beta on my production system, else I would try 0.115b.

**Comment by zsarnett** [comment]
Should this be a bug or expected behavior ?

**Comment by bramkragten** [comment]
> Should this be a bug or expected behavior ?

🤷‍♂️ a bit of both?

**Comment by darthsebulba04** [comment]
I'm not sure this is happening any longer.
