### ISSUE TITLE
entity labels are not consistent over time

### ISSUE THREAD

**Issue by pille** [home-assistant/frontend#6779]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

labels of entities are not stable over time.
e.g. on a history-card the label for a presence graph of a person shows one time their nickname, the other their fullname. also the color-scheme changes.

## Expected behavior

labels of entities and colors representing states stay constant over time.

## Steps to reproduce

1. add history-card in lovelace
2. add a person entity to track
3. reload/relogin a couple of times

## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): unknown
- Browser and browser version: chromium/83
- Operating system: linux

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I think the displayed labels depend on the data we get from the logbook / DB. So if the names of the entities change this can occur. 

Example: I had setup this as a test two days ago.
![image](https://user-images.githubusercontent.com/114137/96352765-4d37be80-10c6-11eb-9a42-3d9f1b93e435.png)

Then afterwards I renamed the entities and today it looks like this, because there are no current (= rendered) state change entries in the DB with the old names, and only ones using the new name.

![image](https://user-images.githubusercontent.com/114137/96352786-6d677d80-10c6-11eb-8a70-01d2c21d51e9.png)

Does the same apply to your situation or do the labels change even though you did not modify the entities in quite some time?

**Comment by pille** [comment]
no, i did not rename anything.
