### ISSUE TITLE
Frontend: Editing scene to check what's inside currently automatically apllies it until you leave scene editor.

### ISSUE THREAD

**Issue by Alvareiro** [home-assistant/frontend#7149]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

 When i want to peek inside scene and click to edit it the scene is applied withouth any promt. So if i have scene that turn off all lights and want to edit it my whole house will be dark until i leave scene editor
## Expected behavior

 Don't change entity state in preview? 

## Steps to reproduce

   Provide steps for us, that helps reproducing your issue.
  For example:
    1. create a scene with some state of entity
    2. change entity to diffrent state than in  scene
    3. try to edit scene

## Environment

 It's the same regardless of diffrent devices i've tested

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system: Home Assistant Container Station

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

 

```txt

```

**Comment by zsarnett** [comment]
Please remove your comments from the commented out sections

**Comment by Alvareiro** [comment]
> Please remove your comments from the commented out sections
 Ok thanks

**Comment by Alvareiro** [comment]
> Please remove your comments from the commented out sections
 Ok thanks

**Comment by spacegaier** [comment]
Never changing the entity state when editing a scene is also not the solution, since if you not only want to view the scene (your use case example) but actually edit it, you want to have the scene take effect.

Imagine a scene with two dimmable lights A and B that are set by the scene to a specific brightness value. If you now want to adjust the brightness value in this scene for light A, but not for B and we would not apply the scene to all involved entities during editing, then once you adjusted the brightness for A and saved, the brightness of B would either be 0 (if it was off at the time of the scene editing) or whatever value B by luck was at at that time, but it probably would loose the original intended brightness value that was set during the initial scene creation.

If think we need to have a slightly more complex solution: When you enter the edit mode of a scene, a popup could ask the user if the scene should be applied or not and warn that the user that if "No" is selected and they save the scene, the current entity states will be used during saving.
