### ISSUE TITLE
Log data loading with empty data appears on any sensor card

### ISSUE THREAD

**Issue by Gooman-rus** [home-assistant/frontend#7166]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I click on any lovelace card with graph, I can see the rotating blue circle and than text "There are no entries in the journal." (in Russian it's "В журнале нет записей."). The text indicating that the data not found appears on the card of **any sensor**.
![image](https://user-images.githubusercontent.com/3216521/94654314-8c63c280-0305-11eb-99bc-4431a80d5109.png)
![image](https://user-images.githubusercontent.com/3216521/94654304-8837a500-0305-11eb-9ff3-25c15f85fbd9.png)

## Expected behavior

Before version 0.115 there was no this journal data loading. How can I disable it?

## Steps to reproduce
1. Open any sensor card with graph.
2. See the rotating blue circle and then the text "There are no entries in the journal." .

## Environment

- Home Assistant release with the issue: 0.115.5
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome 85.0.4183.121 
- Operating system: Ubuntu 20.04.1 LTS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Spirituss** [comment]
I face the same issues. Moreover, sometimes the graph doesn't update correctly in accordance with the current entity state. Here is an example, the person has already been 'at home' since 00:18 but the graph still shows 'not home' status:

<img width="373" alt="Снимок экрана 2020-09-30 в 00 28 58" src="https://user-images.githubusercontent.com/47206760/94674349-b70f4480-0320-11eb-8e3b-ce5c427ed0d5.png">
<img width="93" alt="Снимок экрана 2020-09-30 в 00 33 44" src="https://user-images.githubusercontent.com/47206760/94674353-b8407180-0320-11eb-972a-2a6d4844aeb4.png">

**Comment by Spirituss** [comment]
Still there are some issues with history cards. For example, card doesn't show numeric value in case you choose the point on the graph which is near the lower axis.
