### ISSUE TITLE
Make disabled entities more obvious and easier to enable

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#7299]
## The request

This request:

https://community.home-assistant.io/t/make-disabled-entities-more-obvious-and-easier-to-enable/232360

I think that we should do two things:
 - when you click on the entities link of an integration, we should always show disabled entities
 - when disabled entities are filtered, show somewhere how many disabled entities are filtered out.

**Comment by spacegaier** [comment]
Working on an idea for point number 2 ATM.

**Comment by SeanPM5** [comment]
Rather than always showing disabled entities, which I think would be super annoying in some cases, imo the data table should have filter chips like this example from Material guidelines:

![table](https://lh3.googleusercontent.com/s5i_WoXOxEA_R_cFzKv9xzzWcFXruW8Qs66uen6ZcpE-b-XMcHlf7RVyfuJqitPaTZCjWHYYk6nNJSBGnoC88OCRjIPKZlBfVtXLWA=w1064-v0)

- The filter icon would be moved from the right (current) to the left (like above pic) making it a lot harder to miss.
- The "Filtering by integration Withings [Clear]" button would be moved into there as the first chip. It would say something like (✓ Integration: Withings) instead. Unchecking it would perform the same "clear" action as it does today. Same functionality but cleaner and nicer looking.
- Second chip would be disabled entities. It'd say something like "Disabled (48)" which addresses second point. This wouldn't clutter up the table contents, but would make it clear when there's disabled entities and how many. If the user wants to see the disabled entities all they have to do is click the chip. This saves a click compared to current way, since it's no longer inside a menu but visible at all times.
- Then chips for Unavailable and Read-only. These don't necessarily have to shown by default in the filter bar, the user could add them by clicking the filter icon (just like today).

**Comment by spacegaier** [comment]
@SeanPM5 I think that is a nice long-term solution that is a bit more effort to implement. What I have done now as an more intermediate solution, I show an information about the number of hidden entities plus a button to show all. See the linked PR.

**Comment by SeanPM5** [comment]
Yeah, I am fine your PR as a short-term solution, I just disagree with making this a permanent change personally.

In the linked WTH example there's only two entities total, but with other integrations there can be literally _dozens_ of disabled entities. Always showing disabled entities would be a lot more annoying in those cases imo.

**Comment by spacegaier** [comment]
We could also not do the first point, and instead keep the disabled ones hidden by default and I could adjust the logic for the second point to also show the information about hidden objects if we have an active filter for a certain integration / config_entry. Then with a click on the "Show All" button the user could easily see all if required. Not sure though how that will look UI screen space wise if we have both a filter info and a hidden entity info box.

I am fine either way.

**Comment by SeanPM5** [comment]
They both have drawbacks, but I lean towards just always showing the disabled entities here. Mostly because of the current mobile UI: 

![image](https://i.imgur.com/rAosvzK.jpg)

This top area is already overly cramped as-is on mobile and can barely fit the "Clear" button which is just a few characters. There's not going to be enough room to display the "X hidden entities - Show All" button idea. 

So maybe just show them automatically at all times like point number 1 suggested. I personally don't like that though because it's inconsistent with how disabled entities behave everywhere else (click-to-show). And that behavior would feel like a bug honestly, since it's ignoring the users "Show disabled entities" checkbox setting. But I guess as a temporary stopgap measure it's OK.

**Comment by spacegaier** [comment]
It is not technically ignoring the users checkbox settings, since I in fact am setting that checkout automatically to actually show the disabled entities, so in case an integration has too many entities and they only want to see the enabled ones, they can uncheck the box. So we are not completely forcing them to see the disabled ones, they will now just be visible by default when filtered for a certain integration.

But I agree with the rest of your points.
