### ISSUE TITLE
input_datetime objects' new History tab shows incorrect entries

### ISSUE THREAD

**Issue by theorician** [home-assistant/frontend#7309]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Opening a 'helper' (e.g. an input_datetime)'s more info dialog ([this new feature introduced in 0.115.x](https://www.home-assistant.io/blog/2020/09/17/release-115/#updated-more-info-dialog)) and clicking the History tab shows the full history of when each change was made, as expected. However, each value is the current value instead of the historic one, e.g. if I just changed an input_datetime from 06:00 to 07:00, the history will show _all_ previous times as 07:00. 

## Expected behavior

History tab should show the correct historical values.

## Steps to reproduce

1. Create a helper (mine were created in yml rather than via the UI, not sure if this makes a difference.)
2. Navigate to Lovelace
3. Add the helper to Lovelace.
4. Edit the helper's values a few times
5. Click on more info for the helper.
6. Click on the history tab
7. See that all historic values are the same.

## Environment

- Home Assistant release with the issue: 0.116.x
- Last working Home Assistant release (if known): N/A - probably didn't work in 0.115.x either, feature introduced then.
- Browser and browser version: Firefox latest
- Operating system: MacOS Catalina latest

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Also seem to happen in the regular "History" panel. 

As far as I could trace the issue: The history call is using `minimalResponse` so the attributes are not returned for all state changes (and even if they were, there is coding in `processTimelineEntity()` that would ignore it currently).

In the end however `computeStateDisplay()` is using the attributes for `input_datetime` => since only attributes for the very first and very last state change are present, only those can be used => wrong display result.
