### ISSUE TITLE
Custom components not loading properly

### ISSUE THREAD

**Issue by paulhobbel** [home-assistant/frontend#7384]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I just updated from 0.115.2 -> 0.116.4. After updating I noticed some custom components not loading in Lovelace. Upon further expection it seems like it's failing to find custom components:
![html](https://user-images.githubusercontent.com/2983567/95609770-93a27300-0a5f-11eb-9a12-6fcf39a21f26.png)

The custom components will only show when resizing the screen of pressing edit.

## Expected behavior

Normally it should just load custom components without any issue

## Steps to reproduce

1. Add a custom component, took [simple-thermostat](https://github.com/nervetattoo/simple-thermostat) as example here.
2. Navigate to Lovelace
3. Add a new card with the custom component
4. Reload the page
5. Card won't show up unless pressing edit/resizing

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known): 1.114
- Browser and browser version: Chrome 86.0.4240.75
- Operating system: Windows 10 2004

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by paulhobbel** [comment]
Okay so this seems to be a Chrome and App related issue, the issue does not occur in Firefox 81.0 and Edge 86.0.622.43

**Comment by spacegaier** [comment]
Perhaps tied to this? https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/

**Comment by iantrich** [comment]
This is an issue the card must address

**Comment by maxwroc** [comment]
Hey guys I have exactly the same problem (I'm author of few custom cards) and I have noticed these issues since v116. 

The linked info is about lazy loading of more-info dialogs if I understand it correctly. Or is it applicable to any of the internal custom page elements defined on HA side? In other words if my card uses e.g. <ha-card> can it be affected?

I don't use more-info control in any way but still I experience the same issue. It happens not only to my custom cards but as well other ones like mini-media-player (which is quite popular).

Few observations:
* The problem occurs only when the custom card is loaded on the initial view. When the card is on another panel/tab it loads fine. It is very easy to repro when you are on the page/panel with custom card and you just hit refresh button in your browser.

* In this example I have 4 github-flexi-cards and only last two are rendered:
  
  ![image](https://user-images.githubusercontent.com/8268674/96475239-acfbaa00-122b-11eb-8602-5eaafa3da059.png)

* Cards do appear when resizing window - when there is a switch from multiple column view to single one or the opposite

* According to the below code the error card should be shown after 2s when the custom element is not defined but it doesn't happen:

  https://github.com/home-assistant/frontend/blob/a2ec878ef0b02076004cac7a22cc3585f287cfac/src/panels/lovelace/create-element/create-element-base.ts?fbclid=IwAR36TMNp38bdbgjjtAPvp7lQ1aMBiY_TjKVln9g_gV3FC4Td5zNvOu1zNwg#L94

  This means, I think, that the card code is actually available but probably handler of `ll-render` event fails. I can debug it further but TBH I haven't played with HA frontend code yet and the sources are crunched so debugging in browser quickly is painful.

* I can repro the issue in all the browsers which I have: Chrome 86.0.4240.75, Edge 86.0.622.43, FF 74, Android Chrome, iOS Chrome/Safari
    * Issue happens less often on yaml based dashboards and more often on UI controlled ones

* I thought that maybe the reason is the other breaking change which was introduced in v116 that LitElement cannot be extracted from hui-view. I wasn't using it but a different one - home-assistant-main. So I gave it a try and switched to hui-masonry-view but no luck. I have tried to do it without this hack and include lit-element in my bundle but still the problem is there. Anyway if that is the problem I think I wouldn't see the card at all.

In case anyone has a spare min to take a look at this card's code (which is quite small and simple) adding link
https://github.com/maxwroc/github-flexi-card/tree/master/src

I have posted question about this issue on few FB HA groups and people were saying they experience exactly the same problems with (not mine) custom cards

**Comment by maxwroc** [comment]
I have removed all the external dependencies (I was using `ha-card` and `ha-icon` custom element) and still the problem is there :(

**Comment by maxwroc** [comment]
The same issue happens with the boilerplate-card from here: https://github.com/custom-cards/boilerplate-card

**Comment by bramkragten** [comment]
Are you using any other custom cards? Can you try it with just this card

**Comment by maxwroc** [comment]
So I have removed all the references to any other js files in ui-lovelace.yaml and left only the bolerplate-card.js, I have created dedicated page for this card only and the result is the same

![image](https://user-images.githubusercontent.com/8268674/96638354-e01b6780-1317-11eb-8bb6-79f4845b27f7.png)

**Comment by maxwroc** [comment]
Thanks for the quick fix! Looking forward to testing it

**Comment by ministryofsillywalks** [comment]
I have the same issue on various devices and browsers.
Firefox on Windows, Android App on various different phones.
For me two custom cards were giving issues 
custom:weather-card and custom:button-card
however custom:mini-graph-card on the same page always loads
Looking forward to test the fix. Just wanted to give some more data points in case its useful.
