### ISSUE TITLE
Quick bar should disable search on page in Firefox

### ISSUE THREAD

**Issue by kukulich** [home-assistant/frontend#7536]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have "Search for text when I start typing" option enabled in Firefox (Options -> General Tab -> Browsing)
The quick bar should block the search. It should be possible because it's blocked on https://community.home-assistant.io/  😃 

## Expected behavior

The search on page should be blocked when typing "e" or "c"

## Steps to reproduce

1. Enable Options -> General Tab -> Browsing -> "Search for text when I start typing"
2. Type "e" or "c"

## Environment

- Home Assistant release with the issue: 0.117.0
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 82.0.2
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![Clipboard01](https://user-images.githubusercontent.com/260445/97684936-2ea7cf00-1a99-11eb-9d9a-c6be27d80c6c.png)

**Comment by donkawechico** [comment]
Yeah I don't think we can override that behavior without taking a huge step backward with all the other concerns we have to balance with keyboard shortcuts. Primarily with accessibility: keyboard users (users who have difficulty using a mouse, for example) rely on features like this to navigate around a page quickly.

I don't know for sure, but I don't think the community pages don't technically override the "search when typing" feature, specifically. I think it seems that way simply because the community pages override the browser's find bar, which is what firefox tries to launch when you type with your setting enabled.

If I'm right about that, then for us to "disable" search-when-typing we'd have to override the "Find in page" shortcut as well, and that's just not something we'd do.

In the future, we may end up adding the ability to customize these shortcuts. But there's still debate about whether to do that. In the meantime, I would suggest using a firefox extension like Saka Keys to override / remap shortcuts for specific URLs.

**Comment by kukulich** [comment]
> I don't know for sure, but I don't think the community pages technically override the "search when typing" feature. I think it seems that way simply because the community pages override the browser's find bar, which is what firefox tries to launch when you type with your setting enabled.

I don't know how it works on community pages but:

- I type some letter - it does nothing
- I use `ctrl + f` - it opens custom search bar. Second `ctrl + f5` opens the browser search bar.
- I did not find any shortcut that does not work.

**Comment by donkawechico** [comment]
> I type some letter - it does nothing

Odd. I just tried this in Firefox with "Search for text when you start typing" enabled, and I'm still seeing the search behavior occur while I'm typing.

Try going to this specific post and typing a word you see in the post (I used "install"): https://community.home-assistant.io/t/home-assistant-resources/27

**Comment by donkawechico** [comment]
Either way, my answer is going to be the same. Adding shortcuts to web applications is a very delicate process, and we're still learning all the complexities.

For now, we're only supporting OS, browser, and accessibility-related issues. If you experience issues caused by add-ons, non-default browser settings, or the like, you'll have to either find a workaround, disable shortcuts in HA user profile, or wait until/if we decide to make shortcuts customizable. 

That said, I just tested two great alternatives for you (first is my favorite):

1. Type `e` then `tab` and start typing your filter string. No need to click into the quick-bar text field first.
2. Install [shortkeys](https://addons.mozilla.org/en-US/firefox/addon/shortkeys/) in Firefox. Then add a rule for `e` and `c` that "Does Nothing" but _only_ for your HA url.
<img src="https://user-images.githubusercontent.com/1480827/97759466-59584e80-1abe-11eb-8a9c-97313c06b9fc.png" width=50% />
<img src="https://user-images.githubusercontent.com/1480827/97759762-e6030c80-1abe-11eb-8e4c-d33f3086139d.png" width=50% />

**Comment by kukulich** [comment]
Ok, I understand your opinion :)
