### ISSUE TITLE
Small graphical glitch on safari/ios app on iPhone

### ISSUE THREAD

**Issue by deluxestyle** [home-assistant/frontend#7602]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
with 0.117 compact header has a small glitch in the tabs view on iPhone (both safari and ios App) - see screenshot
![PNG-Bild (1)](https://user-images.githubusercontent.com/662779/98268038-5791fd80-1f8c-11eb-80d6-f5119c80d003.png)

## Steps to reproduce

happens in safari and ios App.

## Environment

- Home Assistant release with the issue: since 0.117
- Last working Home Assistant release (if known): 0.116
- Browser and browser version: ios 14.1 - safari + ios App (latest version)
- Operating system: ios

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

N/A

**Comment by deluxestyle** [comment]
no one looking into this?

**Comment by maykar** [comment]
https://github.com/home-assistant/frontend/pull/7470 May fix the issue, I didn't want to link it as a "fix" since I don't have any devices to test it at the moment. I believe this to be related to the styling of the tab indicator that currently uses sub pixel positioning, which safari doesn't handle well. If that pull request isn't merged I will make another that specifically addresses this once I'm able to test on an apple device.

**Comment by maykar** [comment]
The styling changes to the tab indicator were added in the latest beta 0.118.0b0. Would be interested to know if this is still an issue.

**Comment by deluxestyle** [comment]
@maykar can I add the changes manually to my existing 0.117 installation? then I would be able to test it

**Comment by deluxestyle** [comment]
@maykar thank you. 0.118 fixed the issu
