### ISSUE TITLE
FAB button too close to the screen

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#7662]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The new FAB button with label is too close to the screen edge:
![image](https://user-images.githubusercontent.com/1368405/98866454-41dd7600-246d-11eb-9013-3089ac004a16.png)

BTW on the lovelace page, the button has padding:
![image](https://user-images.githubusercontent.com/1368405/98866877-ed86c600-246d-11eb-8482-be32c3570e2e.png)

So on following pages there is not enough padding:
- Integrations
- Automation

On these pages it's fine:
- Helpers
- Scripts
- Scenes
- Lovelace 
- Users
- Zone
- People
- Area
- Tags

## Expected behavior

Add some distance between the screen edge and the button (I would suggest the same as the bottom distance)

## Steps to reproduce

Update to latest beta 0.108.0b go to the automation or integrations page
## Environment

- Home Assistant release with the issue: 0.108.0b0
- Last working Home Assistant release (if known): -
- Browser and browser version: Edge 87
- Operating system: Windows 10

## State of relevant entities

```yaml
none
```

## Problem-relevant configuration

```yaml
none
```

## Javascript errors shown in your browser console/inspector

```txt
none
```

## Additional information

**Also I noticed that on the "People" page, the FAB text is "Add Person" and not "Add People"**

**Comment by spacegaier** [comment]
They are all in the same position. It is just the fact that for integrations and automations there is an element on that page that often shows a scrollbar, but that is not affecting the fab. The same would happen if you were to have enough areas, scenes, ... which I think is correct.

Reg. "Add People": That would sound a bit weird, since people is basically a plural word, but since we are only adding a single "instance" I prefer the text "Add Person" that I had added to the fab.

**Comment by TheZoker** [comment]
Ok yes I see the problem, but shouldn't the FAB move to the left, when the scrollbar is shown? 
The way it currently is just does not look very nice. A gap between the edge of the screen (including the scrollbar) and the FAB should always be there.

The other content also moves with the scrollbar and does not get overlayed by the scrollbar, so why shouldn't the FAB move as well? 

![Screenshot_2020 11 15_00h54m17s_009_](https://user-images.githubusercontent.com/1368405/99159605-0bf2f880-26de-11eb-8745-08f539447706.png)


![Screenshot_2020 11 15_00h55m55s_010_](https://user-images.githubusercontent.com/1368405/99159606-0c8b8f00-26de-11eb-8b96-6b2c305c6bb5.png)

As you can see on the screenshots above, the content moves with the scrollbar but the FAB does not. So what do you think?

**Comment by spacegaier** [comment]
I understand what you are hinting at, but I think that behavior is correct. The content ("Execute" plus info and editor buttons) moves since it is part of the element that actually contains the scrollbar. However a FAB (as the F in the name applies) is meant to be floating and not care about what is behind it. We are following here the Material Design Guidelines and they specify that the fab should be 16px from the right and from the bottom which is what we do:

https://material.io/components/buttons-floating-action-button#specs
