### ISSUE TITLE
Bug : Entity search from Configuration Menu

### ISSUE THREAD

**Issue by mat4444** [home-assistant/frontend#7761]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The search function in Configuration --> Entities does not work well if the window is reduced to a small resolution (typically when the Integration, Devices, Entities and Room icons are at the bottom of the window). In this case, most search requests will give "No data", whereas if we expand the window, the search results will be displayed.
The same behavior happens in a small Chrome or Firefox window, and always in the mobile app (Android).
![ezgif com-gif-maker](https://user-images.githubusercontent.com/53400792/99883409-96c87b80-2c27-11eb-9b37-8293442be10e.gif)

## Expected behavior

The search results must be the same regardless of the window resolution

## Steps to reproduce

1. Go to Configuration -> Entities
2. In the search bar, type 'automation'
3. Play with the window size or zoom level until the results appears.
## Environment

- Home Assistant release with the issue: 0.118.2
- Last working Home Assistant release (if known): unknown, don't know if it ever worked
- Browser and browser version: Chrome 87.0.4280.66
- Operating system: Windows 10

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

No error noticed in the console

## Additional information

N/A

**Comment by spacegaier** [comment]
I haven't checked in detail but I think the following happens (would match your GIF and my tests):

1. If the window is in wide-mode, then you have multiple columns (let's focus on "Name" and "Integration" for this example). If you now filter for "automation" you will see all entries where any column contains the string "automation". In your case those are all entities of integration "automation". 
2. If you now make your window narrow, the column "Integration" is removed to optimize the screen space and only "Name" is left. Since however, none of your entities have "automation" in their name, nothing is shown anymore. 

**To verify**: Can you please add an entity that has the string "automation" in the name?

If my assumption is true, it might make sense for the narrow mode search logic to still check the entity ID and integration even though they are not rendered as separate columns in narrow screens.

**Comment by mat4444** [comment]
I created another automation named automation_test. It is the only result in narrow mode, so it seems that your assumption is correct. The search function filters only based on the columns displayed on screen.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53400792/99884055-7bf80600-2c2b-11eb-92f0-97b11484067c.gif)
