### ISSUE TITLE
Quick bar - All words in "command palette" begin with capital letter

### ISSUE THREAD

**Issue by cholek3** [home-assistant/frontend#7937]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Every single word in Quick Bar "command palette" (c) begin with capital letter, even though in Lokalise it is correct (see examples).

## Expected behavior
Only first word should have CAPITAL letter and Names (such as Integrations, Helpers, etc). Capitalisation of every single word has also impact on translation, as very often you don't start every single word with capital letter.

## Environment

- Home Assistant release with the issue: 0.118.5 and 1.0.0b3
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome 87.0 and Microsoft Edge 87.0
- Operating system: 
## Examples
Lokalise (CORRECT):
![github1](https://user-images.githubusercontent.com/43534386/101707423-15744400-3a83-11eb-8cdd-7d63d875c48b.jpg)

Quick Bar:
![github2](https://user-images.githubusercontent.com/43534386/101707440-1c9b5200-3a83-11eb-890e-aae92975be67.jpg)

## OR
Lokalise (CORRECT):
![github4](https://user-images.githubusercontent.com/43534386/101708108-810ae100-3a84-11eb-9487-6534500e8ee0.jpg)

Quick Bar:
![github3](https://user-images.githubusercontent.com/43534386/101708075-77817900-3a84-11eb-896a-913031871130.jpg)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Work on the related PR to use chips in the QB has been picked up again. That one should solve this issue. 
https://github.com/home-assistant/frontend/pull/7692

**Comment by donkawechico** [comment]
PR merged... BUT... It won't completely resolve this ticket. Not yet.

That PR resolved the "verb" part of this problem.  E.g. "**Navigate To** Developer Tools").

The "nouns" are still being capitalized for each word. If we didn't have that, you would see this:

* "[Navigate] Developer Tools"
* "[Reload] Input booleans"
* "[Reload] timer"

This is because the strings we're pulling for these labels weren't written with this use-case in mind so they're wildly inconsistent in their casing.

Capitalizing each word, for now, is the easiest way to give us casing consistency. It obviously has a few small edge-cases, which we'll try and think of a solution for in future work.
