### ISSUE TITLE
homeassistant.loader.IntegrationNotFound: Integration '' not found.

### ISSUE THREAD

**Issue by scibi** [home-assistant/frontend#7979]
After trying to repeat steps from live demo on conference (creating new automation using ZHA - IKEA five button remote for lights blueprint) I'm getting following exception:

```txt
2020-12-14 00:01:36 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=automation, service=reload, service_data=>
2020-12-14 00:01:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139745441034400] Integration '' not found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 81, in async_get_device_automation_platform
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 47, in async_get_integration_with_requirements
    integration = await async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 491, in async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration '' not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 202, in reload_service_handler
    await _async_process_config(hass, conf, component)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 512, in _async_process_config
    await async_validate_config_item(
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 74, in async_validate_config_item
    config[CONF_ACTION] = await script.async_validate_actions_config(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 143, in async_validate_actions_config
    return await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 187, in async_validate_action_config
    choose_conf[CONF_SEQUENCE] = await async_validate_actions_config(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 143, in async_validate_actions_config
    return await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 158, in async_validate_action_config
    platform = await device_automation.async_get_device_automation_platform(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 84, in async_get_device_automation_platform
    raise InvalidDeviceAutomationConfig(
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig: Integration '' not found
```

Right now I'm not able to load my automations...

## System Health

version | 2020.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.83
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 14, 2020, 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.8
-- | --
update_channel | stable
supervisor_version | 2020.12.6
docker_version | 19.03.13
disk_total | 15.0 GB
disk_used | 9.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (8.10.0), AdGuard Home (2.6.1), Let's Encrypt (4.11.0), Visual Studio Code (2.9.1), NGINX Home Assistant SSL proxy (3.0.1), Git pull (7.12), Grafana (5.3.6), ESPHome (1.15.3), Check Home Assistant configuration (3.6.0), AirCast (2.3.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 0

</details>

**Comment by thundergreen** [comment]
Solved my issue! Great and Thanks!

**Comment by sebade** [comment]
I had exactly the same problem. Same blueprint, click on action and directly click on save -> automations could not be loaded anymore.  I was near a heart attack but removing the created automation in the yaml file solved the problem.

**Comment by lucimart** [comment]
Hi I had this same bug just now version 2021.4.5

**Comment by yrplus** [comment]
Hi I had this same bug just now version 2021.6.5

**Comment by ogajduse** [comment]
I am hitting the same issue.

Can any of HA devs suggest any hotfix for this issue or provide a workaround to get functional *Automations* page?

Let me know if you need more info, I am happy to provide it.

## Reproducer:
Import the following blueprint.
[![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgist.github.com%2Fsbyx%2F1f6f434f0903b872b84c4302637d0890)
Create automation using this blueprint. Choose "Device" as an action for the automation and leave the data fields blank.

## Actual results
All automations gets greyed out. After the HA restart, *Automations* button disappears completely.

## Expected results
If there is an bug in a blueprint/automation, HA should report it to the user instead of locking itself and being unable to provide *Automations* setting to the user.

## System Health

version | core-2021.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Prague

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4922
Installed Version | 1.12.4
Stage | running
Available Repositories | 849
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.6
disk_total | 457.7 GB
disk_used | 30.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.7.1), Mosquitto broker (6.0.1), AdGuard Home (4.1.6), chrony (2.1.0), ESPHome (1.19.2), Grafana (7.0.1), InfluxDB (4.1.1), Node-RED (9.1.4), Log Viewer (0.11.0), Visual Studio Code (3.4.1), WireGuard (0.5.1), Terminal & SSH (9.1.3), Home Assistant Google Drive Backup (0.104.3), Glances (0.12.2), SSH & Web Terminal (8.2.4), ArgonOne Active Cooling (0.19), File editor (5.3.1), Nginx Proxy Manager (0.11.0), MariaDB (2.4.0), Syncthing (1.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 4
views | 7
mode | storage

</details>

<details><summary>meteoalarmeu</summary>

Reach API endpoint | ok
-- | --

</details>

**Comment by gerbenp** [comment]
Got the same issue as ogajduse describes. I have added the xiaomi opple blueprint, when i added it, the automations are gone. When i disabled that blueprint the automations are back.

**Comment by ajstew444** [comment]
just had this on core-2021.8.6. Glad I found this thread

**Comment by bramkragten** [comment]
This is not a frontend issue. Please open an issue in the core repo.

**Comment by scibi** [comment]
@bramkragten this issue was originally reported in core but @frenck moved it to frontend. There should be validation added that prevents adding empty actions. Probably it should be checked in the frontend but backend should check configuration too.

**Comment by ogajduse** [comment]
@bramkragten I fully agree with @scibi. If you feel that this is not a frontend issue, please move it back to home-assistant/core.
