### ISSUE TITLE
Broken media_player.play_media service

### ISSUE THREAD

**Issue by skumka** [home-assistant/frontend#8023]
After a recent upgrade of HomeaAssistant integration with Roon Labs it is not possible to run service media_player.play_media with arguments which worked before:

entity_id: media_player.homepod
media_content_type: radio
media_content_id: Radio Nowy Swiat

looks like type 'radio' stopped to work for media_player

This issue broke my automations.

**Comment by frenck** [comment]
Hi there @skumka!

Thanks for opening an issue. However, your issue seems not frontend related, but core related. Could you please open an issue here:

<https://github.com/home-assistant/core/issues>

If you create an issue on the core repository, it will provide you an issue template you can use; that gives us the necessary information to dig into a possible issue.

Happy Holidays 🎄  Thanks already! 👍
