### ISSUE TITLE
Creating Automation through UI creates incorrect YAML

### ISSUE THREAD

**Issue by tux43** [home-assistant/frontend#8029]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

When I create a state sensors using an Attribute it incorrectly puts quotes around the state therefore treating it as a string rather than a boolean. Refer to [post](https://community.home-assistant.io/t/condition-based-on-binary-sensor-attribute/258064)

<img width="621" alt="Screen Shot 2020-12-22 at 9 01 43 am" src="https://user-images.githubusercontent.com/53364421/102828596-00a99000-4435-11eb-9391-196b0e571b00.png">

<img width="619" alt="Screen Shot 2020-12-22 at 9 01 56 am" src="https://user-images.githubusercontent.com/53364421/102828682-39e20000-4435-11eb-9a0c-bd1b98403ebb.png">

## Expected behavior

The quotes should not be around the true state, this does not work.

<img width="665" alt="Screen Shot 2020-12-22 at 9 09 01 am" src="https://user-images.githubusercontent.com/53364421/102828797-7f9ec880-4435-11eb-92d7-af0c2cc9a4e3.png">

## Steps to reproduce

Create automation using the optional state attribute. I was using the binary sensor which comes with MacOS 
<img width="430" alt="Screen Shot 2020-12-22 at 9 11 21 am" src="https://user-images.githubusercontent.com/53364421/102828898-bc6abf80-4435-11eb-9e58-25ce7e4648c4.png">

## Environment

- Home Assistant release with the issue: 2020.12.1
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Safari MacOS
- Operating system: MacOS 11.1

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Problem is related to this backend change that two months ago removed the requirement for attribute state condition values to be strings.

https://github.com/home-assistant/core/pull/41261

**Comment by spacegaier** [comment]
I think it is not actually the frontend that is adding those quotes. Instead it seems to be coming from the `yaml.safe_dump()` that the backend calls to write the `automations.yaml` file.

https://github.com/home-assistant/core/blob/2ee2f85574885b684fe638add25428026f2313e1/homeassistant/util/yaml/dumper.py#L13-L15

We will need to add some logic here that will convert the `'true'` / `'false'` that the frontend sends to Python values `True` / `False` so that they get correctly dumped as `true` / `false`.
https://github.com/home-assistant/core/blob/2ee2f85574885b684fe638add25428026f2313e1/homeassistant/components/config/automation.py#L53

**Comment by emontnemery** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/10811
