### ISSUE TITLE
Thermostat Card - set temperature by slider is not working when temperature_high_command_topic, -state or/and temperature_low_command_topic, -state is configured and used.

### ISSUE THREAD

**Issue by Frans1960** [home-assistant/frontend#8036]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The set temperature, by slider, is not working when temperature_high_command_topic, -state or/and temperature_low_command_topic, -state is configured and used.
You can change the temperature by opening the card and do it by the up/down buttons.
And the description is missing, so you have to test/see what is does.

## Expected behavior
Its working when the temperature_high_command_topic, -state or/and temperature_low_command_topic, -state are not configured.
I use the MQTT Climate module and commented the temperature_high_command_topic, -state or/and temperature_low_command_topic, -state -. See the attachment

## Environment

- Home Assistant release with the issue: See under System Health
- Last working Home Assistant release (if known):
- Browser and browser version: MS Edge
- Operating system: Windows 10
## System Health

version | 2020.12.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.8.16-sunxi
arch | armv7l
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4959
Installed Version | 1.9.0
Stage | running
Available Repositories | 702
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Armbian 20.08.17 Buster
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 54.8 GB
disk_used | 4.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.12.4), File editor (5.2.0), Samba share (9.3.0), Mosquitto broker (5.1), Node-RED (7.2.11)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 4
resources | 2

</details>
## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Frans1960** [comment]
[climate.txt](https://github.com/home-assistant/frontend/files/5739305/climate.txt)
The config file I use

**Comment by Mithras** [comment]
I'm facing the same issue after migrating to Z-Wave JS.
![image](https://user-images.githubusercontent.com/2098029/110424601-e6f10f80-8057-11eb-82ec-2709be330f3f.png)
It seems that having both `temperature` and `target_temp_high`/`target_temp_low` set breaks the card sliders
![image](https://user-images.githubusercontent.com/2098029/110424500-c32dc980-8057-11eb-974d-8bf0eb25dec7.png)

**Comment by Mithras** [comment]
I tried to remove `target_temp_high`/`target_temp_low` from the state in dev tools like such:
![image](https://user-images.githubusercontent.com/2098029/110425687-9bd7fc00-8059-11eb-8072-6f9671d5eaac.png)
and the card works as expected until Z-Wave JS brings `target_temp_high`/`target_temp_low` back (which happens immediately after you move the slider).
I think the card should ignore `target_temp_high`/`target_temp_low` presence and instead rely on `mode`

**Comment by quinnhosler** [comment]
I am having this same issue, and it recently started after upgrading my ZWaveJS version and to the latest homeassistant (2021.3). 

Looking into this a bit, my guess would be the issue stems from the combination of the underlying [Round Slider](https://github.com/thomasloven/round-slider) and the fact that ZWaveJS is supplying `target_temp_high` and `target_temp_low` arguments all the time. (even though `target_temp_high` is empty/null when not in use.)

Essentially, Round Slider states it requires both `low` and `high` properties in order to show the dual sliders, HOWEVER I am unable to find the condition that checks for the `high` property. I can only find the condition for the low, which if present triggers it to show two sliders. 

I believe the solution to the answer would be either for Round Slider to implement a check for a valid `high` temp OR for ZWaveJS to only supply `target_temp_high` and `target_temp_low` when the mode is `heat_cool`.

Unfortunately for me, I don't quite have the knowledge base to test my guess, but would certainly be interested in the results.
