### ISSUE TITLE
Keep dashboard tab selected after move

### ISSUE THREAD

**Issue by Erriez** [home-assistant/frontend#8057]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

A dashboard tab remains selected on the current position after a move.

## Expected behavior

Keep the selected tab selected after a move (reordering).

Keep the tab selected after move. Then it is easy to click the arrow buttons to move the tab to the left and right.

## Steps to reproduce

![HomeAssistantKeepSelectionMovedTab](https://user-images.githubusercontent.com/8849873/103414825-cb611880-4b7f-11eb-8078-dbdb08c645e4.gif)

## Environment

- Home Assistant release with the issue: Home Assistant OS: 2020.12.1; Home Assistant OS 5.8
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Any browser
- Operating system: Not applicable

## State of relevant entities

Not applicable.

## Problem-relevant configuration

Not applicable.

## Javascript errors shown in your browser console/inspector

Not applicable.

## Additional information

See screen capture.

**Comment by spacegaier** [comment]
I can confirm the issue, but my initial attempts at fixing all failed 😞.

**Comment by Erriez** [comment]
@spacegaier Thanks for trying to fix it. Can you share your findings? Maybe someone can help you.

**Comment by spacegaier** [comment]
Here the views are swapped, but only in a local variable. But even if I change the class member variable it does not work (and even try to "manually navigate to the new view"), because a debounced later rendering goes to the wrong view.

https://github.com/home-assistant/frontend/blob/6b20bb967bb216fe1b2fb6927f24994323648544/src/panels/lovelace/hui-root.ts#L680

https://github.com/home-assistant/frontend/blob/6b20bb967bb216fe1b2fb6927f24994323648544/src/panels/lovelace/hui-root.ts#L572-L573
