### ISSUE TITLE
Power Button doesn't take effect when Kodi is in idle state

### ISSUE THREAD

**Issue by Thunderbird2086** [home-assistant/frontend#8146]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When Kodi is in idle state, power button on Media Control card turns off kodi while one on Entities Card doesn't.  Power button on Entities cad turns off Kodi when Kodi is playing something.
Originally from home-assistant/core#37195

## Expected behavior
When power buttons is clicked, Kodi should be turned off unless Kodi is off

## Steps to reproduce
1. Add Kodi media player to an entities card 
2. wait for a few minutes until Kodi falls in idle state
3. click power button on the entities card to turn off kodi
![Screen Shot 2021-01-12 at 21 11 29](https://user-images.githubusercontent.com/37539914/104313027-c8b8d880-551a-11eb-8cb3-d68163bad525.png)

## Environment

- Home Assistant release with the issue: 2021.1.1
- Last working Home Assistant release (if known): I don't remember
- Browser and browser version: 
   - Safari 14.0.2
   - FireFox 84.0.2
- Operating system:
   - MacOS
   
## State of relevant entities

![Screen Shot 2021-01-12 at 21 07 31](https://user-images.githubusercontent.com/37539914/104312613-33b5df80-551a-11eb-85f4-1cc087a1aa50.png)

```yaml
friendly_name: Vero 4K
supported_features: 186303
```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Thunderbird2086** [comment]
fyi, @verglor @OnFreund

**Comment by OnFreund** [comment]
Thanks @Thunderbird2086. As mentioned in the original issue, I doubt this has anything to do with Kodi or the Kodi integration. This probably applies to any media player platform.

**Comment by spacegaier** [comment]
I checked in the coding and the conditions are indeed different (independent of which media player integration is used):

**Media control card**: Off button is shown if state !== "off" and has no further checks upon clicking it.

**Entity media control row**: Off button is shown if state !== "off" and upon click it only triggers the "turn_off" service if the state !== "off" and !== "idle".

TBH the row makes more sense for me, because my understanding was that media players that can "idle" can never turn off since they are service based rather than hardware (e.g. Spotify can only be in "playing", "paused" or "idle"). Unfortunately, the docs are not mentioning anything regarding the states: https://developers.home-assistant.io/docs/core/entity/media-player/

Kodi on the other hand knows "off", "playing", "paused" and "idle". So "idle" should be allowed to turn off Kodi.

In the end `SUPPORT_TURN_OFF` should be enough to govern if the button should be shown and work. So you could argue that the !== "idle" check for the row should be removed.

**Comment by OnFreund** [comment]
Thanks @spacegaier.
Is there a better state than "idle" when not playing anything? If there is, I can change the Kodi integration (and Volumio, and possibly a few others), but if not, I don't think "idle" can be reserved solely for media players that can't be turned off (and as you mentioned, that's what `SUPPORT_TURN_OFF` is for).

**Comment by spacegaier** [comment]
TBH not really sure either way.

The generic media_player integration makes it sound as if idle is more like stand-by:

https://github.com/home-assistant/core/blob/2a7a419ff3e3f964608d16f6bf77774f040f6578/homeassistant/components/media_player/__init__.py#L739

But since there is a dedicated "STATE_STANDBY" that is e.g. used by AndroidTV, that cannot (anymore) be the case.
Some other media players are using "idle" where also "on" could be used. Roku uses "idle" when in screensaver mode (which is different from stand-by for that integration). Other integrations start with "on", but go to "idle" when playback stopped (not paused) or stay in "idle" if they cannot be switched off.

Overall I haven't seen anything that would speak against considering "idle" as "on" as far as the on/off button is concerned. Plus we already do it that way in the frontend for the media card. I will create a PR.
