### ISSUE TITLE
Capitalization in beta

### ISSUE THREAD

**Issue by larena1** [home-assistant/frontend#8275]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Latest beta seems to have introduced capitalization of names in entity rows, e.g. iPhone becomes IPhone. It's fine though in other places like modals, logbook or history panel. Is it meant to be like this?

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Yes, we added that with PR https://github.com/home-assistant/frontend/pull/7962 to fix it for the auto-generated dashboards.

Possible solution: Do not auto capitalize in CSS, but instead in JS by checking if any character in the first word is already capitalized and in that case leave as is? That should solve it for brand names, but computation wise is a bit heavier (regex?) than just capitalizing the first letter.

**Comment by frenck** [comment]
Anything with automatic capitalization will fail at things. Either do it, and accept it is not perfect ever, or don't do it at all.

If one starts making fixes to logic like this, the story never ends and never ends up being solved either.

IMHO it is a choice: it is what it is or revert it an accept that...

**Comment by spacegaier** [comment]
If we don't go for a more elaborate approach, then I personally prefer the logic in the beta, because is going to be correct for a lot more people overall.

**Comment by larena1** [comment]
I'd vote for reverting it. There are quite a lot words with lowercase initial letter like iPhone, iMac, eSIM and many others. And it's not even consistent throughout the whole frontend (modals, logbook, history etc.)

It's rather feels like an ugly hack this way

**Comment by spacegaier** [comment]
Thought about it some more: The consistency is the stronger argument in my eyes. In my reply yesterday, I was too focused on the use case that the original issue and PR addressed: The automatic dashboard where the frontend was always removing the redundant area in the entity name.

Perhaps the auto capitalization should directly be incorporated there, instead of the global CSS. That way we do not override the existing proper naming for manually created dashboards, while still addressing the original issue that the auto-generated dashboard should look nice as well.

I will push a PR as an proposal.
