### ISSUE TITLE
Add card button covering Up/Down arrows on Mobile

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8523]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

on mobile, when editing the UI, the up/down arrows of the bottom card are covered by the Blue Add Card button

### Describe the behavior you expected

not to cover the arrows

### Steps to reproduce the issue

1. click top right menu: Edit Dashboard
2. scroll down
3. and see
...

### What version of Home Assistant Core has the issue?

any

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

follow up of https://discord.com/channels/330944238910963714/427516175237382144/816619519861587989

![20210303_103303000_iOS](https://user-images.githubusercontent.com/33354141/109793796-67a5ab00-7c15-11eb-9568-5e0ccc23f20a.png)

**Comment by spacegaier** [comment]
I was about to post the text below, but then I tested it on my instances, and there I cannot reproduce it. On Win with FF and Chrome it never overlays and neither does it in the Android app. Not sure if something was changed here recently.

=> Does the issue still appear? Perhaps only for certain browser / OS?

<hr />

_Not sure if/what we can do here. The floating blue button position is the default one I think. You can move the card above down temporarily to switch them and then access the buttons, but that is only a manual workaround of course._

_Not sure if we could/should force he container element to be higher so that there is some empty space at the bottom for the float to float around in._

**Comment by Mariusthvdb** [comment]
yes, it does, I had recently tested to see if it should be closed. It does seem to allow for some extra movement up and down though, so this:

![20210603_113033000_iOS](https://user-images.githubusercontent.com/33354141/120638243-2caf4f80-c470-11eb-9154-9d5abca9f1a0.png)

can be moved to:

![20210603_113103000_iOS](https://user-images.githubusercontent.com/33354141/120638267-35078a80-c470-11eb-861a-2d3d4b7d3500.png)

which, though probably not intentionally, solves the issue ;-)

**Comment by spacegaier** [comment]
In italic I meant to temporarily switch the hallway with the garage card to access the menu buttons and then switch back. But sounds like that is not even required based on your screenshots.

**Comment by Mariusthvdb** [comment]
yes, I guess the oddity of the system comes to the rescue, Ill close. thanks for your time and suggestions.
