### ISSUE TITLE
Issues with select dropdown on mobile

### ISSUE THREAD

**Issue by alekslyse** [home-assistant/frontend#8730]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to make an automation, or in general using dropdown on mobile, even the app and in browser its hard to select a searched enitity. The problem is especially in the action section in the automation editor when I create an automation the trigger goes ok, but when selecting an action I can click on any item in the select and it just closes, not selecting it

### Describe the behavior you expected

Be able to select any item in the dropdown and the input field is propagated with that item

### Steps to reproduce the issue

1. Open automation editor on mobile
2. Fill a item in trigger
3. Search for an item in the action and try to select
4. Dropdown closes without selecting the item you pressed on
...

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

All mobile browsers, incl. app

### Which operating system are you using to run this browser?

Only on mobile

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by docsparks** [comment]
the drop down is also very narrow and makes it difficult to se the names beyond "automation.alwa....."

**Comment by JonLaliberte** [comment]
Video example here. In the video I'm searching then trying to tap on one of the entities. The menu disappears without selecting anything.


https://user-images.githubusercontent.com/5403662/113479356-a0c37c00-945c-11eb-9e64-ee288d757747.mp4

**Comment by alekslyse** [comment]
I can confirm the video above show the dropdown behaviour on my devices too

**Comment by alekslyse** [comment]
Still an issue for me

**Comment by JonLaliberte** [comment]
This still happens. 
These are also some z-index issues on some menus.

**Comment by FredrikNas** [comment]
I was going to report this as well, it has been an issue for many many versions now, and i´m kinda surprised that it haven´t been fixed, as it makes using a cell phone to actually administrate your cards/settings a hassle. 

Im using the latest version of IOS on Iphone 12 pro max in the companion app (to be fair, the problem is exactly the same when using Chrome on IOS as well, re-verified this right now)

There is a work around though:  to fix/cope with the issue is to "long press and rub/scroll" the list up and down before selecting the entity/value desired in the dropdown.  

Here is a video of the issue, and after the issue, the solution: https://drive.google.com/file/d/1-pD5xTfDMiykQmwraiQABB-CDpp7ygCV/view?usp=sharing
