### ISSUE TITLE
Quickbar doesn't show options in other language

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#8810]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The quickbar doesn't show script reloading in my language (German).
If i switch to English, it seems all options are shown. 
See screenshots below.

### Describe the behavior you expected

Quickbar should show all options in all languages.

### Steps to reproduce the issue

1. Set UI to german, Reload browser
2. Open quickbar, type 'script'
3. Change UI to englisch, Reload browser
4. OpOpen quickbar, type 'script'

### What version of Home Assistant Core has the issue?

core-2021.4.0b4

### In which browser are you experiencing the issue with?

Latest FF and Chrome

### Which operating system are you using to run this browser?

Ubuntu 18.03

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

UI setting  German:
![Auswahl_457](https://user-images.githubusercontent.com/26381449/113506597-08a1c180-9546-11eb-9677-8c5b3b1b7fb8.png)

UI setting English
![Auswahl_458](https://user-images.githubusercontent.com/26381449/113506602-0dff0c00-9546-11eb-98fa-e03228a88dd3.png)

**Comment by spacegaier** [comment]
Well in German you spell it "Skript" so with a "k" and then the option is there 😉.

![image](https://user-images.githubusercontent.com/114137/113513740-6a285700-956b-11eb-9585-650f8ab480fa.png)

**Comment by VDRainer** [comment]
Ha! You're right.
But why do i have to type 'input' to find in German spelled 'Eingabe' options?
I think this should be consistent and the english options should be found in all languages.

**Comment by spacegaier** [comment]
All of that is controlled by the community translations.

In the German translations "Vorlage" is mostly used for blueprint and "Template" for templates (the latter one one could potentially use "Muster" if we wanted to translate it as well).

I just corrected a few inconsistencies in the translations, but feel free to chime in on the Lokalise platform.

**Comment by VDRainer** [comment]
> In the German translations "Vorlage" is mostly used for blueprint and "Template" for templates (the latter one one could potentially use "Muster" if we wanted to translate it as well).

That's why i think the english values should always be found.

If i configure something in yaml i use 'script', 'templates', ... and so on.
Then i have to think about how someone translates this and maybe have multiple choices.

**Comment by spacegaier** [comment]
@donkawechico @bramkragten What do you think?

**Comment by donkawechico** [comment]
My worry is that by including the english terms behind the scenes, but still _showing_ only the translated text, that we will end up with confusing items showing up before the item you were looking for.

I only speak english so I can't think of a real-world example, but let's suppose your language is set to german, and you want to find "Neu Laden FOOBAR". So you type "FOO". 

And you get back these items:

* Navigieren to Abc [because, in english, this happens to translate to "Navigate to **Foo**"]
* Neu Laden Zzz [because, in english, this happens to translate to "Reload **Foo**tball"]
* Neu Laden FOOBAR

The user might wonder why the first two options even _exist_ in the list, let alone show up above the option they actually want.

However, I think there are some reasonable compromise solutions we can explore. But I don't think it will be as simple as just secretly adding english translations to the terms to be filtered against.

**Comment by bramkragten** [comment]
I think we should add just the keys, so script, automation, template, etc, that will also make it easier to program, and we could indeed give it a slightly lower score
