### ISSUE TITLE
Unusable Preload stream checkbox appears on camera more info, mobile only

### ISSUE THREAD

**Issue by Alfiegerner** [home-assistant/frontend#9107]
### The problem

Opening a more info panel for camera on desktop has no 'Preload Stream' checkbox:

![image](https://user-images.githubusercontent.com/596188/117117795-11571300-ade4-11eb-8429-0b9c416abd73.png)

On mobile for the same entity the more-info box shows this checkbox:

![image](https://user-images.githubusercontent.com/596188/117118038-5da25300-ade4-11eb-8758-06ad29e5d228.png)

But it's not usable, i.e. clicking it doesn't do anything.

I came across this as I was trying to work out how to activate Preload Streams for an RTMP based Camera using a stream_source.

Not a biggy. 

### What is version of Home Assistant Core has the issue?

core-2021.4.6

### What was the last working version of Home Assistant Core?

unknown

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Camera / Stream

**Comment by spacegaier** [comment]
Can you check in your browser dev tools / console if there are any errors? I had a quick glance at the coding and it should behave the same on desktop and mobile. But since I don't have any cameras in HA, its' not something I can dig into.

In the browser dev tools network monitor, there should be a call to `camera/get_prefs` in the websocket. If that fails, then the checkbox might not be rendered.

**Comment by Alfiegerner** [comment]
No errors I'm afraid.  I can replicate the problem both using my mobile and using dev-tools to simulate a mobile device in my desktop browser.

You may be able to set up a dummy camera device e.g. setting it some web stream if you want to see it locally,

**Comment by bramkragten** [comment]
The styling seems off, fixed here #9115
