### ISSUE TITLE
Lights show as "on" after call to light.turn_off

### ISSUE THREAD

**Issue by DoubtfulBadger** [home-assistant/frontend#9459]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have several automations (coded in Node Red), which call "light.turn_on" when a motion sensor is triggered. Once the motion sensor detects no movement, it calls "light.turn_off".
In three of my automations, I get the message "turned **on** by service light.turn_**off**". When this happens, the light turns off but the indicator, in Lovelace, shows that the light is still on. This leads to confusion.
![Screenshot from 2021-06-23 13-10-54](https://user-images.githubusercontent.com/70652748/123094269-9ba31700-d424-11eb-9f56-d9ebba8640c1.png)
![Screenshot from 2021-06-23 13-10-09](https://user-images.githubusercontent.com/70652748/123094270-9cd44400-d424-11eb-941b-fdf34c2d8490.png)
[Home Assistant Info.txt](https://github.com/home-assistant/frontend/files/6701700/Home.Assistant.Info.txt)

### Describe the behavior you expected

I expect the "light.turn_off" to produce the message "turned **off** by service light.turn_**off**" and the icon to change to "off".

### Steps to reproduce the issue

1. This happens every time my motion sensor detects no movement.
2. Incidentally, my sensor only calls "light.turn_on" when the time is between sunset and sunrise.
...

### What version of Home Assistant Core has the issue?

core-2021.6.6

### In which browser are you experiencing the issue with?

Vivaldi 4.0.2312.33 (Stable channel) stable (64-bit)

### Which operating system are you using to run this browser?

Manjaro 21.0.7

**Comment by spacegaier** [comment]
I cannot reproduce that issue. `light.turn_off` in an automation works fine for me. Frontend shows correct state for the light. In the logbook I have different messages since my automation triggered the service and that is correctly stated there.

![image](https://user-images.githubusercontent.com/114137/123324546-3724ac80-d537-11eb-8691-4e1265422db6.png)

If those were regular HA automations, the traces would now have been interesting to verify the behavior. Not sure if Node Red has something similar.

I also found this: https://www.reddit.com/r/homeassistant/comments/7ojcb8/homeassistantturn_on_or_lightturn_on/

**Comment by DoubtfulBadger** [comment]
Hi spacegaier,
Thanks for your reply. I wasn't aware that "homeassistant.turn_off" existed. I have changed the automation for one of the lights but the result is still the same - see attached.
![Screenshot from 2021-06-25 13-05-40](https://user-images.githubusercontent.com/70652748/123422783-98d82b80-d5b6-11eb-8d20-decf3228be78.png)

**Comment by spacegaier** [comment]
`light.turn_off` should be the right service anyway. "Good" that it is at least consistent across homeassistant and light though :) .
