### ISSUE TITLE
Hidden history graph traces reappear

### ISSUE THREAD

**Issue by rharvey525** [home-assistant/frontend#9630]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on some entities to hide them from a history graph they initially disappear and are striked out. After a period of time the line reappears, but it stays crossed out in the key. This happens on 

### Describe the behavior you expected

Line to remain hidden from the chart

### Steps to reproduce the issue

1. Hide an entity on a history graph that has more then one entity
2. Wait (normally with 30s)
3. See the line reapper
...

### What version of Home Assistant Core has the issue?

core-2021.7.2

### In which browser are you experiencing the issue with?

Android App 2021.6.2-full

### Which operating system are you using to run this browser?

Android 11

### Additional information

http://youtu.be/hHlkODNXJHE

**Comment by Youpimatin** [comment]
Same problem here, entities reappear at each graph data refresh. This problem didn't exist until my update from 2021.6.6 to 2021.7.4.

This plus the problem of new useless colors.
And the problem of text of entities names taking much space than before...

Which part should I reverse in my backup of 2021.6.6 ?
Will a partial restore of "Home Assistant (2021.6.6)" work to give me back my colors and no bug on my setup ?
I fear each update of home assistant, because there is often things that worked before, but don't work afterwards.
And it's not a thing of "It was better before"... but just "It worked before" :'(

**Comment by j-pas** [comment]
The issue still exists in release core-2021.8.6.
I experience it in multiple browsers on both Android and Windows.
