### ISSUE TITLE
Slow connecting on Firefox

### ISSUE THREAD

**Issue by petersohn** [home-assistant/frontend#9668]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

At first time I load Home Assistant, everything works fine. Later, the connection is lost and trying to reconnect takes a long time (about a minute). Reloading the page does not help, the page is stuck on the loading page. Neither does clearing the cache or using incognito mode. Restarting the browser solves the issue for some time, but eventually it will become slow again.

I tried restarting Home Assistant right after restarting the browser, and then it managed to reconnect quickly. The problem only comes out after it has been running for some time.

I tried reproducing the issue on Chrome, but I couldn't.

### Describe the behavior you expected

If the connection is lost, the browser should be able to quickly reconnect.

### Steps to reproduce the issue

1. Load Home Assistant on Firefox.
2. Keep using the computer with the focus away from Home Assistant's tab.
3. Eventually, when focusing the tab again, it will say "Connection is lost, reconnecting...", and keep being on that state again.

### What version of Home Assistant Core has the issue?

2021.7.4, frontend 20210707.0 

### In which browser are you experiencing the issue with?

Firefox 90.0.2

### Which operating system are you using to run this browser?

Gentoo Linux amd64/17.1/desktop

**Comment by OverZealous** [comment]
A hint here, that might not help. I've been experiencing this for a long time, and it definitely seemed to start happening after some Firefox update. Probably a couple months.

But I also have the toolbar extension installed, and it always loads instantly.

I finally figured out that I was using my external URL (`https://[domain]:8123/`) for the toolbar, and my internal URL (`http://homeassistant.local:8123`) for my Firefox bookmark.

Like you, I tried clearing cookies & cache (all site data, actually), but it was still slow.

I switched to using the external URL, and it's instant again! So I think Firefox _might_ be unhappy with the local URL. I also just tried it using the raw IP (instead of `homeassistant.local`), and it was snappy. I'm guessing it's related to how Firefox looks up DNS queries.

**Comment by petersohn** [comment]
You suggestion seems to work. In this case, the issue is actually that HA doesn't work on IPv6.

**Comment by petersohn** [comment]
Correction: the external address solves the problem, but disabling ipv6 dies not.

**Comment by WallyDW** [comment]
Could you try to test it with the internal IP address instead of the internal URL?
If the internal IP address works, then its not HA, but a part of the DNS lookup process, like the browser, the client OS or the DNS service.

**Comment by petersohn** [comment]
I've always used the internal IP.

**Comment by WallyDW** [comment]
Ok, I use Firefox myself, but on Windows, and I have had no problems with that.

But I have had issues with an automation that went crazy at times and slowed HA down alot causing slowdowns and the situations you describe.
That automation worked flawlessly before, but started to act up recently.
Its just an automation that decreases a counter each second, so nothing advanced, but it caused logs to be filled with messages about exceeding queued message limit of 2048 for the websocket module.

**Comment by petersohn** [comment]
I got the issue even on the external address. Interestingly, on my home computer, from which I can access both the internal and the external address, it slows down on the internal one but works fine on the external. However, I get slowdowns on the external address from outside, for example on my workplace computer (also on Linux).

**Comment by DavidZidar** [comment]
I have the same issue, it only happens in Firefox and only when loading Home Assistant. Super annoying.

Has anyone been able to find a fix or workaround?

**Comment by ekeih** [comment]
I had the same issue for weeks, but recently it started working again. Not sure if a home-assistant update or a firefox update fixed it, but with both on the latest version it works perfectly.

**Comment by DavidZidar** [comment]
Interesting, I'm running the latest version of both and I've had this issue for months.

**Comment by WallyDW** [comment]
Look, a server answers requests on a port on a machine with an IP address.
A server does not care about the URLs a user is using, so if you see different results on the internal and external URLs, then you need to look at the chain of services and infrastructure used before the connection to the server occur.

**Comment by DavidZidar** [comment]
I've been checking the dev tools when this is happening, the strange thing is that there are no pending requests when the spinner is showing, it's just doing nothing for minutes.. and then all of a sudden it loads the UI.

**Comment by WallyDW** [comment]
There is a lot of things happening you will never see in the dev tools of a browser.
You need to check deeper to get it all, like wiretapping with something like wireshark to get network traffic and a real debugger to get what the different processes in the OS is actually doing on the hardware.

It might be a timeout somewhere, like a network connection that is missing the final close package due to a faulty firewall or router setup or a slow virus scanner that try to use a cloud scanning service over a slow internet connection and it blocks the HA GUI untill it gets the response from the cloud scanning.

**Comment by DavidZidar** [comment]
Not likely. It is probably a bug somewhere in HA, maybe in the service worker.

**Comment by WallyDW** [comment]
You would not see the error on only one type of connection.
HA does nothing different if the connection is external or internal. It's just a IP address to it.

**Comment by DavidZidar** [comment]
I said nothing about that. My HA is in my LAN behind an Nginx proxy, the connection is rock solid. This is not a network issue. It is a bug, plain and simple.

**Comment by WallyDW** [comment]
ok, then its not the same as the original poster, which was who I replied to actually. :)
He has different experiences depending on what connection he is on.

**Comment by DavidZidar** [comment]
Alright, but it might still be the same bug. The flawed behavior seems exactly the same. It might be a bug in Firefox though, hard to tell without more investigation.

**Comment by WallyDW** [comment]
True, and it might also be something different.
The same symptom does not equal the same bug.

The issue with the original problem in the thread is the fact that sitting on the internal network and accessing the internal HA through the external address is faster than accessing the internal HA through the internal address from the same place.
That should not be possible in a normally network setup without advanced multiple routes.

It might be the same bug, but these contradicting descriptions blurs the picture and untill it is cleared up it will be hard to solve the problem.
You are probably better off starting a new thread where your issue is not mixed up in this.
If either of you are getting the issue resolved, then it just prefect for the other.

**Comment by DavidZidar** [comment]
@WallyDW I'm sorry, but I think you have confused things. The original post describes my issue perfectly, it makes no mention of what you speak of.

**Comment by DavidZidar** [comment]
I submitted issue #10122

**Comment by DavidZidar** [comment]
I finally figured out my issue. It wasn't Home Assistant (sort of) and it wasn't Firefox (sort of), apparently I had accidentally configured web sockets incorrectly on a completely different site on the same Nginx proxy, so even though that site was completely unrelated to Home Assistant it kept breaking Home Assistant just because I had that other site open in another tab.

Now that I've fixed the web socket configuration for the other site Home Assistant once again loads instantly.

That said, it sort of is an issue with Home Assistant too because the UI shouldn't fail to load just because there is an issue with the web socket connection and it's sort of an issue with Firefox too because one site shouldn't break another site even if they're served by the same server.
