### ISSUE TITLE
Text overflow in a charts legend

### ISSUE THREAD

**Issue by ChopperRob** [home-assistant/frontend#9745]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The listitems in a chart's legend have "ellipsis" set for the text-overflow, but this does not work. The text does not get cutoff when the size is bigger then the card.
This seems to be caused by the "inline-flex" on the display property.

### Describe the behavior you expected

the text not exceed the boundaries of the card

### Steps to reproduce the issue

1. add a chart card to a dashboard with an entity which has a long name.
2. make the browser window smaller until the entity name doesn't fit in the card.

### What version of Home Assistant Core has the issue?

2021.8.3

**Comment by lcavalli** [comment]
The bug is still present in version 2021.11.5.
A discussion is reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=912434

To make legend entries a little bit shorter sensor friendly name could be removed from label:
![image](https://user-images.githubusercontent.com/6123641/143288260-8f702c1e-3cb2-4fb1-9279-badfc0d59edd.png)
In this example "Condizionatore Soggiorno" is redundant.
