### ISSUE TITLE
New design pattern for Lovelace edit mode

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#9826]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently you can edit your Lovelace dashboard by clicking on the three dots that opens a menu with the options `Edit Dashboard` and `Help`.
![Help in droplist](https://user-images.githubusercontent.com/20203284/129546644-4525cf54-193f-4ee5-942a-61e8ad86ee49.png)

In the edit mode you find the three dots again with different menu options and a help icon. When you're done editing you should click on the `X` on the left.
![Help in topbar](https://user-images.githubusercontent.com/20203284/129546651-8ee8cae2-cc43-420f-8fb8-12fc9db30aec.png)

### The problem
- Edit mode is an extra click away.
- Don't know if you should have a `help` icon before you edit a dashboard.
- When in edit mode, the three dot menu is different then before.
- The close button is on the left, that is inconsistent and on a different place where the edit mode started.

### My proposal
In edit mode make a clear `Done` button on the top right, keep the help icon and menu.
![Help icon only on edit mode Make a clear ‘Done’ button Help should give a dialog, same as in configuration](https://user-images.githubusercontent.com/20203284/129548178-c5b96298-679b-491f-9b39-6bd7658bc82e.png)

### Steps to reproduce the issue

1. Open a Lovelace dashboard
2. Click on the three dots in the top right corner
3. Hit `Edit Dashboard`

### What version of Home Assistant Core has the issue?

core-2021.8.5

**Comment by goutammalakar1988** [comment]
@OverloadUT

**Comment by goutammalakar1988** [comment]
Hi

**Comment by noxhirsch** [comment]
While I like the idea of the "Done" button, I don't really like the idea of an edit button always visible. It attracts much more attention than the old button with the three dots - with that, the dashboard looks way cleaner. I think that many people don't change their dashboard so often, that they need the edit button directly on the screen.
On mobile devices with small screens, the icon competes even more with the icons of views:
![image](https://user-images.githubusercontent.com/30938717/135766881-4189edd1-78b7-49ad-afac-3f3657df0024.png)
 A two-click solution also protects it from beeing clicked accidentially on mobile devices.

**Comment by spacegaier** [comment]
I think @noxhirsch got a valid point. The three dots menu looks cleaner plus it is a kind of safeguard. But I agree with the other points from @matthiasdebaat esp. the "Done" part and the fact that it is not really clear to the user that the same three dots menu have different options depending on the mode.

=> What would be the best option for when in edit mode? Just use a different icon instead of the three dots?

**Comment by matthiasdebaat** [comment]
I agree, the three dots looks nicer than the pencil icon. So its what to prefer:

1. Visual Design, keep the current three dots overflow menu and change the `X` to a `Done` button
2. Interaction Design, as this issue suggested.

I can live with both.

**Comment by spacegaier** [comment]
@matthiasdebaat If we keep the current three dot menu to enter the edit mode (my and noxhirsch's current preference), could it make sense to then show a different icon for the overflow menu to tell the user that now in edit mode there are different options there or is that confusing since we would use another icon that is not clearly associated with an overflow icon? 

No real idea yet which one could be used. Purely going by name, but that looks more like a direct action and not an overflow menu icon.
![image](https://user-images.githubusercontent.com/114137/147873125-e5f70940-7187-414a-8427-390cd5fd8e1f.png)

**Comment by matthiasdebaat** [comment]
Let's only change the edit mode by changed the `x` to a `Done` button. I've changed the opening post to keep things clear.
