### ISSUE TITLE
Supervisor does not support RTL

### ISSUE THREAD

**Issue by tzagim** [home-assistant/frontend#9865]
### Describe the issue you are experiencing

The Supervisor does not support RTL on all tabs except the backups

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

core-2021.8.8

### Steps to reproduce the issue

This can be seen in the change of language to RTL languages (Hebrew, Arabic, etc.)

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

**Comment by niraviry** [comment]
I have opened an issue long time ago (#4922) about RTL problems. It was closed due to lack of activity. The bugs are still there.
There are few but not too much. It is like this since many version ago, maybe from the start.
Since than, a new one popped up some time ago where the lovelace editor is right justified or in RTL writing direction.
It can be switched back but one must do that each editing.
I can stretch the exact bugs and how to solve them.
When units are in English they should be placed on the right side of the value and not on the left side.
For instance a value in a card starts from right. 1st tab is the icon which is  OK. 2nd one is the entity name - OK, 3rd one is the value and 4th one is the units. Simply switch between the 3rd and the 4th than it will all be OK.
I can explain some more but lets see if things move.

**Comment by tzagim** [comment]
Hi @niraviry.
Can you present your solution in a practical way and open a pull request?

כשזה יהיה משהו מעשי יהיה קל יותר לקדם את זה

**Comment by niraviry** [comment]
Hi.

Its seems like you do not fix the issues of the RTL languages. Some are
serious bugs that make it hard to work with, like the inability editor that
is an LTR syntax but appears as RTL and can't be searched for text or
edited normally.

I assume it is the same bug as with other RTL languages, like arabic.

Please fix these bugs.
The 3 major bugs are the above 2 in the lovelace editor and the climate
thermostat's visual appearance where the numbers are half hidden due to the
RTL.
There should be any special RTL implementation to a thermostat at all.

Nir Aviry

‫בתאריך שבת, 15 בינו׳ 2022 ב-15:06 מאת ‪github-actions[bot]‬‏ <‪
***@***.***‬‏>:‬
